### ISSUE TITLE
rr4dj directory not created

### ISSUE THREAD

**Issue by SevenW** [openhab/openhab1-addons#1195]
As a result of permission settings, the rrd4j folder does not get created, resulting in errors like this:
21:17:00.010 ERROR o.o.p.r.internal.RRD4jService[:232]- Could not create rrd4j database file '/usr/share/openhab/etc/rrd4j/Weather_Temperature.rrd': /usr/share/openhab/etc/rrd4j/Weather_Temperature.rrd (Permission denied)

manually creating the folder '/usr/share/openhab/etc/rrd4j' and setting permissions right did the trick. It was not done by the installer, and once openhab is running as user openhab, it does not have the permission to write in '/usr/share/openhab/etc' I think.

**Comment by lahouarami** [comment]
I had the same problem and it needs to delete the /opt/openhab/etc/rrd4j folder, then it will be created automatically by OH and just not forget to give permissions to your current directory after deleting it.
I hope this will help.
