### ISSUE TITLE
KNX Binding misbehaving (v1.5.1)

### ISSUE THREAD

**Issue by tdeckers** [openhab/openhab1-addons#1406]
I've just upgraded to 1.5.1 and I see KNX misbehaving in the following way:
- Warning on startup: 

`09:53:07.380 WARN  o.o.m.i.i.GenericItemProvider[:108] - Attempted to register a second BindingConfigReader of type 'knx'. The primaraly reader will remain active!`
- Not all KNX items get initialized - only half of them are.  Some are initiatialized twice:

`09:53:14.390 INFO  runtime.busevents[:26] - l0_livingSalon state updated to OFF 
09:53:14.540 INFO  runtime.busevents[:26] - l0_livingSalon state updated to OFF`
- When I update an items file and it gets reloaded I get an error and KNX binding stops alltogether:

`09:54:54.759 INFO  o.o.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'knx.items'
09:54:55.091 ERROR o.o.m.c.i.f.FolderObserver[:105] - An unexpected exception has occured
java.lang.NullPointerException: null
    at org.openhab.model.item.binding.AbstractGenericBindingProvider.removeConfigurations(AbstractGenericBindingProvider.java:93)
09:55:05.139 INFO  o.o.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'knx.items'
09:55:05.319 ERROR o.o.m.c.i.f.FolderObserver[:105] - An unexpected exception has occured
java.lang.NullPointerException: null
    at org.openhab.model.item.binding.AbstractGenericBindingProvider.removeConfigurations(AbstractGenericBindingProvider.java:93)`

This last error keeps being repeated.  I restarted to install but no difference.

Any insights?

**Comment by jochen-mattes** [comment]
what error message were you looking for? I have the same problem, but have about 4,500 Items in my project. An error message to look out for, would be very helpful.
