### ISSUE TITLE
my.openhab actions are not resolved in Designer

### ISSUE THREAD

**Issue by staehler** [openhab/openhab1-addons#1497]
The actions sendSMS and sendNotification from org.openhab.io.myopenhab-1.4.0-SNAPSHOT.jar couldn't be resolved by Designer and are marked with this comment:
"Couldn't resolve reference to JvmIdentifiableElement 'sendNotification'."

**Comment by GertKonemann** [comment]
I have this problem on Windows with the snapshot version of today. Both this issues and 1164 are closed, but the problem is not solved.

**Comment by kaikreuzer** [comment]
I reopened #1164
