### ISSUE TITLE
MAX!Cube Binding: Do not set thermostat to manual when changing temperature

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab1-addons#1599]
When changing the temperature for a thermostat with openHAB, the operation mode of the thermostat is automatically set to manual even if it was automatic.

This should not happen as it makes the termostat ignore the weekly program set in MAX!Cube.
If the MAX!Cube software is used, or the termostat is controlled directly, adjustment of the temperature does not change the operation mode. The temperature is therefore only changed until the next trigger from the weekly program arrives.

Switching the operation mode between auto and manual could be possible in an own item.

**Comment by gstiegl** [comment]
- Set mode to manual and use custom temperature value (this is currently implemented in the binding)

Hm, I do not finde any description on the binding documentation how to do this. Is this currently implemented?
