### ISSUE TITLE
HABDroid won't work over VPN

### ISSUE THREAD

**Issue by ghost** [openhab/openhab1-addons#1628]
I'm using OpenVPN to connect to my home network. Connecting to http://$host:$port/openhab.app trough my VPN works fine in the mobile device's browser, so it's not a network issue.

---

Issue/observed behaviour:
Having entered both "openHAB URL" and "openHAB Remote URL", trying to connect trough VPN first displays "Connect to remote URL" and then "Connection to http://$host:$port refused" shortly thereafter.

Having entered only "openHAB URL", an error about openHAB not running or the configuration being wrong is displayed.

There is no way to get openHAB to connect trough a VPN.

---

expected behaviour:

HABDroid should be able to connect to a "local" installation trough a VPN.

---

Proposals for a solution:
- Use the default route rather than trying to figure out which network interface to use (perhaps via a toggleable option).
- Provide an "always use openHAB URL" option (i.e. "Don't try to connect via mobile radio interfaces").

**Comment by mikeybs** [comment]
I am having this issue as well.  I have tried using both OpenVPN for Android and OpenVPN Connect as vpn clients.  I am able to connect to the web interface fine using chrome over the vpn.  In HABDroid I have the following set for openHAB Remote URL:
http://192.168.60.10:8080/openhab.app?sitemap=demo

I left openHAB URL blank

any advice would be appreciated

**Comment by belovictor** [comment]
Set it to http://192.168.60.10:8080

**Comment by mikeybs** [comment]
that did the trick.  thank you.  it might be nice to include a sample URL in the settings section
