### ISSUE TITLE
RRD4J Persistence warning

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab1-addons#1846]
Occasionally I get the follwing warning from the rrd4j persistence service:
2014-12-15 05:32:00.419 WARN  o.o.p.r.internal.RRD4jService[:144]- Could not persist 'CO2_Netatmo_Indoor_I' to rrd4j database: null

Usually this warning occurs several minutes in a row and then for several hours not at all.

This item is the only item with which I get this kind of warning. The CO2_Netatmo_Indoor_I.rrd file exists and its timestamp gets updated.

The item is defined as:
Number CO2_Netatmo_Indoor_I             "CO2 [%d ppm]"                      <temperature> (gMesswerte)      {netatmo="00:00:00:00:00:00 #Co2"}

It is persisted with 
gMesswerte\* : strategy = everyMinute

The values are displayed correctly. There is no warning regarding this item from other persistence services I use.
##

**Comment by J-N-K** [comment]
I think this is not a problem with the RRD4J persistence service. If you are still interested (and the problem still exists), I can provide a debug-version of the binding to check if the persistence service is behaving correctly or not.
