### ISSUE TITLE
Problems with zwave binding

### ISSUE THREAD

**Issue by rmshep** [openhab/openhab1-addons#1857]
I am new to Openhab, but have been in home automation for some time. I have been using Homeseer.  I am trying to get Openhab working instead of upgrading to HomeSeer 3.

Whenever I start openhab, I get this message from the zwave binding:

2014-12-18 09:28:13.072 INFO  o.o.b.z.i.p.ZWaveController[:376]- Connecting to serial port /dev/zwaveUSB
2014-12-18 09:28:13.175 ERROR o.o.b.z.i.p.ZWaveController[:391]- Port /dev/zwaveUSB does not exist

The port does exist. I can see it created dynamically by the kernel, I see the cp210x module loaded.  I have tried this with 2 different Aeon  labs Z-sticks.  The Kernel is 3.14.23-100 on fedora 19.

can anyone help with what I am doing wrong?

thanks 

bob shepard

**Comment by angelstarr** [comment]
Any update?

**Comment by cdjackson** [comment]
Any update on what? This issue is closed - if you have a question or problem youd be best opening an issue or posting to the group.
