### ISSUE TITLE
Weather binding - support of variable formatting and maps in the layouts

### ISSUE THREAD

**Issue by TiS** [openhab/openhab1-addons#2401]
Hi

It would be very nice, if support of variable formatting and maps were added in layouts.

For some / most things I can use items. But then I lose the functionality of one-layout-multiple-locations.

I'd appreciate especially map support, so I'd be able to translate some messages to my language (forecast day names, for example).

Variable formatting will also be appreciated, especially for date/time (last observation time, now rendered as dump of date/time object).

The syntax can look like `${CURRENT_SYNTAX|"FORMAT"}`. For map it could be `${MAP(map_name,CURRENT_SYNTAX)}` or `${CURRENT_SYNTAX|MAP(MAP_NAME)}` to be more concise.
##

**Comment by teichsta** [comment]
could you please have a look at this @gerrieg? Thanks, Thomas E.-E.

**Comment by staehler** [comment]
I've a further wish for enhancement:
unfortunately, with the new weather binding a feature disappeared which enabled me to reference to any item and place it in the layout. E.g. I have my own temperature and wind sensor, which should be displayed in the weather layout instead of the weather binding values fetched from the weather provider.

The above mapping feature I miss as well.

Regards,
Michael

**Comment by 9037568** [comment]
The wiki appears to indicate variable formatting is already supported.

**Comment by staehler** [comment]
@9037568 it's not the formatting of variables, but the lack of including own weather data. The weather bindung support just the data from the provider. As I have my own weather station, I'ld prefer to show my own data und would just enrich the applet with some data from the provider. The weather binding was able to include own data in the past, but this feature disappeared - unfortunately.

**Comment by 9037568** [comment]
Closing this ticket as abandoned. If there is a new feature anyone still needs, please open a new ticket.
