### ISSUE TITLE
Persisting nonexistent Groups/Items does not cause an Error/Warning/Info

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab1-addons#2515]
When there are nonexistent Groups/Items in the persistence-configuration it does not show an Error/Warning/Info.
At least a warning or info on the refresh of the model would be helpful.
You can easy reproduce it by adding the following lines to your config:

blalba1: everyMinute
blalba*: everyMinute
##

**Comment by SirTomme** [comment]
Appreciated.
A warning in the logs that I forgot do explicitly define my group in the items file would have saved me a lot of time.

**Comment by J-N-K** [comment]
https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/internal/PersistenceManager.java#L318

https://github.com/eclipse/smarthome/blob/master/bundles/model/org.eclipse.smarthome.model.persistence/src/org/eclipse/smarthome/model/persistence/internal/PersistenceManager.java#L331

so the request is to change DEBUG to WARN?

**Comment by 9037568** [comment]
Closing as abandoned.
