### ISSUE TITLE
Faulty rules leads to "silent crash" on openhab startup

### ISSUE THREAD

**Issue by PascalTurbo** [openhab/openhab1-addons#2692]
Since the upgrade to 1.7 I found this critical behaviour:

If you have a rule which would result in an exception; in my case it throws this one:

```
2015-06-05 09:53:00.326 [ERROR] [.o.m.r.i.engine.ExecuteRuleJob] - Error during the execution of rule Update Supply Current Consumption
java.lang.NullPointerException: cannot invoke method public abstract org.openhab.core.types.State org.openhab.core.persistence.HistoricItem.getState() on null
```

and you restart openhab then the whole system will silently die. It won't execute any rules nor will there be any message sent to the event bus. I tried this a lot of times and always got the same result.

Again for clarification:
1. Create a rule which will result in an exception on execution
2. Restart openhab
3. have a look at the event bus and the openhab.log -> There will be no new events and the systems seems to do nothing
##

**Comment by teichsta** [comment]
for some reason one of my rules regularly throws an exception but this doesn't lead to the described behaviour. @PascalTurbo did you discuss this behaviour on the Group before opening this issue? Best, Thomas E.-E.

**Comment by PascalTurbo** [comment]
@teichsta: I didn't. But I'm able to reproduce this issue. Maybe I could support you with some example?

**Comment by teichsta** [comment]
that would be great … would you?

**Comment by PascalTurbo** [comment]
So first I created a video demonstrating what happend after starting openhab with activated rules.
Have a look at this video: https://www.youtube.com/watch?v=ezd09IgEVu8

Next I created a github repository and placed my configuration in it: https://github.com/PascalTurbo/openhab_configuration

**Comment by dominicdesu** [comment]
@PascalTurbo I had a similar issue where openhab silently stops executing rules, described in #2646.
Maybe our issues are related? What happens if you remove the restoreOnStartup option for all items from the rrd4j configuration?

**Comment by PascalTurbo** [comment]
@dominicdesu you've just made my day! 

That seems to be the trigger of the problem. I've disabled the restoreOnStartup and OpenHab works fine.

**Comment by dominicdesu** [comment]
Now we only need to find somebody to fix #2646 ;-)

**Comment by brettyj** [comment]
Looks like I'm getting this issue too. Setting restoreonstartup to false feels like it kinda defeats the point of rrd4j, so I'm eagerly awaiting this fix :)

**Comment by MrMontesa** [comment]
I might have that problem as well. I started a thread at [community.openhab.org](https://community.openhab.org/t/rule-sometimes-not-triggered-from-astro-binding/2523) since my rules are not properly working in 1.7.1. At the end I downgraded to 1.7.0 and everything started working as expected.

**Comment by MrMontesa** [comment]
Is there any idea how to tackle this issue?
I have a bad feeling updating again to 1.7.1. Are the masterminds aka @teichsta & @kaikreuzer aware of this issue? Can we somehow assist in troubleshooting/analyzing? I'd like to help but am a bit puzzled where to start.
Thanks much

**Comment by brettyj** [comment]
I'm with you MrMontesa. I'm a bit concerned this issue isn't being fixed - it means I can't rely on a reboot of my HA server bringing back up OpenHAB correctly. I have to babysit it and ensure it's all working before I can leave it, and if it isn't, I just have to kill and relaunch openhab until it works...

**Comment by hmerk** [comment]
Is this still existing in oh 1.8.3 or latest 1.9 snapshot ?

**Comment by PascalTurbo** [comment]
@hmerk It's existing in 1.8.3. Can't check for latest snapshot

**Comment by 9037568** [comment]
Perhaps the solution mentioned in this ticket would work here, too?
https://github.com/openhab/openhab/issues/3578

**Comment by hmerk** [comment]
Sill existing ?
