### ISSUE TITLE
Rfxcom binding: binding actions should bind to BaseType, not Type

### ISSUE THREAD

**Issue by gersilex** [openhab/openhab1-addons#3009]
If I bind and rfxcom ValueSelector input to Groups, the binding fails, because it tries to bind to **GroupItem** instead of the BaseType **SwitchItem** for each item. This should be the case.
## Reproduction

default.items

```
Group:Switch:SUM devices_leroy   "Geräte von Leroy [%d aktiv]"           <devices>        (devices)  { rfxcom="<P.5:Command"  }
```

```
osgi> openhab items
devices_leroy (Type=GroupItem, BaseType=SwitchItem, Members=5, State=2)
```

``````
sh> cat openhab.log
00:18:59 ERROR o.o.m.i.i.GenericItemProvider | Binding configuration of type 'rfxcom' of item ‘devices_leroy‘ could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: Invalid item type for value selector 'Command'!```

**Comment by 9037568** [comment]
GenericItemProvder is now in ESH. As no further releases are planned for the OH1 platform, this cannot be addressed here.

**Comment by 9037568** [comment]
I may have misread this. The log message referenced does come from the binding...

**Comment by gersilex** [comment]
Obsoleted by new handling of Groups in ESH.
