### ISSUE TITLE
Feature request for Weather binding: map the Wunderground sunset/sunrise data elements

### ISSUE THREAD

**Issue by djm300** [openhab/openhab1-addons#3095]
Would be interested in integrating the same type of weather info as currently available in the iPhone IOS8 Weather app (would improve the WAF: Wife Acceptance Factor, thanks http://jpmens.net/ for introducing the term to me). Since IOS8, the Weather app no longer uses Yahoo as the weather data provider but the Weather Channel, which is raw-data-wise the same as Wunderground.

According to the debug logs in binding 1.7.1, sunrise & sunset times are not mapped and neither are the hourly forecasts (ranging from 0-24h in the future). 

I would be very grateful if such a feature would be added in the Weather app.
##

**Comment by 9037568** [comment]
It's not clear to me what this request is exactly.

What do you want map these items to?
