### ISSUE TITLE
FS20Binding only works with UpDownType while dimming

### ISSUE THREAD

**Issue by wojtus** [openhab/openhab1-addons#3097]
Hallo,
the FS20CommandHelper.getStateFromFS20Command(FS20Command) interprets FS20s DIM_UP/DIM_DOWN allways as UpDownType.UP/UpDownType.DOWN;
This is not allways right. Using FS20 with a dimmer leeds to: 
 [DEBUG] [ore.internal.items.ItemUpdater:73   ] - Received update of a not accepted type (UpDownType) for item BzLampe 
The update of the state of the Dimmer fails. 
This funcionality must be configurable, to provie backwards compatible choice for rollershuther users.
For me it would be enough if it would be global configuration, not per item. 
To achive this some changes in FS20CommandHelper and FS20Binding and  are needed. 
FS20Binding could become configurable state variable, that controls the interpreting of DIM_UP/DIM_DOWN FS20 commands. 
What do you think about this idea? It woud fix my gap.
##

**Comment by 9037568** [comment]
I'd like to see the full debug log of this, along with the configuration information.
