### ISSUE TITLE
sendXbmcNotification stalls rule if host is offline

### ISSUE THREAD

**Issue by regnets** [openhab/openhab1-addons#3519]
When using sendXbmcNotification in a rule while the target host is not available the rule stalls.

When the host becomes available openhab send all not transfered messages at once to kodi.

There should be a Timeout for this action, so that the rule continues to work.

[EDIT]
It seems like there is a timeout of 1000ms configured in the action binding.

So this is no timeout. Maybe kodi is not sending an OK if kodi can't display the notification?

I experienced this behaviour with kodi in the background on a firetv.

Maybe this has to be fixed in kodi?
[/EDIT]
##

**Comment by 9037568** [comment]
Suggest taking up these issues in the [community forum](http://community.openhab.org/) if they're still ongoing.

**Comment by regnets** [comment]
Why is this issue closed? Nothing has changed. This is clearly reproducible.

**Comment by 9037568** [comment]
The "EDIT" from the original post made it unclear to me. That section seems to say OH is working correctly but there's a problem in "kodi".

Please clarify what the problem is and attach a debug log that shows the issue.
