### ISSUE TITLE
Snapshot binding for CCTV

### ISSUE THREAD

**Issue by PolishBen** [openhab/openhab1-addons#3583]
Hi All

This is a ticket to track the changes I plan to introduce for the snapshot CCTV binding as discussed here: https://community.openhab.org/t/binding-to-integrate-with-imagery-generated-by-motion-detection-cctv/2985/4

I need to get community feedback on the code and check it runs on OH2 before I can do a pull-request.

My fork with work in progress is here: https://github.com/PolishBen/openhab
##

**Comment by watou** [comment]
Could you share a JAR file and wiki page, and it's OK to submit a pull request for review only.  Thanks very much, Ben!

**Comment by PolishBen** [comment]
sure no problem - will do.  Will also work on sharing the sourecode on my fork too.

**Comment by PolishBen** [comment]
wiki page: https://github.com/openhab/openhab/wiki/Snapshot-Binding

I just need to add info about logging/debugging.

**Comment by PolishBen** [comment]
OK so I did the wiki page and here's the binding as a jar:

[org.openhab.binding.snapshot-1.8.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab/files/69742/org.openhab.binding.snapshot-1.8.0-SNAPSHOT.jar.zip)

Will continue to work on a pull request.

**Comment by PolishBen** [comment]
I pushed the code to https://github.com/PolishBen/openhab and would be grateful for any comments/suggestion/feedback.

**Comment by NCO3** [comment]
Thanks, @PolishBen
Could you please also share a sitemap example entry?

**Comment by PolishBen** [comment]
Done

**Comment by NCO3** [comment]
Thanks.
Yes, it's trivial ;-)
What I meant was an example how to implement the snapshot view into the sitemap.
like:
Webview url="/weather?locationId=home&layout=example&iconset=colorful" height=7

Sorry, if this is trivial again... ;-)

**Comment by PolishBen** [comment]
doh! OK sorry yes I see what you mean.  Yes just do Webview url="/snapshot".  I will check my sitemap file when I get home tonight and update the wiki with an example.

**Comment by NCO3** [comment]
Thanks! I Appreciate your help.
Your implementation is much more straight forward than my workaround. ;-)

**Comment by PolishBen** [comment]
I updated the wiki page with a full example for the sitemap.  Let me know how you get on.

**Comment by zacofany** [comment]
Hi PolishBen,
I've tried your binding and I have 3 things:

1.
I'm using satel binding. After some time of using your snapshot, satel stops work with this bunch of messages and I think it's connected somehow to your binding:

2015-12-26 10:47:54.258 [INFO ] [o.o.b.s.i.protocol.Ethm1Module] - Connecting to ETHM-1 module at 192.168.1.191:7094
2015-12-26 10:47:54.261 [ERROR] [o.o.b.s.i.protocol.Ethm1Module] - IO error occurred during connecting socket
java.net.SocketException: Too many open files
        at java.net.Socket.createImpl(Socket.java:460) ~[na:1.8.0]
        at java.net.Socket.connect(Socket.java:587) ~[na:1.8.0]
        at org.openhab.binding.satel.internal.protocol.Ethm1Module.connect(Ethm1Module.java:69) ~[bundlefile:na]
        at org.openhab.binding.satel.internal.protocol.SatelModule.communicationLoop(SatelModule.java:345) [bundlefile:na]
        at org.openhab.binding.satel.internal.protocol.SatelModule.access$1(SatelModule.java:329) [bundlefile:na]
        at org.openhab.binding.satel.internal.protocol.SatelModule$CommunicationWatchdog$2.run(SatelModule.java:442) [bundlefile:na]
        at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
2015-12-26 10:48:04.000 [ERROR] [.o.m.c.i.folder.FolderObserver] - An unexpected exception has occured
java.lang.NullPointerException: null
        at org.openhab.model.core.internal.folder.FolderObserver.checkFolder(FolderObserver.java:127) ~[na:na]
        at org.openhab.model.core.internal.folder.FolderObserver.run(FolderObserver.java:99) ~[na:na]
2015-12-26 10:48:04.258 [INFO ] [o.o.b.s.i.protocol.Ethm1Module] - Connecting to ETHM-1 module at 192.168.1.191:7094
2015-12-26 10:48:04.261 [ERROR] [o.o.b.s.i.protocol.Ethm1Module] - IO error occurred during connecting socket
java.net.SocketException: Too many open files

2. Few times something went wrong and I was flooded with messages like:
2015-12-26 10:55:17.154 [WARN ] [.snaphsot2.SnapshotFileManager] - Error attempting to delete file: /media/nas/linked/cameras/FI9821W_00626E4F326A/snap/Schedule_20151225-161014.jpg

3. I'm using Foscam cameras (3x FI9821W v2 and 1xFI9826W). These cameras has ability to take snapshots depending on schedule and also when alarm (due to motion detection) occurs. Then snapshots can be send via FTP to some location where openhab is running. 
These cameras has also the following address structure to get to the current snapshot instantly:

http://ip address:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=admin&pwd=xxx

This however doesn't work if I put it instead of Image label="Camera" url=" "http://admin:12345@192.168.1.5/Streaming/channels/1/picture"  ref$ as it is in your example.
However it works with Webview.

More information about foscam fetching snapshots (for HD cameras) is here http://foscam.us/forum/how-to-fetch-snapshots-and-mjpeg-stream-on-hd-cameras-t4328.html

Cherrs

**Comment by PolishBen** [comment]
Cześć Zacofany :-)

Sorry for the long delay in replying, have been offline a lot over the holiday season.

1. I don't know what this is - not sure if it's a problem with my binding, theirs, or due to a combination of the bindings but I have a few suggestions - can you test and let me know please?
1.1 Have you configured the binding to allow a large number of snapshots? i.e. more than a few dozen?  If so, does the problem go away when you reduce the number?
1.2 Can you test to see which linux process is opening all these files as per this thread http://askubuntu.com/questions/181215/too-many-open-files-how-to-find-the-culprit ?
If it just says it's java / OpenHab can you test with one of the bindings turned off to find the culprit?
1.3 Can you experiment with changing the "ulimit" as mentioned in that thread?

2. Yes - I get that too - in future I will downgrade this from "warning" to "debug" to not flood the log file.  To turn warnings off you can just modify your logback.xml file and change the threshold level to WARN.  See the Debugging section at https://github.com/openhab/openhab/wiki/Snapshot-Binding for the syntax.
Having said that, not sure why these messages sometimes appear to start with so I will investigate it one day anyway....

3. My example was just a sample using Hikvision.  Also I had a copy/paste error in my example with "ref$" which should be deleted.  The URL should just be the URL that works for you in your browser, so in your case change it to be http://ip address:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=admin&pwd=xxx
I have added your sample URL to the wiki page - thanks for the info.

**Comment by jefsmk** [comment]
Hi,

Trying to get this binding running and am having a tough time with configuring the HTML files in the snapshot-resources folder.  index.html is pretty simple, but not sure what file.html and group.html are looking for?  Can someone clarify what edits are required here?  PS -- Using Foscam.  Thanks!

**Comment by PolishBen** [comment]
Hi

Are you using [these example html files](https://drive.google.com/file/d/0B3zmi0FWXByrT1VzTWJ6N3p0a3M/view?usp=sharing) as provided on the [wiki page](https://github.com/PolishBen/openhab)? 

If you set the logging to debug (as described on the wiki page) you should get more detailed messages about what the binding is doing.

Let me know how you get on - am happy to help.

**Comment by jefsmk** [comment]
Thanks, yes I'm using the example html files.  And I did enable logging as described. My logback.xml file:
```
	 <appender name="SNAPSHOT" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>${openhab.logdir:-logs}/snapshot.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>logs/snapshot-%d{yyyy-ww}.log.zip</fileNamePattern>
            <maxHistory>30</maxHistory>
        </rollingPolicy>
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%-30.30logger{36}:%-4line]- %msg%n</pattern>
        </encoder>
    </appender>  

    <logger name="org.openhab.binding.snapshot" level="DEBUG" additivity="false">
        <appender-ref ref="SNAPSHOT" />
    </logger>
```
although I'm not seeing any output in my snapshot.log file.

I downloaded the add-on from a link above (https://github.com/openhab/openhab/files/69742/org.openhab.binding.snapshot-1.8.0-SNAPSHOT.jar.zip), and renamed the zip file to create the .jar file.  Is this correct?  I have never installed an addon using that method.

**Comment by PolishBen** [comment]
I can't remember if there's a good reason for me uploading that as a zip or not - but yes, it's really a jar so correcting the extension and putting it in the addons directory is the way to go.

If you add a regular logger do you see any output in the main openhab.log file?

Are you seeing your OfficeCam item get updated when snapshots arrive?

**Comment by jefsmk** [comment]
No, I'm not seeing any updates.  The only things I see any any logs related to this binding is in openhab.log, and shown below:

`15:45:04.133 [DEBUG] [b.s.internal.SnapshotActivator:17   ] - Snapshot binding has been started.
15:45:04.156 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'OfficeCam (Type=DateTimeItem, State=Uninitialized)' with 'SnapshotGenericBindingProvider' reader.
15:45:04.183 [DEBUG] [SnapshotGenericBindingProvider:37   ] - Item validation OK
15:45:04.198 [ERROR] [i.internal.GenericItemProvider:350  ] - Binding configuration of type 'snapshot' of item ‘OfficeCam‘ could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: No binding config found for item: OfficeCam`

I just don't get it!  Thanks for helping me with this, really hoping I can get this working.

**Comment by PolishBen** [comment]
ah OK so it can't understand your OfficeCam config.  What does your items file entry look like for OfficeCam?

**Comment by jefsmk** [comment]
I probaby should of started with this ;) ...

`DateTime OfficeCam "Last Snapshot [%1$td/%1$tm/%1$tY %1$tT %1$tZ]" <calendar> { snapshot="path=E:\Dropbox\Personal\House\camera-ftp\office\FI9831P_00626E609B72\snap;maxFiles=50" }`

I've looked at it a hundred times, and it looks right to me.  And the path is correct.  The only realy difference is i'm on an windows box.

**Comment by PolishBen** [comment]
does it make a difference if you use forward slashes instead of back slashes on that path?

**Comment by jefsmk** [comment]
Sure does!  Forward slashes including the trailing slash did it!  Thanks so much.  It all looks pretty good.  Any idea why the the group title is showing like below?  The ${timestamp} is a link that works and brings up the pictures from that group.  

Office Camera
58 snapshot(s) found in 13 group(s)
${timestamp} 

Thanks soooo much for all the help!

**Comment by PolishBen** [comment]
Try this in your group.html file instead:

```
<li>
  <a href="/snapshot?name=${itemName}&action=list&size=600:300&group=${groupIndex}">
  <img width="500" height="300" src="/snapshot?name=${itemName}&action=snapshot&size=500:300&group=${groupIndex}">
  </a>
</li>
```

**Comment by jefsmk** [comment]
Yup, that did it.  And I see that when new files are added, this triggers the processing to delete files over maxfiles.  Looks like it's working perfect.  Thanks.  

Just wish I could edit the html files and preview without having to restart OH because of the locked file.  But that's another issue I suppose.

Thanks again.

**Comment by PolishBen** [comment]
ok great.  I don't have locking issues but at least you've got it working

**Comment by jefsmk** [comment]
So, had this working great under a Windows box, but now trying to get it re-setup under Ubuntu (I can't just leave well enough alone!).  Can't figure out why I'm seeing:

HTTP ERROR 404
Problem accessing /snapshot. Reason:
    ProxyServlet: /snapshot

My item file:
`DateTime dteOfficeCamSnapped "Last Snapshot [%1$td/%1$tm/%1$tY %1$tT %1$tZ]" <calendar> (gFoscamSettings){ snapshot="path=/srv/ftp/cameras/office/FI9831P_00626E609B72/snap;maxFiles=50" }`

I don't think it's an Apache thing, as I granted it permission to view the snapshot directory.  Still can't figure out how to view the logs for this binding.

Any ideas??

**Comment by FriedCircuits** [comment]
Great binding! Just was I was looking for.

Is there away to get the ${timestamp} variable working for the template? I could really use this.  I am switching from emailing myself images to having this binding manage my cameras. 
Thanks.

**Comment by SecurityAddicted** [comment]
Hi all,
Any chance this binding will be ported to Openhab2? I tried to install it but I'm getting the following errors into openhab.log:
```
2017-03-20 08:53:36.653 [ERROR] [org.openhab.binding.snapshot2       ] - [org.openhab.binding.snaphsot2(182)] bind method [addBindingProvider] not found; Component will fail
2017-03-20 08:53:36.655 [ERROR] [org.openhab.binding.snapshot2       ] - [org.openhab.binding.snaphsot2(182)] bind method [addBindingProvider] not found; Component will fail
2017-03-20 08:53:36.728 [ERROR] [org.openhab.binding.snapshot2       ] - [org.openhab.binding.snaphsot2(182)] bind method [addBindingProvider] not found
2017-03-20 08:53:36.733 [ERROR] [org.openhab.binding.snapshot2       ] - [org.openhab.binding.snaphsot2(182)] unbind method [removeBindingProvider] not found; Component will fail
2017-03-20 08:53:36.734 [ERROR] [org.openhab.binding.snapshot2       ] - [org.openhab.binding.snaphsot2(182)] unbind method [removeBindingProvider] not found
2017-03-20 08:53:36.735 [ERROR] [org.openhab.binding.snapshot2       ] - [org.openhab.binding.snaphsot2(182)] bind method [addBindingProvider] not found
2017-03-20 08:53:36.735 [ERROR] [org.openhab.binding.snapshot2       ] - [org.openhab.binding.snaphsot2(182)] unbind method [removeBindingProvider] not found
```

**Comment by 9037568** [comment]
No updates on this in a while. @PolishBen are you still working on this?

**Comment by frodo37** [comment]
Good afternoon.
@PolishBen thanks you for snapshot binding! 
Neither can I understand the error:

Recent Activity
HTTP ERROR 403
Problem accessing /snapshot. Reason:
    Forbidden
________________________________________
Powered by Jetty://

OpenHab works with root privileges
Rights to the snapshot directory and snapshot-resources checked. Where can there be a problem?

p.s. OH1.8.3

**Comment by PolishBen** [comment]
Hi. No I've not been working on this recently nor am I able to.  I might get back to it in the future but I have no idea when so if somebody else wants to pick this up they'd be more than welcome to.

**Comment by 9037568** [comment]
Thanks.

Anyone else interested in taking this on?

**Comment by frodo37** [comment]
There might be a problem ".snaphsot2."?

![image](https://cloud.githubusercontent.com/assets/26698135/24629980/9fa2de24-18c3-11e7-8d1c-95dd8ea197e1.png)
