### ISSUE TITLE
comfoair550 - outofoffice vs. automatic level

### ISSUE THREAD

**Issue by leutholl** [openhab/openhab1-addons#3707]
Hi.
The comfoair binding is working perfectly for a 550. It even runs on RS232 if the CC Deluxe control panel is connect to RS485 and accepts commands from either side and updates the CC deluxe panel. I have a improvement about:
FAN_LEVEL {
        {
            key = "fan_level";
            data_type = DataTypeNumber.class;
            possible_values = new int[] { 0x01, 0x02, 0x03, 0x04 };
            change_command = 0x99;
            change_data_size = 1;
            change_data_pos = 0;
            change_affected = new String[] { "auto_mode", "incomming_fan",
                    "outgoing_fan" };
            read_command = 0xcd;
            read_reply_command = 0xce;
            read_reply_data_pos = new int[] { 8 };
        }
    },

according to http://www.see-solutions.de/sonstiges/Protokollbeschreibung_ComfoAir.pdf
the meaning of the values are different than the meaning described in the howto and samples:
The command bytes: 0x00 0x99 (Stufe setzen)
should use the following values and ranges
0x00 = Auto
0x01 = Abwesend
0x02 = niedrig / Stufe 1
0x03 = mittel / Stufe 2
0x04 = hoch / Stufe 3

0x01 to 0x04 is working, 0x01 also works but means out-of-office and not automatic (as wrongly described in the howto and in the samples) the auto-mode is 0x00 but this value is not accepted by the binding.
I suggest to accept 0x00 as a value and to correct the manual.

This might be a 550 specific thing in combination with the CC Deluxe which has timer programs, but it shouldn't harm the 350 users (they should just remove the 0x00 from the mapping)

Further improvements would be:
- show RPM off all fans
- show temperature of the CC Deluxe sensor
- show when the filter must be changed (as displayed by the CC Deluxe) instead of counting the weeks.
- accept PTY (pseudo terminals) on unix and not only TTY as a serial device. Many of us use a RS232 over ethernet solution on there is no simple solution to create real TTY as a virtual serial port. It would be even better to accept udp/tcp sockets to completely get rid of the serial port issues when using non-usb and non-mainboard RS232 ports. using a udp/tcp port the raw character output writer could be used and this would be enough to make it RS232 on the far side using the cheap RS232 over udp/tcp devices. Note that such devices are configurable over the webpage for settings such as baudrate etc...
  I tried to use socat under unix/osx to create a virtual serial port but this only creates a PTY which is not accepted as a TTY by java.
##

**Comment by bechte** [comment]
Well the 0x00 level indeed claims to set the Fan Level to auto, but this only works with the CC-Ease controlled times. These cannot be changed by the PC controlled version via the serial interface, therefore, one might state, that setting the fan level to auto is not a valid operation.

Anyway, one might to reset the Fan Level to Auto mode before disconnecting the serial connection. This is where I also believe 0x00 should be accepted as valid operation.

The other improvements are valid, but still I would recommend to file them in separate issue in order to keep track of them individually.

**Comment by 9037568** [comment]
This repository is closed to new code, so not going to happen here...
