### ISSUE TITLE
rrd4j does not persist during the night (Time Cron bug?)

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab1-addons#3803]
I have the weirdest issue...

For some reason, some (not all) of the items that I have configured to persist are not persisted during the night.

It usually stops working sometime between midnight and 1 am.
It resumes to work around 5-6 am.

I have noticed it because the graphs show strange straigth lines at night.
I have confirmed the problem by taking a look at the persisted  values through Habmin. There is a period in which some of my items are not persisted.

I use openHAB 1.8.
It may be (or not) related to another issue I have with Time cron expressions not executing at the right time. I have the feeling that nothing related to Time Cron is reliable at all.

These are some of the items that are not persisted as expected:

Strategies 
{
    everyMinute:    "0 */1 \* \* \* ?"
}

nbTempComedor:          strategy = everyMinute
nbTempHab1:                 strategy = everyMinute  
nbSolAzimut:                strategy = everyMinute
nbSolElevacion:         strategy = everyMinute

The reason I think it is related to Time Cron is that the items that fail to persist are the items that are designed to be persisted at regular intervals configured with Time Cron.

Is there some kind of big bug with Time Cron or is it just me???
##

**Comment by steve-bate** [comment]
> Is there some kind of big bug with Time Cron or is it just me???

You may get more feedback by discussing this at the [community forum](https://community.openhab.org/). Please update this issue once you have more information. Thanks.

**Comment by sercasyr** [comment]
Is it a known bug?
Is there a on going topic about this in the forum?

**Comment by sercasyr** [comment]
I can give more information.
I have other items that don't update correctly. And not only at night.

If I don't use "everyUpdate, everyMinute" instead of "everyMinute", they don't persist at all.

Maybe it is just me, but Time-Cron persistence isn't reliable in my system.

**Comment by teichsta** [comment]
> Is it a known bug?

no

> Is there a on going topic about this in the forum?

i don't think so … would be great if you discuss your problem there since not everybody scans through this issue list.

**Comment by cvdenzen** [comment]
Try to change:
everyMinute: "0 */1 * * * ?" into
everyMinute: "0 * * * * ?"
