### ISSUE TITLE
binding.knx-1.8.jar no tcp connection to eibd

### ISSUE THREAD

**Issue by siri69de** [openhab/openhab1-addons#3851]
Hi,

I get no connection to eibd
check with wireshark on the openhab server
when knx.type tunnel is set a UDP connection to port 6720, but eibd seems to listen on tcp port 6720.
when knx.type route is set, there is no udp/tcp connection to the destination ip address. 
bug/config?

Try with WIndows 7 & Oracle JRE 8u66
but also with Debian 8.2 & Oracle JRE 8.66 i get no connection

by
Siri
##

**Comment by lewie** [comment]
Hi @siri69de,

in openHAB for knxd/eibd set typically: 
knx:type=ROUTER
knx:port=6720

Other parameters leave without config!
They find each other by default multicast IP address 224.0.23.12 then.

If this doesn't work, please post your knxd/eibd configuration (IP-Router or useb or serial) and parameters.

Rgds
Helmut

**Comment by hmerk** [comment]
@siri69de did this solve your issue so it can be closed then ?
