### ISSUE TITLE
HTTP actions do not work with HTTPS and basic authentication

### ISSUE THREAD

**Issue by haumacher** [openhab/openhab1-addons#3978]
I learned from the code, that one can use basic authentication in HTTP actions by encoding the username and password into the URL:

```
sendHttpPostRequest("http://<user>:<password>@some.host.com/some/path)
```

Unfortunately, this does not seem to work with HTTPS, because the pattern extracting the credentials from the URL does not match:

```
public class HttpUtil {

    /** {@link Pattern} which matches the credentials out of an URL */
    private static final Pattern URL_CREDENTIALS_PATTERN = Pattern.compile("http://(.*?):(.*?)@.*");

    ....
}
```

Shouldn't this be fixed to something like `Pattern.compile("http(?:s)?://(.*?):(.*?)@.*")`?

With the current code, services that require HTTPS and basic auth cannot be used, right?
##

**Comment by steve-bate** [comment]
@haumacher Do you want to create a PR for this request? You can simplify the regular expression modification to `"https?://(.*?):(.*?)@.*"`. This will match the 's' 0 or 1 times. No need for the noncapturing group.

**Comment by 9037568** [comment]
HttpUtil.java no longer exists in OH1. It was part of the OH1 platform, which no longer exists post 1.8.x.

You should inquire if this feature is available in OH2.
