### ISSUE TITLE
[Request] LG Hombot/Roboking Binding

### ISSUE THREAD

**Issue by snickers2k** [openhab/openhab1-addons#3984]
Hey.
Would be really cool to have an LG Hombot/Roboking Binding.
Everything about it is listed here: http://www.roboter-forum.com/showthread.php?13718-HomBot-3-0-Guide-Alle-Infos-Alle-Links (German)
##

**Comment by mstormi** [comment]
I don't think we need a binding. HTTP binding will do.
I got my Hombot to work with it, and documented it [here](https://github.com/openhab/openhab/wiki/LG-Hombot)

**Comment by cribskip** [comment]
Please see https://community.openhab.org/t/lg-hombot-binding/51261
Please close

**Comment by 9037568** [comment]
Closing in favor of the in-progress [OH2 binding](https://github.com/openhab/openhab2-addons/pull/4181).
