### ISSUE TITLE
CUL network connection does not get restarted on broken connection

### ISSUE THREAD

**Issue by JSurf** [openhab/openhab1-addons#4035]
I recently found a new issue with my networked cul. It seems the connection does not get recovered when the networked cul is not reachable. I'm slowly moving services to another raspberry and restart ser2net quite often. Then i get "broken pipe" errors and openhab does not seem to restart/recover the connection after the remote cul is up again. 

I only use outgoing calls via culintertechno binding. I see that there is some code to recover from errors in processNextLine but this may never be used because i'm only sending commands. "writeMessage" does not handle restart of connections after send errors

Might be related to #1328
##

**Comment by teichsta** [comment]
thanks for sharing this @JSurf. Any chance to create a PR with the according fix?

**Comment by JSurf** [comment]
I hoped that @tarioch would have a look since is/was refactoring the cul io binding, So i would at least wait until #2358 is merged. Could have a look then

**Comment by Gugiman** [comment]
Can confirm this bug.

I'm also using ser2net and have to restart openhab everytime I restart ser2net.
So I think any other interruption would break the connection to the CUL permanently.

**Comment by dereulenspiegel** [comment]
I started to implement a fix for this issue (https://github.com/dereulenspiegel/openhab/tree/cun). This is currently in testing in my environment. Once it proves stable, I will create a Pull Request.

**Comment by watou** [comment]
@dereulenspiegel Please have a look at the solution @tarioch implemented in #3885 and was recently merged.

**Comment by dereulenspiegel** [comment]
These changes didn't solve network connectivity issues for CUN devices. But my changes are based on #3885 . So there shouldn't be a problem.

**Comment by watou** [comment]
Excellent news, @dereulenspiegel!

**Comment by dereulenspiegel** [comment]
I submitted my [Pull Request](https://github.com/openhab/openhab/pull/4359). This has been running stable now for about a week with reflashed Max!Cube (running a-culfw) and a CULLite v4.

**Comment by JSurf** [comment]
Thanks for your work! I will test this fix in my environment

**Comment by JSurf** [comment]
Tried with only the cul io binding changed against the version from this pull request, but this broke the intertechno binding completely. Could not see errors in the logs but could not switch any items anymore. Do i need to install other updated bindings to make this work ?

**Comment by 9037568** [comment]
@dereulenspiegel , any chance to review the comments from @JSurf ?

**Comment by JSurf** [comment]
I had a chance to test the latest version of pull request again against my setup (cul connected to ser2net). 

It seems to work fine and recovers great from ser2net restarts. So if the pull request gets merged this issue can be closed

**Comment by 9037568** [comment]
Should be fixed by the merged PR.
