### ISSUE TITLE
[DSCAlarm Binding] Problem with configuration parameter 'deviceType'

### ISSUE THREAD

**Issue by RSStephens** [openhab/openhab1-addons#4158]
The DSC Alarm binding is not able to handle the configuration parameter 'deviceType'.  Whenever this parameter is populated in the configuration file the binding appears to freeze or not initialize.  I will look at this issue as soon as I can.
##

**Comment by RSStephens** [comment]
This issue has been fixed in PR #4208, but has not been merged yet.

**Comment by 9037568** [comment]
Fixed via merged PR.
