### ISSUE TITLE
Transform support for Modbus Binding

### ISSUE THREAD

**Issue by DCandE** [openhab/openhab1-addons#4204]
As noted in this post [Modbus Transform](https://community.openhab.org/t/modbus-transform/8868) I would like to be able to use the transformation service with the modbus binding.
##

**Comment by ssalonen** [comment]
I now published experimental version implementing transformation support in the community forums: https://community.openhab.org/t/modbus-support-for-transformations-roller-shutter-items-read-only-items-write-only-items-and-others/21500

**Comment by paulbeech** [comment]
Hi ssalonen,
I have used the new version 1.10.0-SNAPSHOT with
` Number A1  "Temperature 1 [%03.2f]" <temperature> { modbus="<[A1:6:transformation=JS(div16.js)]" }`
and it works great for me.

I am only testing the operation at the moment, so no stress testing yet, but great work.

Thanks for the update, it was timed well!

**Comment by 9037568** [comment]
Closed via merged PR.
