### ISSUE TITLE
[WeMo] Feature Request for Wemo Crockpot

### ISSUE THREAD

**Issue by Fcases** [openhab/openhab1-addons#4275]
## Expected Behavior

should be able to get statuses.
## Current Behavior

missing types in jar
## Possible Solution

https://github.com/petrklus/crockpot/blob/master/main.py

or 
https://github.com/tierneykev/SmartThings/blob/master/devicetypes/tierneykev/wemo-crockpot.src/wemo-crockpot.groovy

or 
http://pastebin.com/KMvXAsHH

{ ip: '192.168.0.69',
  port: '49153',
  deviceType: 'urn:Belkin:device:crockpot:1',
  friendlyName: 'Crock-Pot',
  manufacturer: 'Belkin International Inc.',

  modelDescription: 'Belkin Plugin Socket 1.0',
  modelName: 'Socket',
  modelNumber: '1.0',
  modelURL: 'http://www.belkin.com/plugin/',
  serialNumber: '221409S0000319',
  UDN: 'uuid:Crockpot-1_0-221409S0000319',
  UPC: '123456789',
  macAddress: 'B4750E7160D4',
  firmwareVersion: 'WeMo_WW_2.00.7179.PVT',
  iconVersion: '1|49153',
  binaryState: '1',
  iconList: { icon: [ [Object] ] },
  serviceList:

  presentationURL: '/pluginpres.html' }
### 

{ host: '192.168.0.69',
  port: '49153',
  path: '/upnp/control/basicevent1',
   SOAPACTION: '"urn:Belkin:service:basicevent:1#GetCrockpotState"',

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
 <s:Body>
  <u:GetCrockpotState xmlns:u="urn:Belkin:service:basicevent:1">
  /u:GetCrockpotState
 /s:Body
/s:Envelope
##

**Comment by hmerk** [comment]
Thanks for this feature request. I will think about implementation.

**Comment by aaronincincy** [comment]
Not sure if this is the place, or if you'd rather have it tracked as a separate item, but I'd love to be able to control the wemo humidifier as well.

Here's some information I was able to find about the api.

https://community.smartthings.com/t/holmes-wemo-humidifier/19482

specifically this post:
https://community.smartthings.com/t/holmes-wemo-humidifier/19482/4


I'm relatively new to openhab so I don't know how you would handle it, but ideally you would be able to access all of the attributes.

**Comment by hmerk** [comment]
I had a quick look at the references you both posted and think, it is feasable to add support for both devices, but this will take some time as those are not available here in Germany. So I will have to code blind.
Furthermore, I have to decide wether to just add this for openHAb 2.0 or support both versions.
As I alreday decided to add support for the LED lights just for oh2, this probably will be the same for Crockpot and Humidifier.

**Comment by Fcases** [comment]
i coult vpn you to my crockpot if needed; ) just down burn the house down

**Comment by hmerk** [comment]
Hi @Fcases, please have a look at this post:
https://community.openhab.org/t/wemo-coffe-maker/12667/9

**Comment by hmerk** [comment]
Closing this issue as further discussion will be at
https://github.com/eclipse/smarthome/issues/3345
