### ISSUE TITLE
IEC 62056 - 21 Meter Binding: Support for L&G Ultraheat 2wR5 - multiple value strings

### ISSUE THREAD

**Issue by coyte** [openhab/openhab1-addons#4293]
I'm using the binding v 1.8.2 to communicate with a district heating meter from Landis & Gyr, using a IR-USB volkszaehler gizmo.

I get all data in and displayed in openhab except where the meter returns multiple values separated by a semicolon. I only get data until the semicolon
Example: 
DataSet: 6.8;0497.202;GJ - I just get 0497.202 { iec6205621meter="district_heating:6.8" }
DataSet: 9.4;100;C&085*C - I just get 100. { iec6205621meter="district_heating:9.4" }
In many cases the last item (like the GJ in my first example) is simply an indication of the unit for the value. But in my second example it is tuneable parameter for the heating of the house and I'd like to have the value reported.

Item config:
Number  flowtempmaxreturn   "Flow temperatuur in/uit [%.s]" { iec6205621meter="district_heating:9.4" }

Binding log:
2016-04-13 12:16:44 - DataSet: 9.4_01;100;C&085_C
2016-04-13 12:16:44 - Updateing item flowtempmaxreturn with OBIS code 9.4 and value 100

If you look at the structure of the data:
DataSet:id;val1;val2 
only val1 is assigned to an item, val2 is discarded.

A possible solution would be to create a flag to assign the datastring from the separator characher until EOL to an item, the parsing can be done in a rule.  
##

**Comment by kreutpet** [comment]
val2 is the unit value. 
so in above case this should represent Celsius
not sure if it makes sense to adapt the item configuration to also access the unit.
/kreutpet

**Comment by kreutpet** [comment]
i guess this could be closed

**Comment by coyte** [comment]
Think so too
