### ISSUE TITLE
[RFXCOM] Enhancement to allow use with Lighting4 4 port relay boards

### ISSUE THREAD

**Issue by sheppy99** [openhab/openhab1-addons#4352]
## Current Behavior

Only ON and OFF Types are supported commands for sending out in the LIGHTING 4 protocol of the RFXCOM Binding.
## Possible Solution

Add Number as an type to RFXComValueSelector.java
at or around line 72:

```
NUMBER("Number", NumberItem.class);
```

Add Number Type to RFXComLighting4Message.java at or around line 198

```
case NUMBER:
            if (type instanceof DecimalType) {
                commandId = ((DecimalType) type).intValue();
            } else {
                throw new RFXComException("Can't convert " + type + " to Command");
            }
            break;
```

Add to documentation:

Multi port relay item example

```
Number MultiportRelay { rfxcom=">123456.550:LIGHTING4.PT2262:Number" }
```

where 123456 is the 6 character address of the relay and 550 is the command length in milliseconds 

To send to the item in a rule needs to read something like this:

```
when Item something changed then
{    MultiportRelay.sendCommand(15)    }
end
```

The number in brackets represents the state you want the relays to be in. Each relay on the card is controlled by a binary bit with number "0" being all Off, number "15" being all On, number "1" being the first relay on, number "2" being the second relay on etc
## Context

It allows use the binding to be used with products such as this 
http://www.aliexpress.com/item/High-Quality-12V-4CH-Wireless-Remote-Control-Relay-Switch-4-Transceiver-with-Receiver-Compatible-with-2262/32383896424.html
## Your Environment

This is tested and working with Openhab V1.8.0, Raspberry Pi3, RFXCOM binding and external 433MHz USB Transceiver.

Unfortunately I can't understand how to get Eclipse / Local GIT / Remote GIT to combine my branches / pulls into something usable so I have copy and pasted the changes into here.
##

**Comment by martinvw** [comment]
I am currently working on some changes for OH2 lighting 4 and I do really like this idea, if I make the changes in OH2 and make them ready for a PR can you test them whether they work in your situation?

**Comment by sheppy99** [comment]
Hi Martin, currently I'm still on OH 1.8 so can't test the V2 binding on my live system, and due to range issues I've replaced this relay with an ESP8266. I do still have it though, so if I get time I can set up a test environment on OH2 and do a quick minimal test for you. 
Once OH2 supports login security I'll upgrade, but until then I'm sticking with 1.8

**Comment by martinvw** [comment]
@sheppy99 I made a new jar for the binding with support for sending and receiving command id's.

See: https://github.com/openhab/openhab2-addons/pull/2045

Offtopic are you aware you can just put NGINX or something like that in front of it to provide security, I have NGINX providing SSL and login security. OR you can expose your items via openhab cloud which will also require a login to access.

**Comment by sheppy99** [comment]
Thanks, I'll give it a test next week. So far I've been experimenting with OH2 on my windows machine just to get familiar with it, I'll test this on my spare Pi 1.
I've found some info on NGIFX in the docs, so I'll take s look at that too. I run my pi's read only, so it's not straight forward to simply swap over

**Comment by sheppy99** [comment]
Further update, I have OpenHAB 2 installed and almost working. The runtime itself does work, but RFXCOM doesn't both using the V2 binding and also before that by copying your binding into the addons folder. Something to do with Felix isn't happy. Any idea what's wrong? I thought Felix was a cat on a UK cat food advert :-)

**Comment by martinvw** [comment]
Could you give some details about the exact error, I do not remember any error about a cat either :-)

**Comment by sheppy99** [comment]
Will do, probably in around 12 hours or so

**Comment by sheppy99** [comment]
With the binding is there anything else that needs doing other than telling openhab2 where to find it by listing the serial port in /etc/default/openhab2? It doesn't need a services file?

**Comment by martinvw** [comment]
In the binding for oh2 you can add the device via the paper ui or ( depending on your os)  it might be automaticly discovered. There is on device with a more generic name you should use that one when adding it manually. If you added it other devices are discovered or can be added via the ui

**Comment by sheppy99** [comment]
I've got RFXCOM working with the released binding, and everything seems to be working. How can I change to your binding without having to reconfigure anything? It's taken several hours to get it all working so I'd rather not break anything if possible, although I will take an image backup first just in case.
