### ISSUE TITLE
CalDav command separator enhancements

### ISSUE THREAD

**Issue by reyem** [openhab/openhab1-addons#4355]
## Expected Behavior

As end user I want to enter commands in the command calendar via any CalDav client, being able to read the entered commands for review for finding mistakes in case of non triggered events.
## Current Behavior

Currently the CalDav command add-on supports multiple commands in the description of a calendar event, separated by "newline". However, "newline" is a bit fragile in webdav, as it can be entered in multiple ways depending on CalDav client. On Mac OS X Calendar (iCal) one can enter a newline with:
- Option+Return: Resuts in an expected backslash( \ ) character n ( n ) sequence.
- Control+Return: Results in a Unicode line separator ( U+2028 ), which is currently not recognized as newline in the add-on: http://www.fileformat.info/info/unicode/char/2028/index.htm

If an end user checks the calendar entries for mistakes if commands are not executed, he/she will not be able to see the (wrong) newline in the description in the CalDav client.
## Possible Solution

I would like to see following enhancements:
- support unicode line separators as command separators
- add another command separator, for example semicolon ( ; ) and ignore whitespaces. This would allow even having multiple commands on one line and the line separator would not matter.
## Steps to Reproduce (for bugs)
1. Create a calendar event with 2 commands in Apple iCal by separating the commands with a unicode line separator ( press Control+Return )
2. Check the log file ( using the "less" command to view it will show the unicode newline character ). It contains:
   2016-05-05 23:11:00.006 [ERROR] [g.openhab.io.caldav.EventUtils:98  ]- invalid format for line: BEGIN:RGBControllerAll:0<U+2028>END:RGBControllerAll:100
## Context

I was affected by this when first trying the calDav add-on, not being aware of multiple ways to enter newlines in iCal.
https://community.openhab.org/t/events-with-multi-line-in-description-does-not-work/10379
## Your Environment

- Version used: openhab 1.8.1, caldav io and command 1.8.2
- Environment name and version: CalDav Server: Sinology DSM 6.0, CalDav client Apple Calendar ( iCal ) Version 8.0
- Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Client OS: Mac OS X 10.11.4 El Capitan. Openhab server OS: Linux raspberrypi 4.1.17-v7+
##

**Comment by 9037568** [comment]
I have a code change for allowing the Unicode line separator character U+2028, but I'm having trouble testing it. It appears that either Google is mangling the character when I enter it in the Google Calendar web UI, or it's not being read/written correctly by ICal/OH.

@reyem : Here are the test jars. Please try them out. (Note: just rename the file to replace the .zip extension with .jar. Github stupidly won't accept .jar.)

[org.openhab.io.caldav-1.10.0-SNAPSHOT.zip](https://github.com/openhab/openhab1-addons/files/967350/org.openhab.io.caldav-1.10.0-SNAPSHOT.zip)
[org.openhab.binding.caldav-command-1.10.0-SNAPSHOT.zip](https://github.com/openhab/openhab1-addons/files/967352/org.openhab.binding.caldav-command-1.10.0-SNAPSHOT.zip)

**Comment by reyem** [comment]
thank you for the fix. Its a while since I played with the binding. So in the meantime I switched to OH2. I did not install the CalDav binding yet in OH2. Once I come to this point again (probably next couple of weeks I want to do some calendar based automation again anyways), I will try to test this.

btw. Any plans to migrate the CalDav binding to OH2?

**Comment by 9037568** [comment]
Found a few errors in my implementation, so here are updated jars.

[org.openhab.binding.caldav-command-1.10.0-SNAPSHOT.zip](https://github.com/openhab/openhab1-addons/files/980639/org.openhab.binding.caldav-command-1.10.0-SNAPSHOT.zip)
[org.openhab.io.caldav-1.10.0-SNAPSHOT.zip](https://github.com/openhab/openhab1-addons/files/980640/org.openhab.io.caldav-1.10.0-SNAPSHOT.zip)

PR will follow shortly.

**Comment by 9037568** [comment]
Closed via merged PR.
