### ISSUE TITLE
[request] Modbus Binding write and read not contiguous addresses.

### ISSUE THREAD

**Issue by tomtom30** [openhab/openhab1-addons#4407]
Hi,
is it possible to add fonctionnality to read one address in one slave ( ex : address 4092 on slave1 ) and write another one ( ex: address 8196 on slave2 ) in the same item.

ex : Switch MySwitch "My Modbus Switch" (ALL) {modbus=**"slave1:<6:slave2>7"**}

In fact in API , addresses are not always contiguous so we need to use two items to fix it.

Thx for reply
Thomas
##

**Comment by ssalonen** [comment]
This is now possible, see the discussion here:

https://community.openhab.org/t/modbus-support-for-transformations-roller-shutter-items-read-only-items-write-only-items-and-others/21500

and the PR #5098 having the experimental version

Best,
Sami

**Comment by 9037568** [comment]
Closed via merged PR.
