### ISSUE TITLE
[Dropbox] configuration within configuration

### ISSUE THREAD

**Issue by slaboure** [openhab/openhab1-addons#4415]
## Expected Behavior

I have an existing configuration stored in Dropbox. Upon re-installing OpenHAB from scratch, configuring Dropbox, it should re-download configuration from Dropbox and apply it to local setup
## Current Behavior

Instead, a configuration folder gets created as a sub-folder of the configuration folder. The sub-folder _is_ the content of Dropbox while the main configuration folder is just the one that's part of the default setup. Dropbox should have overriden it instead. Users have similarly complained about it in the forums in the past: https://community.openhab.org/t/dropbox-sync-folder/7878
## Possible Solution

Probably toy around with ln -s
## Steps to Reproduce (for bugs)

see above
## Context

restore of OpenHAB setup from Dropbox
In my Applications/openHAB folder I have sub-folders etc and configurations
## Your Environment

Odroid XU4
OpenHAB 1.8.3 debian package APT
Oracle Java 8
Ubuntu Server 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
##

**Comment by 9037568** [comment]
Please provide your configuration (sitemap file, items file, rules files if any, and openhab.cfg).

**Comment by slaboure** [comment]
Here you go..

[Archive.zip](https://github.com/openhab/openhab/files/334735/Archive.zip)

**Comment by slaboure** [comment]
Am I supposed to do anything else? I'm asking as I see the status is still set to "awaiting-feedback" and I'm unclear whether I'm the one is supposed to change the status of the report. LMK. thanks.

**Comment by 9037568** [comment]
Since the dropbox v1 api is now retired, I'm going to say it's too late to do anything with this.
