### ISSUE TITLE
[rfxcom] Controlling Somfy blinds doesn't work with the rollershutter item in OH 1.7.1

### ISSUE THREAD

**Issue by svenschaefer74** [openhab/openhab1-addons#4624]
I'm encountering this issue in OH 1.7.1 but I'm sure it's also existing in the more current 1.8.x branch.

Rollershutter items work perfectly well with roller shutters but not with (venetian) blinds. With Somfy blinds a 'short' UP or DOWN command just changes the angle whereas a longer press (ca. 2sec) is necessary to make them moving UP or DOWN.
## Current Behavior

The current binding only executes a short UP command which makes it impossible to open or close the blinds. The RFXCOM firmware supports this longer command and I can control the blinds with the RFXCom Windows application. There is a [workaround](https://community.openhab.org/t/please-help-with-rfxcom-binding-and-somfy-blinds/11605) available using commandline tools but this seems to be an unncessary complexity.
## Solution

I had a look at [RFXComRfyMessage.java](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComRfyMessage.java). There just seems to be a small gap where only the Shutter part of the command set can be executed by OH but I've seen in the binding sources that there are already the necessary commands prepared in the enumeration. As a first step it needs to be necessary to add Blinds to the RFXComValueSelector type. 

Unfortunately I've no experience with the Openhab development. It would be great if someone could judge the necessary effort and in best case could probably supply a solution.
## Your Environment

- I'm using OH 1.7.1 on an RPI
##

**Comment by martinvw** [comment]
Can you please add logging of the command which is received by the rfxcom binding when you control the blinds with the remote. 

This makes it easier to estimate the impact.

How to enable that logging is described at https://github.com/openhab/openhab/wiki/RFXCOM-Binding

**Comment by svenschaefer74** [comment]
I also do have a [discussion](https://community.openhab.org/t/please-help-with-rfxcom-binding-and-somfy-blinds/11605/4) in the OH Community about this topic. I already implemented the necessary changes and do currently the testing in my home environment. As soon as I am confident with the functionality and stability I would issue a pull request.

**Comment by hakan42** [comment]
Hi @svenschaefer74 , are you satisfied with the functionality? I am really really looking forward to control my shutters 😄
