### ISSUE TITLE
[lgtv] Feature Request for pre-2011 LG TV binding

### ISSUE THREAD

**Issue by kedarbhise** [openhab/openhab1-addons#4640]
## Description

This request is for a binding for older LG Smart TVs that support the HDCP protocol over port 8080.

The current lgtv binding supports LG TVs that support UDAP protocol, typically released after 2011.
## Expected Behavior

A binding to connect to older LG Smart TVs that support HDCP protocol.
## Current Behavior

Current LG TV binding supports TVs 2012 and newer which use the UDAP protocol. No support for older LG TVs
## Possible Solution

A working implementation of this protocol (in Ruby) can be found at:
https://github.com/dreamcat4/lgremote

I tried using the commands from the Ruby program directly on the command line using the "curl" command, and they work as expected.

A simple php script to send remote commands to such TVs can be found at:
http://www.domoticaforum.eu/viewtopic.php?f=28&t=9305&start=15#p68185

A brief description of the protocol and some sample transactions can be found at:
http://www.cometvisu.org/wiki/LGconnectd

Full keymap of commands can be found at:
https://gist.github.com/dreamcat4/1477497
## Steps to Reproduce (for bugs)

None, as this is a feature request.
## Context

Attempting to control an older LGTV via OpenHAB. I think this should be doable as a remote control for Android is available, and also sample programs as listed in the "Possible Solution" are available. My main use cases are "Sleep" and "Leaving Home" scenes where all multimedia devices are powered off.
## Your Environment

- Version used: OpenHAB 1.8.3, Addons 1.8.3, Demo setup 1.8.3
- Environment name and version: Raspberry Pi 3 Model B, Java 8, LGTV LV3730-TD
- Operating System and version: Raspbian Jessie, LGTV HDCP Version 1.0, LGTV Service Version dtv_wifirc1.0
##

**Comment by joshuaherman** [comment]
Might want to contact the Android app dev and ask for guidance on how you can help.

**Comment by kedarbhise** [comment]
The pre-2011 LG TV (LGTV LV3730-TD) mentioned in the issue above died sometime back. As such, this issue is no longer current for me.
@9037568 - I am OK to mark this as closed.
