### ISSUE TITLE
[denon] Marantz M-CR611 - not updating states of items

### ISSUE THREAD

**Issue by rapiertg** [openhab/openhab1-addons#4777]
I have configured Marantz in this way both on OH 1.8 and current snapshot of 2.0:
```
avr2000.host=192.168.1.26
avr2000.update=http
refresh=2000
```
And everything works in one direction. Eg. Commands are executed on the device - but states of items are not send to openhab. I mean that if I turn it off with my remote, change Volume, Input or mute then the Input Web Interface are not reflected. It is also not showing current TRACK, ALBUM etc. This is weird as I can get these info by sending POST message to _http://192.168.1.26/goform/AppCommand.xml_:
```
<?xml version="1.0" encoding="utf-8"?>
<tx>
 <cmd id="1">GetVolumeLevel</cmd>
 <cmd id="1">GetMuteStatus</cmd>
 <cmd id="1">GetSourceStatus</cmd>
</tx>
```
and get:
```
<?xml version="1.0" encoding="utf-8" ?>
<rx>
<cmd>
<volume>-73.0</volume>
<disptype>ABSOLUTE</disptype>
<dispvalue>7</dispvalue>
</cmd>
<cmd>
<mute>off</mute>
</cmd>
<cmd>
<source>Internet Radio</source>
</cmd>
</rx>
```
Current playback info can be seen xml file in http://192.168.1.26/goform/formNetAudio_StatusXml.xml?ZoneName=MAIN+ZONE

Would it be possible to make this little device work both sides with denon binding?

**Comment by 9037568** [comment]
Can you provide a full debug log, @rapiertg ?

**Comment by sjcliffe** [comment]
I've recently purchased this model so would like to see this functionality too.

**Comment by sjcliffe** [comment]
Startup log:

2016-12-21 13:07:05.232 [DEBUG] [.denon.internal.DenonActivator] - Denon binding has been started.
2016-12-21 13:07:05.393 [DEBUG] [.i.DenonGenericBindingProvider] - denon:hifi item Hifi_Power bound to property PW
2016-12-21 13:07:05.395 [DEBUG] [.i.DenonGenericBindingProvider] - denon:hifi item Hifi_Mute bound to property MU
2016-12-21 13:07:05.396 [DEBUG] [.i.DenonGenericBindingProvider] - denon:hifi item Hifi_Volume bound to property MV
2016-12-21 13:07:05.398 [DEBUG] [.i.DenonGenericBindingProvider] - denon:hifi item Hifi_Input bound to property INPUT
2016-12-21 13:07:05.400 [DEBUG] [.i.DenonGenericBindingProvider] - denon:hifi item Hifi_Tuner bound to property SITUNER
2016-12-21 13:07:05.401 [DEBUG] [.i.DenonGenericBindingProvider] - denon:hifi item Hifi_CurrentTrack bound to property TRACK
2016-12-21 13:07:05.403 [DEBUG] [.i.DenonGenericBindingProvider] - denon:hifi item Hifi_CurrentArtist bound to property ARTIST
2016-12-21 13:07:05.404 [DEBUG] [.i.DenonGenericBindingProvider] - denon:hifi item Hifi_CurrentAlbum bound to property ALBUM
2016-12-21 13:07:05.429 [DEBUG] [.b.denon.internal.DenonBinding] - Denon all bindings changed
2016-12-21 13:07:05.440 [DEBUG] [.b.denon.internal.DenonBinding] - Denon binding updated
2016-12-21 13:07:05.468 [DEBUG] [.b.denon.internal.DenonBinding] - Denon receiver configured at 192.168.128.125
2016-12-21 13:07:06.711 [INFO ] [.service.AbstractActiveService] - HTTP Refresh Service has been started
2016-12-21 13:07:07.099 [DEBUG] [.denon.internal.DenonConnector] - Refreshing URL: http://192.168.128.125:80/goform/Deviceinfo.xml
2016-12-21 13:07:07.658 [DEBUG] [.denon.internal.DenonConnector] - Denon hifi zones: 1

Running tcpdump on my openhab server I can see the commands being sent but am not seeing any periodic polling for status. I'm using the default 5000 (5 seconds) so I would expect to see a request for http://192.168.128.125:80/goform/Deviceinfo.xml every 5 seconds.

**Comment by 9037568** [comment]
Please also include your denon configuration settings.

**Comment by 9037568** [comment]
It appears to me that the 5 second refresh only applies if the connection type is telnet (in spite of what the wiki page says). Maybe I'm missing something:
````
    public void connect() {
        if (connection.isTelnet()) {
            listener = new DenonListener(connection, new DenonUpdateReceivedCallback() {
````

No listener gets started if the connection type is http...

**Comment by rapiertg** [comment]
This is weird as config file states:

> # Optional, this sets the refresh interval (in milliseconds) for all instances 
> # if you're using the http connection method. Default = 5000 

Just to add some view I changed it to telnet:

```
#<instance>.<property>=value

# IP adress of the Denon receiver instance
avr2000.host=192.168.1.26

# Optional, set connection method for receiving updates. Can be http or telnet. 
# Denon receivers only support one concurrent telnet connection, so use http if 
# you have any other app using the telnet connection. Default = telnet
#avr2000.update=http

# Optional, this sets the refresh interval (in milliseconds) for all instances 
# if you're using the http connection method. Default = 5000 
refresh=2000
```



> 2016-12-21 18:17:36.471 [DEBUG] [org.openhab.binding.denon           ] - BundleEvent INSTALLED - org.openhab.binding.denon
> 2016-12-21 18:17:36.520 [DEBUG] [org.openhab.binding.denon           ] - BundleEvent RESOLVED - org.openhab.binding.denon
> 2016-12-21 18:17:36.597 [DEBUG] [org.openhab.binding.denon           ] - BundleEvent STARTING - org.openhab.binding.denon
> 2016-12-21 18:17:36.651 [DEBUG] [inding.denon.internal.DenonActivator] - Denon binding has been started.
> 2016-12-21 18:17:36.659 [DEBUG] [org.openhab.binding.denon           ] - ServiceEvent REGISTERED - {org.openhab.model.item.binding.BindingConfigReader, org.openhab.binding.denon.DenonBindingProvider}={component.name=org.openhab.binding.denon.genericbindingprovider, component.id=183, service.id=314, service.bundleid=204, service.scope=bundle} - org.openhab.binding.denon
> 2016-12-21 18:17:36.667 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzPower bound to property PW
> 2016-12-21 18:17:36.668 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzVolume bound to property MV
> 2016-12-21 18:17:36.669 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzMute bound to property MU
> 2016-12-21 18:17:36.670 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzCurrentTrack bound to property TRACK
> 2016-12-21 18:17:36.671 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzCurrentArtist bound to property ARTIST
> 2016-12-21 18:17:36.672 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzCurrentAlbum bound to property ALBUM
> 2016-12-21 18:17:36.672 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInput bound to property INPUT
> 2016-12-21 18:17:36.673 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputCD bound to property SICD
> 2016-12-21 18:17:36.674 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputUSBIPOD bound to property SIUSB/IPOD
> 2016-12-21 18:17:36.675 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputNet bound to property SISERVER
> 2016-12-21 18:17:36.675 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputSpotify bound to property SISPOTIFY
> 2016-12-21 18:17:36.676 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputTuner bound to property SITUNER
> 2016-12-21 18:17:36.677 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputDVD bound to property SIDVD
> 2016-12-21 18:17:36.677 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputBluray bound to property SIBD
> 2016-12-21 18:17:36.678 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputTV bound to property SITV
> 2016-12-21 18:17:36.679 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputSATCBL bound to property SISAT/CBL
> 2016-12-21 18:17:36.679 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputMplay bound to property SIMPLAY
> 2016-12-21 18:17:36.680 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputGame bound to property SIGAME
> 2016-12-21 18:17:36.681 [DEBUG] [internal.DenonGenericBindingProvider] - denon:avr2000 item MarantzInputAux1 bound to property SIANALOG1
> 2016-12-21 18:17:36.687 [DEBUG] [org.openhab.binding.denon           ] - ServiceEvent REGISTERED - {org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService}={event.topics=openhab/command/*, service.pid=org.openhab.denon, component.name=org.openhab.binding.denon.binding, component.id=182, service.id=316, service.bundleid=204, service.scope=bundle} - org.openhab.binding.denon
> 2016-12-21 18:17:36.705 [DEBUG] [.binding.denon.internal.DenonBinding] - Denon all bindings changed
> 2016-12-21 18:17:36.706 [DEBUG] [.binding.denon.internal.DenonBinding] - Denon binding updated
> 2016-12-21 18:17:36.708 [DEBUG] [org.openhab.binding.denon           ] - BundleEvent STARTED - org.openhab.binding.denon
> 2016-12-21 18:17:36.712 [DEBUG] [.binding.denon.internal.DenonBinding] - Denon receiver configured at 192.168.1.26
> 2016-12-21 18:17:36.717 [INFO ] [core.karaf.internal.FeatureInstaller] - Installed 'openhab-binding-denon1'
> 2016-12-21 18:17:36.832 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-persistence-jdbc-mysql1': No matching features for openhab-persistence-jdbc-mysql1/0.0.0
> 2016-12-21 18:17:36.918 [DEBUG] [inding.denon.internal.DenonConnector] - Refreshing URL: http://192.168.1.26:80/goform/Deviceinfo.xml
> 2016-12-21 18:17:37.106 [DEBUG] [inding.denon.internal.DenonConnector] - Denon avr2000 zones: 1
> 2016-12-21 18:17:37.319 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=316, bundle=204/mvn:org.openhab.binding/org.openhab.binding.denon/1.9.0-SNAPSHOT]: Unexpected problem updating configuration org.openhab.denon
> java.lang.NullPointerException
> 	at org.openhab.binding.denon.internal.DenonConnector.updateMainZone(DenonConnector.java:452)[204:org.openhab.binding.denon:1.9.0.201612210211]
> 	at org.openhab.binding.denon.internal.DenonConnector.refreshHttpProperties(DenonConnector.java:510)[204:org.openhab.binding.denon:1.9.0.201612210211]
> 	at org.openhab.binding.denon.internal.DenonConnector.updateState(DenonConnector.java:213)[204:org.openhab.binding.denon:1.9.0.201612210211]
> 	at org.openhab.binding.denon.internal.DenonConnector.getInitialState(DenonConnector.java:204)[204:org.openhab.binding.denon:1.9.0.201612210211]
> 	at org.openhab.binding.denon.internal.DenonConnector.connect(DenonConnector.java:161)[204:org.openhab.binding.denon:1.9.0.201612210211]
> 	at org.openhab.binding.denon.internal.DenonBinding.updated(DenonBinding.java:198)[204:org.openhab.binding.denon:1.9.0.201612210211]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[7:org.apache.felix.configadmin:1.8.8]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[7:org.apache.felix.configadmin:1.8.8]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[7:org.apache.felix.configadmin:1.8.8]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1444)[7:org.apache.felix.configadmin:1.8.8]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1400)[7:org.apache.felix.configadmin:1.8.8]
> 	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)[7:org.apache.felix.configadmin:1.8.8]
> 	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)[7:org.apache.felix.configadmin:1.8.8]
> 	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
> 

Seems to not working on telnet too.

**Comment by rapiertg** [comment]
Thanks. It seems to log this every 2 sec:
`2016-12-24 10:28:38.303 [WARN ] [inding.denon.internal.DenonConnector] - Unable to get the SURROUND_MODE. MainZone update may not be correct.`

If the xml key it is looking is preciselly "SURROUND_MODE" then it is not there. It have "SurroundMode".

Attaching device xml.
[Deviceinfo.xml.txt](https://github.com/openhab/openhab/files/671731/Deviceinfo.xml.txt)

**Comment by 9037568** [comment]
Is 2 seconds your configured refresh rate in the settings?
This will happen on each refresh...

**Comment by rapiertg** [comment]
Yes, it is currently set to 2 seconds thru http. Updates are working for items like power, source input and song details.

Can we make the Unable to get... log make DEBUG? The way it is now will flood the logs a lot.

**Comment by 9037568** [comment]
I think that's reasonable, since this failure is coming from a completely undocumented data file.

Here's an [updated jar.](https://github.com/openhab/openhab/files/673028/org.openhab.binding.denon-1.9.0-SNAPSHOT.zip)

**Comment by rapiertg** [comment]
Tested and its working fine for me for the device, except volume status, mute status and surround status. This is probably harder as under MainZone I get:
```
<?xml version="1.0" encoding="utf-8" ?>
<item>
<Power><value>ON</value></Power>
<InputFuncSelect><value>CD</value></InputFuncSelect>
<MasterVolume><value>-65.0</value></MasterVolume>
<Mute><value>off</value></Mute>
</item>
```

But the Values for Mute and MasterVolume are not reflecting actuall state. They are like this forever.

Could You maybe merge this change to openhab branch? This have no impact for other devices that were working before and enables at least one more device.

**Comment by 9037568** [comment]
These changes should be included in the next run of the [CI build](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.denon/target/org.openhab.binding.denon-1.9.0-SNAPSHOT.jar)

Looks like that runs around 3 am each day.

I'll leave this open for now. Drop a note if you think it should be closed.

**Comment by rapiertg** [comment]
This can be closed. Binding is working as expected now. Thank You. Now it is up to Marantz Support if they are willing to fix the firmware for Volume and Mute to work as expected. This is in progress.
