### ISSUE TITLE
Update Product File for another version of Trane Thermostat

### ISSUE THREAD

**Issue by identify3d-joe** [openhab/openhab1-addons#4803]
I have another version of the Trane Thermostat. Everything is the same, except my Type/ID is 5452:5431. So, I am requesting that the poduct.xml file be modified as described below:

<Manufacturer>
        <Id>008b</Id>
        <Name>Trane</Name>
        <Product>
            <Reference>
                <Type>5452</Type>
                <Id>5433</Id>
            </Reference>
            <Reference>
                <Type>5452</Type>
                <Id>5431</Id>
            </Reference>
            <Reference>
                <Type>5452</Type>
                <Id>5439</Id>
            </Reference>
            <Model>TZEMT400BB32MAA</Model>
            <Label lang="en">Trane Z-Wave Programmable Thermostat</Label>
            <ConfigFile>trane/tzemt400bb32maa.xml</ConfigFile>
        </Product>
    </Manufacturer>

**Comment by cdjackson** [comment]
Can you create a PR with the updated product.xml?

**Comment by 9037568** [comment]
Closed by merged PR.
