### ISSUE TITLE
Athmosphere transport notifications not working with OH 1.8.3

### ISSUE THREAD

**Issue by micw** [openhab/openhab1-addons#4837]
I run openhab 1.8.3 from debian repo. For some reason I had problems updating item states in the android app. I tracked it down to athmosphere transport notifications which seems not to work at all.

### Items
Switch test

### Sitemap
sitemap test label="Test" {
	Frame label="Test" {
		Switch item=test
	}
}

### Long-Polling:
curl -i http://127.0.0.1:8080/rest/sitemaps/default/test -H "X-Atmosphere-Framework: 1.0" -H "X-Atmosphere-Transport: long-polling" -H "X-Atmosphere-tracking-id: test1"

### Test:
Switch the switch on/off via UI

## Expected Behavior
Curl should receive a changed sitemap as soon as I change the switch status

## Current Behavior
Curl keeps waiting for response

## Steps to Reproduce (for bugs)
See above

## Context
The bug makes the android application unresponsive (shows item changes with large delays)

## Your Environment
Debian 8, OpenJDK 8 headless

**Comment by 9037568** [comment]
Can you provide a full debug log, @micw ?
