### ISSUE TITLE
Raspberry Pi GPIO Pins Not Responding

### ISSUE THREAD

**Issue by ezlikespie** [openhab/openhab1-addons#4912]
My Issue: GPIO Pins on the pi are not responding. I have installed openhab on my raspberry pi with the GPIO add-ons. If I go into the Openhab app I can see the switch that I made. I can turn the switch on and off but the LED on the pin I set it to isn't lightning up. I know my code is correct and I know I have wired the LED correct. I would just like to know whether I am missing an add-on or I need to configure something so that The GPIO pins will turn on

**Comment by 9037568** [comment]
You'll need to attach a debug log so that we can see what's happening with the binding.
