### ISSUE TITLE
[zwave-binding] Add new device: Popp Z-Weather

### ISSUE THREAD

**Issue by moonwhaler** [openhab/openhab1-addons#4929]
Hello,

please add support for the Device Popp Z-Weather to the database, It's already there, but it seems (even while using the latest nightly of openhab 2 + Zwave binding), mine isn't recognised:

**0154:0100:0400:1.0 (Unknown device)**

http://products.z-wavealliance.org/products/2102
Other request: https://github.com/openhab/openhab/issues/3757

Manufacturer: 0154 (Popp & Co.)
Type: 0100
ID: 0400

If you need something else, please tell me.
Thank you!

**Comment by cdjackson** [comment]
Added.

**Comment by moonwhaler** [comment]
Sorry, my bad. I use "openhab2" and posted this under openhab1-addons. But still: this doesn't work for openhab2 either. I completely re-installed everything from scratch, but while other devices are detected, this one is still showing up as "unknown".

Thank you.

**Comment by cdjackson** [comment]
Please open an issue on oh2 zwave issues list
