### ISSUE TITLE
Support for extra colormodes Epson Beamer binding

### ISSUE THREAD

**Issue by bartmx** [openhab/openhab1-addons#4935]
Can somebody add the extra following Colormodes in the epson projector binding?
In the file EpsonProjectorDevice.java

My beamer (Epson TW5000) support the following extra colormodes

CINEMANIGHT(0x05),
VIVID(0x06), 
HD(0x09),
SILVER(0x0A),
CINEMADAY(0x0C),

These are the current colormodes available in the binding:
DYNAMIC(0x06),
NATURAL(0x07),
XVCOLOR(0x0B),
LIVINGROOM(0x0C),
CINEMA(0x15),
ERROR(0xFF);

Problem that is see is that DYNAMIC and VIVID use the same HEX code.
Also CINEMADAY and LIVINGROOM.

Thanks

**Comment by jaydonoghue** [comment]
#5158 
I added these, plus a few others for another Epson projector

I kept LIVINGROOM and DYNAMIC as-is in the code

**Comment by bartmx** [comment]
Dear,

You contacted me in the past to inform you that have added extra color
modes for the epson beamer.
I cannot find these code on github and not in the binding? Dit somebody
removed it again from the code?

Kind
Regards
Bart
