### ISSUE TITLE
[knx] value could not be sent to the KNX data bus, no confirmation reply 

### ISSUE THREAD

**Issue by crystollic** [openhab/openhab1-addons#4949]
## Expected Behavior

Read and write to KNX bus used to work with openhab-binding-knx 1.9.0.b4
Doesn't work on 1.9.0.b5 and higher
Reverting to 1.9.0.b4 fixes problem.

## Current Behavior
Log looks like this: 
14:44:46.649 [WARN ] [al.bus.KNXBindingDatapointReaderTask] - Autorefresh: Cannot read value for item 'heating_frost_kitchen' from KNX bus: no confirmation reply received for L-Data.req from 0.0.254 to 9/0/0, low priority hop count 6 repeat tpdu 00 00: timeout
14:44:46.649 [WARN ] [al.bus.KNXBindingDatapointReaderTask] - Autorefresh: Remaining retries for address '9/0/0' = '2'
14:44:49.588 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'UFH_Shunt_Pump' received command OFF
14:44:50.002 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'UFH_GroundFloor_Pump' received command OFF
14:44:49.650 [WARN ] [.binding.knx.internal.bus.KNXBinding] - Value 'OFF' could not be sent to the KNX bus using datapoint 'command DP 9/0/0 heating_frost_kitchen, DPT main 0 id 1.001, low priority' - retrying one time: no confirmation reply received for L-Data.req from 0.0.254 to 9/0/0, low priority hop count 6 repeat tpdu 00 80
14:44:50.004 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'UFH_FirstFloor_Pump' received command OFF
14:44:52.651 [WARN ] [al.bus.KNXBindingDatapointReaderTask] - Autorefresh: Cannot read value for item 'Temp_FF_Bathroom' from KNX bus: no confirmation reply received for L-Data.req from 0.0.254 to 0/1/57, low priority hop count 6 repeat tpdu 00 00: timeout
14:44:52.652 [WARN ] [al.bus.KNXBindingDatapointReaderTask] - Autorefresh: Remaining retries for address '0/1/57' = '2'
14:44:55.653 [ERROR] [.binding.knx.internal.bus.KNXBinding] - Value 'OFF' could not be sent to the KNX bus using datapoint 'command DP 9/0/0 heating_frost_kitchen, DPT main 0 id 1.001, low priority' - giving up after second try: no confirmation reply received for L-Data.req from 0.0.254 to 9/0/0, low priority hop count 6 repeat tpdu 00 80
14:44:55.654 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'UFH_Zone2' received command ON
14:44:55.655 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'Temp_FF_Bathroom' received command 19.92
14:44:55.657 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'UFH_Shunt_Pump' received command OFF
14:44:55.657 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'UFH_Shunt_Pump' received command OFF
14:44:58.654 [WARN ] [.binding.knx.internal.bus.KNXBinding] - Value 'OFF' could not be sent to the KNX bus using datapoint 'command DP 0/1/103 UFH_Shunt_Pump, DPT main 0 id 1.001, low priority' - retrying one time: no confirmation reply received for L-Data.req from 0.0.254 to 0/1/103, low priority hop count 6 repeat tpdu 00 80
14:44:58.698 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'UFH_Zone4' received command OFF

## Your Environment
openhab Beta 5
Synology DSM6
Java 8.0.101-0011

**Comment by 9037568** [comment]
Can you provide a debug log of this scenario?
