### ISSUE TITLE
OpenHAB2 Snapshot 2.0.0~20170101125906  not starting after update, missing /var/lib/openhab2/tmp for lock file

### ISSUE THREAD

**Issue by bottkars** [openhab/openhab1-addons#4953]
## Current Behavior
bottk@openhab:~$ systemctl status openhab2.service
● openhab2.service - openHAB 2 - empowering the smart home
   Loaded: loaded (/usr/lib/systemd/system/openhab2.service; enabled; vendor preset: enabled)
   Active: active (running) since So 2017-01-01 17:27:36 CET; 1min 21s ago
     Docs: http://docs.openhab.org
           https://community.openhab.org
  Process: 1803 ExecStop=/usr/share/openhab2/runtime/bin/stop (code=exited, status=3)
 Main PID: 1988 (karaf)
    Tasks: 20
   Memory: 49.0M
      CPU: 1.949s
   CGroup: /system.slice/openhab2.service
           ├─1988 /bin/bash /usr/share/openhab2/runtime/bin/karaf server
           └─2143 /usr/bin/java -Dopenhab.home=/usr/share/openhab2 -Dopenhab.conf=/etc/openhab2 -Dopenhab.runtime=/usr/share/openhab2/runtime -Dopenhab.userdata=/var/lib/openhab2

Jan 01 17:27:38 openhab start.sh[1988]:         at org.apache.karaf.main.Main.createLock(Main.java:439)
Jan 01 17:27:38 openhab start.sh[1988]:         ... 3 more
Jan 01 17:27:38 openhab start.sh[1988]: Caused by: java.lang.RuntimeException: Could not create file lock: Invalid karaf.lock.dir system property '/var/lib/openhab2/tmp' : does n
Jan 01 17:27:38 openhab start.sh[1988]:         at org.apache.karaf.main.lock.SimpleFileLock.<init>(SimpleFileLock.java:58)
Jan 01 17:27:38 openhab start.sh[1988]:         ... 8 more
Jan 01 17:27:38 openhab start.sh[1988]: Caused by: java.lang.IllegalArgumentException: Invalid karaf.lock.dir system property '/var/lib/openhab2/tmp' : does not exist
Jan 01 17:27:38 openhab start.sh[1988]:         at org.apache.karaf.main.lock.SimpleFileLock.validateDirectoryExists(SimpleFileLock.java:117)
Jan 01 17:27:38 openhab start.sh[1988]:         at org.apache.karaf.main.lock.SimpleFileLock.getKarafLock(SimpleFileLock.java:93)
Jan 01 17:27:38 openhab start.sh[1988]:         at org.apache.karaf.main.lock.SimpleFileLock.<init>(SimpleFileLock.java:46)
Jan 01 17:27:38 openhab start.sh[1988]:         ... 8 more
bottk@openhab:~$ sudo mkdir /var/lib/openhab2/tmp

## Possible Solution
manually created /var/lib/openhab2/tmp

**Comment by kaikreuzer** [comment]
No, looks related to https://github.com/openhab/openhab-distro/pull/364, but most likely some issue with the Debian packaging. @BClark09 Any idea?

**Comment by kaikreuzer** [comment]
FTR, I have created https://github.com/openhab/openhab-distro/issues/366.

@bottkars The simple workaround seems to be to manually create the folder /var/lib/openhab2/tmp.
