### ISSUE TITLE
[OpenHABCloud] build fails

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab1-addons#4957]
## Expected Behavior
Building the openhabcloud connector should succeed.

## Current Behavior
Building the openhabcloud connector fails:
````
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.24.0:compile (default-compile) on project org.openhab.io.openhabcloud: Compilation failure: Compilation failure:
[ERROR] X:\java\openhab.mine\openhab\bundles\io\org.openhab.io.openhabcloud\src\main\java\org\openhab\io\openhabcloud\internal\CloudClient.java:[24]
[ERROR] import org.eclipse.jetty.client.ContentExchange;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.jetty.client.ContentExchange cannot be resolved
````

## Possible Solution

I tried several clean and rebuild cycles. No joy there.

## Steps to Reproduce

1. git pull
2. mvn clean install

## Environment

* Version used: latest code from master branch
* Operating System: Windows 10
* Maven version:
````
>mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:3
7-04:00)
Maven home: c:\Program Files\Maven\3.3.3\bin\..
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: c:\Program Files\Java\jdk1.8.0_112\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
````

**Comment by watou** [comment]
See https://github.com/openhab/openhab/pull/4884#issue-194786988, but curious to know how it could be made buildable?

**Comment by kaikreuzer** [comment]
You'd have to rebase the code on the 1.8 branch to make it compile.

**Comment by kaikreuzer** [comment]
I could also check it in there, but I preferred to have it visible on the current master. If you think it is better to move it away from master to the 1.8 branch, it would be fine for me as well.

**Comment by watou** [comment]
> If you think it is better to move it away from master to the 1.8 branch, it would be fine for me as well.

It makes more sense to me that the code is moved to the 1.8 branch, since it's not intended to be buildable or usable on the master branch but instead only to be used with the 1.8.x runtime.
