### ISSUE TITLE
[HTTP Binding] JSON Body impossible with parseOutBindingConfig

### ISSUE THREAD

**Issue by computerlyrik** [openhab/openhab1-addons#4992]
## Expected Behavior
```http='>[*:POST:http://192.168.178.2/animation:{"name": "rainbow"}]'```
shall send a POST request with appended json data.

## Current Behavior
It tries to parse HTTP Headers from some "endsWith trimmed } and contains {"
https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpGenericBindingProvider.java#L267

## Possible Solution

Refactor Regexes (modular) according to documentation, e.g. match(3) as url+headers and match(4) as body.
Parse URL headers from match(3) string.

## Steps to Reproduce (for bugs)
compile current git master from https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.http

run with any Outgoing (e.g. Switch) Item 
```Switch Rainbow (Animations)  { http='>[*:POST:http://192.168.178.2/animation:{"name": "rainbow"}]', autoupdate="false"}```

## Context
OpenHAB --> REST --> nodeMCU --> Lamp

## Your Environment
Home Environment. Running openHAB on Raspberry pi 3 and arch Linux with jre 1.8_u112.
Compiled **1.9.0-SNAPSHOT** Version of HTTP Bindings and added to stable 1.8.3 Server instance.

**Comment by 9037568** [comment]
I have a fix in progress. Needs a bit of additional testing.
