### ISSUE TITLE
[MAX!Cube Binding] more than one Cube possible?

### ISSUE THREAD

**Issue by ModuloFS** [openhab/openhab1-addons#5003]
Hello,

is it possible to connect more than one Cube to the MAX!Cube binding?

**Comment by watou** [comment]
The [wiki](https://github.com/openhab/openhab1-addons/wiki/MAX!Cube-Binding) does not seem to suggest this is possible.  Please consider opening a discussion at https://community.openhab.org to see if others know better, or share your interest in someone implementing this feature.
