### ISSUE TITLE
[ekey] binding isn't presently on the install list

### ISSUE THREAD

**Issue by binderth** [openhab/openhab1-addons#5015]
## Expected Behavior
The ekey binding works in principal also with OH2 (see issue #5014) and as such I'd expect it to be in the (legacy) repository and ready for easy install via `addons.cfg` for example.

## Current Behavior
currently, the binding isn't officially listed, and therefore you have to install it manually in the OH2 console using:
```bundle:install https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.ekey/target/org.openhab.binding.ekey-1.9.0-SNAPSHOT.jar```
```bundle:start <<ID OF BUNDLE>>```
Then the binding can be configured using `/services/ekey.cfg` as usual.

## Possible Solution
listing the bundle in the repository for easy Installation. At present, I have to reinstall the bundle on every update of OH2

## Steps to Reproduce (for bugs)
1. filling in the `addons.cfg`:  `binding = ekey1`
2. binding isn't found

## Context
as explained, the binding works (in RARE mode), but has to be reinstalled with every new update of OH2 in the console, which is a bit boring! ;)

## Your Environment
* Version used: (e.g., openhab and addon versions): recent OH2 build: #739, ekey-binding: 1.9.0.201701190930 (installed via the console: `bundle:install https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.ekey/target/org.openhab.binding.ekey-1.9.0-SNAPSHOT.jar`)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): JAVA8
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): openHABian on rasbian Jessie lite

**Comment by watou** [comment]
Thanks @binderth !  In the queue.
