### ISSUE TITLE
[IHC] Dates retrieved are offset by one month

### ISSUE THREAD

**Issue by vakdevi** [openhab/openhab1-addons#5016]
## Expected Behavior
Dates within IHC should match the shown dates in OpenHAB

## Current Behavior
Dates coming from IHC are offset by +1 month
[See this discussion](https://community.openhab.org/t/ihc-dates-are-offset-by-one-month/17790)

## Steps to Reproduce (for bugs)
Add a DateTime item and link to an IHC date to observe the phenomenon
E.g. `DateTime ihc_last_restart_date	"Restart date [%1$tF]"	<info> {ihc="<0x12f8730e"}`

## Your Environment
* OpenHAB 1.8.3 on Raspbian Jessie
* A log of events is attached [log.txt](https://github.com/openhab/openhab1-addons/files/719450/log.txt)

**Comment by 9037568** [comment]
Please provide a debug log and your OS environment.

**Comment by paulianttila** [comment]
I agree this problem and in fact, I already did fix for this and I quickly test it as well. I have just forgotten to make PR for it, as I'm not personally use date and time resources from the IHC controller.

**Comment by paulianttila** [comment]
@9037568, you can assign this issue to me

**Comment by vakdevi** [comment]
I made a pull request https://github.com/openhab/openhab1-addons/pull/5018
I have tested it on my own setup.
