### ISSUE TITLE
[zway] Z-Wave ZHC5010 not recognized in OH2 RC1 in zway binding

### ISSUE THREAD

**Issue by rhjensen79** [openhab/openhab1-addons#5017]
Z-Wave ZHC5010 is not recognized in OH2 RC1. 

The version used is : ZHC5010-WH-4L
It should already be present in the z-wave database, but it's not recognized, by some strange reason.

Links : https://youcontrol.dk/media/wysiwyg/ZHC5010_datablad_1.pdf

Information from OH2. 

![skaermbillede 2017-01-20 kl 13 06 17](https://cloud.githubusercontent.com/assets/24954205/22148939/481c9b90-df11-11e6-9a22-68e9be46a993.jpg)

**Comment by watou** [comment]
Is this regarding the zwave1 or zwave binding?  If the latter, please close this issue and open a new one in the openhab/org.openhab.binding.zwave.  Thanks.

**Comment by watou** [comment]
Or the new zway binding, in which case I think the issue goes to openhab/openhab2-addons.

**Comment by rhjensen79** [comment]
Damn. You are right. I will close it and create it the right place. Thanks.

**Comment by watou** [comment]
It can be confusing no doubt!
