### ISSUE TITLE
Not all bundles loaded on first start

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab1-addons#5022]
Hi, I noticed a possible bug while testimg openHAB 2.

I performed the following steps:

1. Started a clean install of OH2, without modifying any of the configuration files
-> Everything OK

2. Stopped OH2 and copied my config files and restarted it
This resulted in the following warning ragarding the installation of the transformation services:

`23:20:15.109 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-transformation-xpath, openhab-transformation-map, openhab-transformation-javascript, openhab-transformation-xslt, openhab-transformation-regex, openhab-transformation-exec, openhab-transformation-scale, openhab-transformation-jsonpath': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-exec1; type=karaf.feature; version="[1.9.0.SNAPSHOT,1.9.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-exec1)(type=karaf.feature)(version>=1.9.0.SNAPSHOT)(version<=1.9.0.SNAPSHOT))"
`

Additionally openHAB tries to uninstall some bundles, which fails :

`23:20:19.288 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed uninstalling 'openhab-ui-cometvisu': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-exec1; type=karaf.feature; version="[1.9.0.SNAPSHOT,1.9.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-exec1)(type=karaf.feature)(version>=1.9.0.SNAPSHOT)(version<=1.9.0.SNAPSHOT))"

23:20:23.487 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed uninstalling 'openhab-misc-homekit': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-exec1; type=karaf.feature; version="[1.9.0.SNAPSHOT,1.9.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-exec1)(type=karaf.feature)(version>=1.9.0.SNAPSHOT)(version<=1.9.0.SNAPSHOT))"
`

3. Stopped and restarted OH2 without changing the configuration:

Only a warning regarding regex transformation:
`00:02:31.051 [WARN ] [.core.transform.TransformationHelper] - Cannot get service reference for transformation service of type REGEX
00:02:31.051 [WARN ] [ab.binding.exec.internal.ExecBinding] - couldn't transform response because transformationService of type 'REGEX' is unavailable
`

4. Stopped and restarted OH2 without changing the configuration:
-> No more warnings, works as expected.

I have the following configuration in addons.cfg (all other entries are commented out). As the transformation services are part of the expert package they should have been installed on the first start, additionally OH2 should not have tried to deinstall other bundles:

`package = expert

remote = true

legacy = true

experimental = true
binding = astro,caldav-command1,denon1,exec1,fritzboxtr0641,http1,hue,knx1,network,snmp1,tcp1,weather1,wol1

ui = basic, classic, cometvisu, habmin, habpanel, paper

persistence =jdbc-sqlite,mapdb,rrd4j

action = mail, prowl

misc = homekit, restdocs`

As it worked after some retries this might have been a temporary problem with a server or OH2 needed more time to install all addons?!

**Comment by 9037568** [comment]
This does not appear to be a problem with an OH1 addon.
