### ISSUE TITLE
[snmp] Binding produces a lot of Null Pointer Exceptions

### ISSUE THREAD

**Issue by tkuehne71** [openhab/openhab1-addons#5027]
Clean install of 2.0RC1.

Added the snmp binding (1.9.0.RC1) from the UI, configured Port=16200 in snmp.cfg and added a few items to read and write from a network switch, i.e. ifAdminState (.1.3.6.1.2.1.2.2.1.7) and ifOperState(.1.3.6.1.2.1.2.2.1.8):

> switch sw1_P3 "sw1_en03: Port3" (sw1) { snmp="<[192.168.1.1:public:.1.3.6.1.2.1.2.2.1.8.3:300000:MAP(SwitchState.map)] >[OFF:192.168.1.1:private:.1.3.6.1.2.1.2.2.1.7.3:2] >[ON:192.168.1.1:private:.1.3.6.1.2.1.2.2.1.7.3:1]" }

Communication works, I can switch the corresponding switch port between admin up and down.
However, the binding generates a lot (i.e. one every few hundred milliseconds) of null pointer exceptions like:

> 2017-01-22 12:01:25.526 [INFO ] [b.core.service.AbstractActiveService] - SNMP Refresh Service has been started
> 2017-01-22 12:01:25.536 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread SNMP Refresh Service
> java.lang.NullPointerException
> at org.snmp4j.MessageDispatcherImpl.getTransport(MessageDispatcherImpl.java:219)[235:org.openhab.binding.snmp:1.9.0.RC1]
> at org.snmp4j.MessageDispatcherImpl.sendPdu(MessageDispatcherImpl.java:427)[235:org.openhab.binding.snmp:1.9.0.RC1]
> at org.snmp4j.Snmp.sendMessage(Snmp.java:1004)[235:org.openhab.binding.snmp:1.9.0.RC1]
> at org.snmp4j.Snmp.send(Snmp.java:974)[235:org.openhab.binding.snmp:1.9.0.RC1]
> at org.snmp4j.Snmp.send(Snmp.java:958)[235:org.openhab.binding.snmp:1.9.0.RC1]
> at org.openhab.binding.snmp.internal.SnmpBinding.sendPDU(SnmpBinding.java:443)[235:org.openhab.binding.snmp:1.9.0.RC1]
> at org.openhab.binding.snmp.internal.SnmpBinding.execute(SnmpBinding.java:354)[235:org.openhab.binding.snmp:1.9.0.RC1]
> at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:157)[176:org.openhab.core.compat1x:2.0.0.RC1]
> at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)[176:org.openhab.core.compat1x:2.0.0.RC1]

I verified that the port 16200 that I configured is properly bound, so that doesn't seem to be the issue. This is on Ubuntu Server 16.04.1 LTS. Iptables is inactive (default policy on all chains is ACCEPT).

**Comment by J-N-K** [comment]
Please set snmp.internal to DEBUG with

log:set DEBUG org.openhab.binding.snmp.internal

and show the result. It looks like for some reason the target-address of the item is not properly configured, therefore getTransport fails. There are several possibilities to address this issue, but I would liek to see the reason WHY the target address is missing.

**Comment by tkuehne71** [comment]
aargh, i found a typo in one of the IP adresses in my item definition. that's what caused the error.

**Comment by 9037568** [comment]
Glad it was an easy fix ;)

**Comment by J-N-K** [comment]
I disagree. NPE should Never be thrown. I'll have a Look How to catch that.

**Comment by tkuehne71** [comment]
ok, the typo was a spelling error in the GET part of the SNMP item: I wrote 

> switch sw1_P3 "sw1_en03: Port3" (sw1) { snmp="<[192.168.1.**1.**1:public:.1.3.6.1.2.....

**Comment by J-N-K** [comment]
see PR #5031
