### ISSUE TITLE
[piface] Please include in OH2

### ISSUE THREAD

**Issue by jpgnz** [openhab/openhab1-addons#5032]
piface-1.9.0 is working perfectly on OH2 when installed manually.

There's been some discussion on the forums (https://community.openhab.org/t/openhab2-piface-setup/13363/4 and subsequently https://community.openhab.org/t/piface-binding-works-on-oh-2-0/21000) about getting this included in the legacy bindings in OH2 by default, and ultimately this was the best place to log the issue.

If any specific detail is required, I'm using this binding daily on OH2.0.0, I can provide information.

**Comment by watou** [comment]
Thanks!
