### ISSUE TITLE
[jdbc::mysql] Constant useSSL Warnings

### ISSUE THREAD

**Issue by ajw107** [openhab/openhab1-addons#5033]
## Expected Behavior
The openhab console shouldn;t be being swamped with mysql warnings.

## Current Behavior
The warning message:
> WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Is displayed on every SQL command, so quite a few times a minute.

## Possible Solution
The MYSQL binding should have withe an option to set useSSL=true/false in the config file, or if a SSL certificate is used this should be added to the truststore (no real information found on this last bit).  Easiest would be the useSSL option, which surpresses the warning on every SQL command (so is incredibly frequent), although does not affect the functionality of JDBC apparently.  There is a security concern here, but as most peopel will be using a mysql server either on the same machine, or on their local network, it shouldn;t be an issue.
I did try changing my url to both:
`url=jdbc:mysql://<mysql server ip address>:<port>/<openhabdbname>?useSSL=false` (the solution mentioned when I googled the issue)
`url=jdbc:mysql://<mysql server ip address>:<port>/<openhabdbname>;useSSL=false` (which a quick look at the code seems to suggest should work)
neither worked, and stopped openhab from being able to connect to the mysql database.
The solution can be seen being discussed on these, as well as other, site:
[Luv2Code](http://www.luv2code.com/2016/05/20/jdbc-and-mysql-getting-rid-of-the-dreaded-message-warn-establishing-ssl-connection-without-servers-identity-verification-is-not-recommended/)
[StackOverflow1](http://stackoverflow.com/questions/34189756/warning-about-ssl-connection-when-connecting-to-mysql-database)
[StackOverflow2](http://stackoverflow.com/questions/34590652/what-is-the-actual-issue-mysql)

## Steps to Reproduce (for bugs)
Just use the MYSQL persistence binding, and check the console output

## Context

# Your Environment
Using Openhab2 build 752 and persistence-mysql 1.10.0 SNAPSHOT (jdbc is same version too), both from the kar file associated with the 752 build
Running on Windows 10x64 (only thing my AEOTEC S2 Zwave stick will run reliably on for some reason) with JAVA 1.8.0 build 121
and mysql server 5.7.17 on Ubuntu 16.10 and triied on windows version as well

**Comment by 9037568** [comment]
It would be helpful if you could provide a debug log of one or more of your scenarios. (eg. with "?useSSL=false")

The listed WARN message does not appear to be coming from OH, but from a lower-level API.

**Comment by 9037568** [comment]
Closed for lack of input. Drop a note here to restart.
