### ISSUE TITLE
Fatek PLC Binding - dodanie drugiego rejestru do zapisu dla typu Number

### ISSUE THREAD

**Issue by DZIKI2005** [openhab/openhab1-addons#5035]
Hello, zipper slider (in OpenHab2) or Dimmer (in ImperiHome) current przydałbysię reading registry PLC FATEK eg. R100 and write to the second register np.R101.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by watou** [comment]
Hello, I'm sorry but we cannot proceed with this issue report due to the language difference.  Please open a new issue in English.  Thank you.
