### ISSUE TITLE
mqtt clientID is not taken from the opehab.cfg but automatically generated

### ISSUE THREAD

**Issue by ggolec** [openhab/openhab1-addons#5055]
I defined clientID for mqtt as this is required by external mqtt broker:

mqtt:cayenne.url=tcp://mqtt.mydevices.com:1883
mqtt:cayenne.clientid=01155d90-e731-11e6-a971-4db18559717d

tcp connection works fine. it is connected but not authorized. Cayenne requires valid clientID to be sent. 

In parallel I configured Chromium addon MQTT lens to test the same connection. I used the same  and authentication works without any problems. 

I took network trace to see what is the difference in sent requests.
It seems to MQTT field is set as: 
Client ID: owca.1485813787709
instead of the one configured in openhab.cfg

in Chrome browser addon MQTT Lens in network trace correct one is set and field takes values as below: 
Client ID: 01155d90-e731-11e6-a971-4db18559717d

## Expected Behavior
openhab is taking mqtt clientID that is set in openhab.cfg 

## Current Behavior
openhab ignores mqtt.broker.clientID setting and generates random one (<username>.<numbers>)

## Steps to Reproduce (for bugs)

1. set mqtt clientID in configuration
2. sniff for traffic when connecting to the broker
3. check what is sent
4.

## Context
I tried to connect openhab to the mydevices.com service over mqtt 

## Your Environment

* Version used: openhab 1.8.3
* Environment name and version 
* Operating System and version: Sabayon Linux amd64 16.08

**Comment by ggolec** [comment]
![image](https://cloud.githubusercontent.com/assets/25458934/22470445/a212c55e-e7cf-11e6-97d4-7ee33ad7f317.png)

**Comment by watou** [comment]
> mqtt:cayenne.clientid=01155d90-e731-11e6-a971-4db18559717d

The configuration key is case sensitive.  It must be `clientId`.

**Comment by ggolec** [comment]
it was from very beginning, I changed to try that maybe this is fault
I retried once again with clientId in configuraiton. The same issue. 
![image](https://cloud.githubusercontent.com/assets/25458934/22476590/3be254ac-e7e3-11e6-857e-d4598b96151a.png)

**Comment by ggolec** [comment]
please reopen

**Comment by watou** [comment]
Now I see `clientID` where you need `clientId`?

**Comment by ggolec** [comment]
just to be clear. piece of config:
mqtt:cayenne.url=tcp://mqtt.mydevices.com:1883
mqtt:cayenne.clientId='01155d90-e731-11e6-a971-4db18559717d'
mqtt:cayenne.user=e94888f0-e725-11e6-a971-4db18559717d

value is still replaced by random name in format <username>.<numbers>

It should look like this. I used MQTTLens - chrome addon:
![image](https://cloud.githubusercontent.com/assets/25458934/22482713/826f2f64-e7fa-11e6-81e5-f57b419b42ea.png)

**Comment by ggolec** [comment]
wrrrrr.... this one. No quatations just like in documentation. 
mqtt:cayenne.url=tcp://mqtt.mydevices.com:1883
mqtt:cayenne.clientId=01155d90-e731-11e6-a971-4db18559717d
mqtt:cayenne.user=e94888f0-e725-11e6-a971-4db18559717d

I tried different settings, small letters, quotation marks ' "" etc. But default conf doesn;t work. 
It's a BUG

**Comment by 9037568** [comment]
ClientId values are required to be 23 characters or less.

See
https://github.com/openhab/openhab1-addons/blob/db62be70e9cd9561036d8925a177a2e37aaa4bd4/bundles/io/org.openhab.io.transport.mqtt/src/main/java/org/openhab/io/transport/mqtt/internal/MqttBrokerConnection.java#L284
.

If the ClientId is longer, a new random one is generated.

**Comment by ggolec** [comment]
yeah it seems to be the issue. Just tried something like 'alalala' and it is set correctly... 
any chance to change its limit to 36 characters?
01155d90-e731-11e6-a971-4db18559717d

**Comment by ggolec** [comment]
OK it seems to you follow specification. The service I try to use doesn't... 
http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html#connect

If you are not willing to adjust a bit standards :) feel free to close it. I will ask cayenne service owners to fix it on their site.

**Comment by 9037568** [comment]
According to the latest specification I could find (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718031), servers MAY allow longer identifiers:

>The Server MAY allow ClientId’s that contain more than 23 encoded bytes. The Server MAY allow ClientId’s that contain characters not included in the list given above.

Based on that, we might want to allow the binding to accept such values.

**Comment by ggolec** [comment]
The same wrote me guys from Cayenne - mydevices.com:
http://community.mydevices.com/t/clientid-in-mqtt-is-too-long-against-mqtt-standards/2192

**Comment by 9037568** [comment]
I have a fix in work. Need to add a new configuration parameter to preserve the old behaviour.
