### ISSUE TITLE
Fibaro FGMS001-001 ZW5 Motion Sensor v3.2 / openHABianPi 

### ISSUE THREAD

**Issue by cedricwalter** [openhab/openhab1-addons#5075]
Can not fetch any items value from sensor
## Expected Behavior
being able to see items value from sensor

## Current Behavior
1. add things
2. define items
3. Go to paper UI control, no value from motion sensor get displayed

Binary Sensor 
Temperature -NaN
Seismic Intensity -NaN
Luminance -NaN
Motion alarm
Tamper
Battery Level  NaN
General alarm

## Your Environment
1. rapsberry PI 3 with Linux openHABianPi 4.4.0-1-rpi2 #1 SMP Debian 4.4.6-1+rpi14 (2016-05-05) armv7l GNU/Linux
2. openHAB 2.0.0-1 (Release Build) on /dev/ttyACM0
3. Latest AEONtec Gen5 USB
4. Fibaro FGMS001-001 ZW5 Motion Sensor v3.2

Note: i am a java developer, so a dirty temporary solution is acceptable ;-)

**Comment by cdjackson** [comment]
Please consider discussing this on the forum first. If there is a bug established, then since you are using OH2, you should open the issue in the [OH2 zwave issue list](https://github.com/openhab/org.openhab.binding.zwave/issues) - but only once a bug is found.
