### ISSUE TITLE
Support for Intertechno V3

### ISSUE THREAD

**Issue by overrunner** [openhab/openhab1-addons#5076]
Hi,
i am running the Intertechno Binding on my openhab 2.0.
Currently it seems not possible to use Intertechno v3 with 26-bit addresses as the on/off command between the "housecode" and the "device" code.
see here for explanation:  https://wiki.fhem.de/wiki/Intertechno_Code_Berechnung#Mit_neuem_Protokoll_anlernen

**Comment by watou** [comment]
@dereulenspiegel @tarioch Is support for Intertechno v3 something that can be added to this binding?

**Comment by tarioch** [comment]
Unfortunately currently don't have the time to look into this, but it shouldn't be that hard to add. Adding a bit configuration for it and adjusting

internalReceiveCommand in

https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.intertechno/src/main/java/org/openhab/binding/intertechno/internal/CULIntertechnoBinding.java

**Comment by watou** [comment]
Thank you @tarioch for the guidance.
