### ISSUE TITLE
[Modbus] Binding restarts service after config change - keeping serial port open

### ISSUE THREAD

**Issue by ManniAT** [openhab/openhab1-addons#5078]
Trying to figure out parameters for a modbus serial device I changed modbus.cfg several times.
Changing setting sometimes seems to restart the addon.

What I noticed was that after such a restart the addon stopped working.
Checking the logs I found entries like this:

> 19:08:04.715 [ERROR] [et.wimpi.modbus.net.SerialConnection] - open port failed: Modbus Serial Master
> 19:08:04.717 [ERROR] [ing.ModbusSlaveConnectionFactoryImpl] - connect try 1/3 error: open port failed: Modbus Serial Master. Connection SerialConnection@1e19c7d[portName=/dev/ttyUSB99,port=<null>]. Endpoint ModbusSerialSlaveEndpoint@1098b8e[portName=/dev/ttyUSB99]
> 19:08:34.754 [ERROR] [et.wimpi.modbus.net.SerialConnection] - open port failed: Modbus Serial Master
> 19:08:34.756 [ERROR] [ing.ModbusSlaveConnectionFactoryImpl] - connect try 2/3 error: open port failed: Modbus Serial Master. Connection SerialConnection@1e19c7d[portName=/dev/ttyUSB99,port=<null>]. Endpoint ModbusSerialSlaveEndpoint@1098b8e[portName=/dev/ttyUSB99]
> 19:09:04.793 [ERROR] [et.wimpi.modbus.net.SerialConnection] - open port failed: Modbus Serial Master
> 19:09:04.795 [ERROR] [ing.ModbusSlaveConnectionFactoryImpl] - connect try 3/3 error: open port failed: Modbus Serial Master. Connection SerialConnection@1e19c7d[portName=/dev/ttyUSB99,port=<null>]. Endpoint ModbusSerialSlaveEndpoint@1098b8e[portName=/dev/ttyUSB99]
> 19:09:04.796 [ERROR] [ing.ModbusSlaveConnectionFactoryImpl] - re-connect reached max tries 3, throwing last error: open port failed: Modbus Serial Master. Connection SerialConnection@1e19c7d[portName=/dev/ttyUSB99,port=<null>]. Endpoint ModbusSerialSlaveEndpoint@1098b8e[portName=/dev/ttyUSB99]
> 19:09:04.798 [ERROR] [ing.ModbusSlaveConnectionFactoryImpl] - Error connecting connection SerialConnection@1e19c7d[portName=/dev/ttyUSB99,port=<null>] for endpoint ModbusSerialSlaveEndpoint@1098b8e[portName=/dev/ttyUSB99]: open port failed: Modbus Serial Master
> 19:09:04.799 [WARN ] [.binding.modbus.internal.ModbusSlave] - ModbusSlave (eehtc): Error ...

The easiest way to see if that happend was that my adapter stopped blinking (no more traffic).

Restarting openhab2 fixes the problem.
At least until I make the next change to modbus.cfg

Environment:
Openhab2 on raspberry pi 3
Serial: FTDI USB Serial converter FT232RL
Editing of modbus.cfg was made via a windows client using the openHAB-conf share.
see: https://community.openhab.org/t/modubs-configuration-for-ee800-device/21274/14

**Comment by 9037568** [comment]
This appears to be functioning as designed.  Every time the configuration changes, the connections are closed, the connection pool is cleared and rebuilt.  The binding itself does not restart, from what I can see.

To delve any further into this, we'd need a debug log.

**Comment by ssalonen** [comment]
I could reproduce this using an integration test, and at least the test was fixed by the above solution. See the PR #5088 for a pre-compiled test version with the described fix.

**Comment by ssalonen** [comment]
@manniat have you had the chance to try this out?

Best
Sami
