### ISSUE TITLE
[Modbus] Requests to removed (from config) units

### ISSUE THREAD

**Issue by xeax** [openhab/openhab1-addons#5084]
Binding send requests to removed slave units (removed from config - /etc/openhab2/services/modbus.cfg)
Restarting OH2 doesn't helps.
Rebooting RPi also. Even removing power for some time doesn't help.

## Steps to Reproduce (for bugs)
Add serial.slave1, serial.slave3, serial.slave11, then remove serial.slave3
Restart computer
But not sure, because can't return system to initial state now without full openhabian reinstall.

## Your Environment
* Version used: 
openHAB 2.0.0~20170119040408-1 (Build #735)
binding-modbus1 - 1.9.0.SNAPSHOT
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
opanHABian on RPi 3

**Comment by 9037568** [comment]
Not sure how this could happen, given the way connections are treated on a config update.

Need to see a debug log.

**Comment by ssalonen** [comment]
Perhaps this is related https://community.openhab.org/t/modbus-log-erro-item-that-doesn-t-exists-anymore/22661/14

**Comment by 9037568** [comment]
Glad to see someone's logged the [larger issue](https://github.com/openhab/openhab-distro/issues/396).

**Comment by ssalonen** [comment]
"Larger issue" is now closed, perhaps this should be closed as well?

**Comment by 9037568** [comment]
Thanks for the pointer...

**Comment by ssalonen** [comment]
@9037568  and others: User in community forums reported issues still,, see [this post](https://community.openhab.org/t/modbus-binding-works-intermittently-with-wago-750-881-plc/42039/2?u=ssalonen).

By following the "larger issue" (openhab-distro [#396](https://github.com/openhab/openhab-distro/issues/396#issuecomment-332236729) Parameters removed from binding cfg files persist in userdata/config even after restart), it feels like the implementation went half-way? Last discussion point talks about some pid markers but not sure if users are instructed to anything like that?

**Comment by ssalonen** [comment]
Another issue with cached configurations https://community.openhab.org/t/modbus-log-erro-item-that-doesn-t-exists-anymore/22661/14?u=ssalonen
