### ISSUE TITLE
<lgtv> No update after poweroff/poweron

### ISSUE THREAD

**Issue by Sandriekus** [openhab/openhab1-addons#5086]
## Expected Behavior / Current Behavior

I have installed the lgtv binding into openhab2. the connection is ok, values are showing up and i can control the volume/mute. when i power off the tv (with the original remote, i dont use the software item in openhab) the value's are going to 0 (offcourse). when i power on the tv again, the values are not updating. it looks like the connection is dropped, and not checking if the tv is powered on again.

openhab.log shows:
2017-02-13 11:28:36.037 [ERROR] [binding.lgtv.internal.LgtvConnection] - IO Exception at Connection to: http://192.168.2.12:8080/udap/api/data?target=volume_info
2017-02-13 11:28:36.037 [INFO ] [binding.lgtv.internal.LgtvConnection] - lgtv connectionstatus of ip=192.168.2.12 changed from CS_PAIRED to CS_NOTCONNECTED

i have waited 10 minutes now, and there is no new connection

## Possible Solution

checkalive function does not work for openhab2, i think.

## Steps to Reproduce (for bugs)

1. install lgtv binding in PaperUI
2. edit conf/services/lgtv.cfg:

```

# The ip address of the lgtv (required)
LG_Woonkamer.host=192.168.2.12

# The TCP port to use (optional, defaults to 8080)
LG_Woonkamer.port=8080

# The the pairkey / if it's wrong the device shows the right pairkey
# at every connection attempt
LG_Woonkamer.pairkey=671887

# The TCP port address of the openhab system to receive lgtv status messages
# (only first occurrence is used for all TVs)
LG_Woonkamer.serverport=8080

# The location to put XML files with the information of availiable
# channels and apps (optional)
#<lgtvId1>.xmldatafiles=./

# The check alive interval (optional, defaults to 60secs)
LG_Woonkamer.checkalive=10
```

3. configure items
4. configure sitemap
5. check if values are showing up
6. turn off tv
7. check if values are 0
8. turn on tv
9. items are not updating

## Your Environment

* Version used: (e.g., openhab and addon versions) openHAB2
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): LGTV 1.9.0
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Windows 10 with LG TV 42LA6208

**Comment by Sandriekus** [comment]
extra info:
when i shutdown OpenHAB and start it again.. the communication is fixed..
when i shutdown the tv, and turn in on again.. same issue.. not updating anymore

**Comment by 9037568** [comment]
To increase the chances of this getting fixed, you should include a debug log.

**Comment by AngelosF** [comment]
default lgtv.cfg has a wrong example for the port to communicate to the TV
it should be:

```
# The TCP port to use (optional, defaults to 60128)
LG_Woonkamer.port=60128
```

Ref: https://www.openhab.org/addons/bindings/lgtv1/#example
