### ISSUE TITLE
DMX OLA: With newest updates OLAD is consuming more and more memory

### ISSUE THREAD

**Issue by msfunty** [openhab/openhab1-addons#5093]
With current version 1.10 of the DMX (OLA) binding the OLA daemon using constantly using more and more memory. In my setup OLAD is starting with about 6.5 MB, after 1 day it is more than 200 MB.
As there was no change in the OLA service itself, I assume this is due to some changes within that binding. AFAIR that behavior started about 2 - 4 weeks ago.
So currently I need to restart the daemon everyday.

Another issue: When restarting OLA daemon the binding is (of course) losing the connection resulting in error entries in the log each 35 ms. If OLA daemon is down for some seconds the log file is flooded with that error messages.

BTW: I'm using OH2.

**Comment by J-N-K** [comment]
Please try repeatMode=never in the config.

**Comment by msfunty** [comment]
With repeatMode=never OLAD is not consuming more and more memory.

But IHMO this still is a bug as I can't images that repeating data should increase data footprint significantly, right?
Also when losing connection to OLAD you still have the log issue.

**Comment by J-N-K** [comment]
It is a bug, but it is not inside Openhab but inside OLA. please file a bug there.

The log is a totally different issue. What is the expected behaviour? Should OH stop trying to connect after some tries? Should it stop reporting and you never now why something is not working? In ESH the thing status should be switched to offline but there is no such option for OH1 addons (no matter where they run (OH1/OH2). This should be discussed in the forum.

**Comment by msfunty** [comment]
I would be nice to have some configuration similar to e.g. KNX binding.
There you have a number a timeout (duration of next connection attempt) and a number of retries.
Once the connection is lost there is an entry in the log file and timeout duration is starting. After that, e.g. 30 seconds, there is a new try to connect. Up to a maximum of # retries.

**Comment by J-N-K** [comment]
I think this should be closed for two reasons: first there is a new ESH binding for DMX, so probably this code will not be updated anymore and second, it's still a bug in OLA, not in OH.

**Comment by 9037568** [comment]
Thanks, @J-N-K.
