### ISSUE TITLE
MAX!Cube Binding doesnt respond anymore to Alexa-Voice command via Hue-Emulation

### ISSUE THREAD

**Issue by rrutk** [openhab/openhab1-addons#5099]
MAX!Cube Binding doesnt respond anymore to Alexa-Voice command via Hue-Emulation.

No change at all, but the voice command "Heating to xy degrees" is not answered all the time with "This command doesnt work for this device".

It has worked for weeks ("Heating to xy degrees")...

Any ideas?

**Comment by 9037568** [comment]
You should ask this question in the [community forum](http://community.openhab.org).
