### ISSUE TITLE
Dieser Befehl funktioniert nicht für das Gerät Heizung

### ISSUE THREAD

**Issue by rrutk** [openhab/openhab1-addons#5102]
Problem:

Wochenlang hat meine Kombination Alexa + openHAB mit Hue-Emulation und Max!-Binding wunderbar funktioniert: "Heizung auf xy Grad" -> Voila.
Seit gestern kommt beim Befehl: "Heizung auf xy Grad" nur noch die Antwort  "Dieser Befehl funktioniert nicht für das Gerät Heizung".

Das "Gerät Heizung" ist ein emuliertes Hue-Gerät und wird von der Alexa-App als Typ "Lux Light" erkannt.

https://github.com/openhab/openhab2-addons/tree/master/addons/io/org.openhab.io.hueemulation

Bisher hat es immer den Befehl für eine Temperaturänderung entgegengenommen.

Anscheinend wurde an der Alexa-Software irgendwas verändert, so dass sie die "Lux Light" (emulierten Hue)-Geräte nicht mehr mir "Grad"-Befehlen ansprechen kann??!

Ich habe auf meiner Seite alle Fehlerquellen ausgeschlossen.

Haben Sie noch irgendwelche Ideen?

------------

MAX!Cube Binding doesnt respond anymore to Alexa-Voice command via Hue-Emulation.

No change at all, but the voice command "Heating to xy degrees" is not answered all the time with "This command doesnt work for this device".

It has worked for weeks ("Heating to xy degrees")...

Any ideas?

**Comment by kaikreuzer** [comment]
Please stop the cross-postings and stick to English, please.
