### ISSUE TITLE
Feature Request: use any item in layout of weather binding

### ISSUE THREAD

**Issue by staehler** [openhab/openhab1-addons#5103]
In openhab 1 it was possible to include individual item states in the weather binding layout. So I could use my own values of my weatherstation and enriched the layout just with not known weather data from the weather provider.

I would like to have this feature in OH2 as well. The temperature of my weatherstation differs slightly from the temperature of wondergroud. On the other hand, I have no UV index sensor, which I would take from the weather privider. So the layout should give the possibility to mix values.

**Comment by staehler** [comment]
Closed and reopend in openhab/openhab2-addons, sorry.

**Comment by watou** [comment]
This binding feature was removed before 1.8.3. openhab2-addons isn't the correct repo to report this.  I suggest looking to HABPanel as a potential UI for weather layouts.
