### ISSUE TITLE
Callmonitor is giving status "NULL", all other items working

### ISSUE THREAD

**Issue by rrutk** [openhab/openhab1-addons#5120]

**Comment by 9037568** [comment]
Please provide your configuration information (items, sitemap, rules, etc.) and upload a debug log.

**Comment by rrutk** [comment]
Items: see above.

Just using the items in a template:

1.

<font color="#00BFFF"><strong>Status Festnetz Ausgehend</strong></font>  
<br></br>
	<tr>
      <td>
        Anruf:
        <font color="#00BFFF"><strong>{{itemValue('fboxRinging_Out')}}</strong></font>  
		  </td>    
  </tr>
  <br>
  <tr>
      <td>
        Nummer:
        <font color="#00BFFF"><strong>{{itemValue('fboxOutgoingCall')}}</strong></font> 
      </td>   
  </tr>  

2.

<font color="#00BFFF"><strong>Status Festnetz Eingehend</strong></font>  
<br></br>
<tr>
      <td>
        Anruf:
        <font color="#00BFFF"><strong>{{itemValue('fboxRinging')}}</strong></font>  
		  </td>    
  </tr>
  <br>
  <tr>
      <td>
        Nummer:
        <font color="#00BFFF"><strong>{{itemValue('fboxIncomingCall')}}</strong></font> 

      </td>   
  </tr>  
  <br>
  <tr>
      <td>
        Name:
        <font color="#00BFFF"><strong>{{itemValue('fboxIncomingCallResolved')}}</strong></font>
      </td>   
  </tr>

**Comment by 9037568** [comment]
I'd suggest starting a discussion thread in the [community forum.](http://community.openhab.org)

Someone there may be able to help fixing the configuration.
