### ISSUE TITLE
Zooz Z-Wave Plus On/Off Toggle Switch

### ISSUE THREAD

**Issue by cristhiampaul** [openhab/openhab1-addons#5124]
I really like to add this device to the repositories, but i dont know how to.

Manufacturer: Zooz
Model: Zen21

Link zwave database : [http://products.z-wavealliance.org/products/2058](http://products.z-wavealliance.org/products/2058)

Thanks a lot

**Comment by cdjackson** [comment]
Is it in the openhab database at www.cd-jackson.com?

**Comment by cristhiampaul** [comment]
No, It isn´t.

**Comment by cdjackson** [comment]
Please follow the instructions on the site - specifically http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide. This will allow creation of the data required.

**Comment by cristhiampaul** [comment]
Ok, I`m registered but I have not permission to edit or add new data.

**Comment by cdjackson** [comment]
I’ve updated your access, so you should be good to go…

Cheers
Chris

**Comment by cristhiampaul** [comment]
Hi, I already created the data of the device, how can I update my OH2 with the export XML file ?
thx

**Comment by cdjackson** [comment]
You need to now update the binding. So you need to export the XML from the database and create a PR with this, and also the modified products.xml file. The OH1 export from the database should show this, but you might need to modify things slightly if the manufacturer already exists in the products file.

**Comment by cristhiampaul** [comment]
Done!! now? Sorry for the lot of question, iam very noob.

**Comment by cdjackson** [comment]
No problem, and thanks for doing this.

Cheers
Chris
