### ISSUE TITLE
Diyxbee  binding  issues on OpenHab2

### ISSUE THREAD

**Issue by amarpulli544** [openhab/openhab1-addons#5129]
Hello,

I am trying to use Openhab1  diyonxbee  addon on Openhab2 running on windows 7, but it has below issues . 

I created jar of diyonxbee which can be [downloaded ]
(https://drive.google.com/file/d/0ByTiOU2W3nyZaHNURUl4S2ZySTA/view?usp=sharing). 

I placed this jar file addons folder of Openhab2.

When I run the openhab2  server,  I get below errors.

```
19:37:25.250 [ERROR] [.core.internal.folder.FolderObserver] - Error handling upd
ate of file 'D:\XBEE_H~1\NEWFOL~1\conf\things\demo.things': UID must have at lea
st 3 segments..
java.lang.IllegalArgumentException: UID must have at least 3 segments.
        at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:65)
        at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:43)
        at org.eclipse.smarthome.core.thing.ThingUID.<init>(ThingUID.java:139)
        at org.eclipse.smarthome.model.thing.internal.GenericThingProvider.const

```

I also check the status of binding using Karaf Console

```
 9 | Active   |  80 | 1.10.0.201703011753   | openHAB DiyOnXBee Binding
10 | Active   |  80 | 2.0.0.b2              | openHAB Serial Transport Bundle
```
Here is my Item Configuration file:

`Switch  Living_Motion           "Bewegung [MAP(de.map):%s]"     <present>       (GF_Living,GPresence)   { diyonxbee="<0013A20040E7782D:MOTION" }`

My Thing Configuration file:

```
diyonxbee:serialPort=COM3                                                                               
     diyonxbee:baudRate=9600
```

I think serial device is not recognized by openhab2, also thing definition doesn't work on openhab2.

Please help me to work this binding on Openhab2.

Thanks.

**Comment by watou** [comment]
There are no Things for openHAB 1.x bindings.  Please see documentation for this binding [here](http://docs.openhab.org/addons/bindings/diyonxbee1/readme.html).  

You can download a nightly build of the binding [here](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.diyonxbee/target/org.openhab.binding.diyonxbee-1.10.0-SNAPSHOT.jar).

Please use the [Community Forum](https://community.openhab.org) for further questions.  Thanks!
