### ISSUE TITLE
Alarmdecoder Items not refreshing correctly in realtime on openHAB's basicUI site

### ISSUE THREAD

**Issue by ashishgupt** [openhab/openhab1-addons#5149]
I have installed openhabian on RaspberryPi and using the beginner's guide setup a site which I can access from a browser as well as openHAB app on my Android phone. I have also setup AD2PI. I installed AlarmDecoder binding through Addons and updated alarmdecoder.cfg to connect via tcp. Then I added the following lines to my alarmdecoder.items file:

String Display "panel display: [%s]" { alarmdecoder="KPM:00#text" }
Number StatusReady  "panel ready: [%d]"  { alarmdecoder="KPM:00#status,bit=17" }

And I finally added these lines to my default.sitemap:
Text item=Display
Text item=StatusReady

If I launch openHAB app on my Android phone, I see the correct values for both the items but the values don't update unless I reload the site. What am I missing?

**Comment by 9037568** [comment]
This sounds like an Android problem. You should try asking this question in the [community forum](http://community.openhab.org).

**Comment by ashishgupt** [comment]
I tried accessing the site through basicUI as well and the result was the
same. I added items corresponding to the status of my phone and Yamaha
receiver (online/offline) and their status got updated on the site (basicUI
as well as openHAB's app on Android)  instantaneously. Looks like that the
refresh issue is only with Alarmdecoder.

**Comment by 9037568** [comment]
Ok. Which version of OH and which version of the binding?

**Comment by 9037568** [comment]
Also, please include a debug log showing the failure.

**Comment by ashishgupt** [comment]
OH version: openHAB 2.0.0-1 (Release Build)
I installed binding-alarmdecoder1 - 1.9.0 through PaperUI --> Addons
Where can I find the debug log?

**Comment by ashishgupt** [comment]
I rebooted my Pi and then everything started refreshing fine. :-)
