### ISSUE TITLE
[astro] events after UTC Midnight missed.

### ISSUE THREAD

**Issue by mckaymatthew** [openhab/openhab1-addons#5157]
When an astro event such as civilDusk occurs after Midnight UTC, the event never "fires". The nightly Midnight UTC job is rescheduling the next event before the current event has transpired. The end result is scheduled events do not fire.

## Expected Behavior
Expected behavior is that the Astro Binding will fire scheduled events. 

## Current Behavior
Current behavior is that the astro job recalculates sunset time and looses information on the about-to-happen event. If you examine this log you can see a few things. 
```2017-04-01 00:00:00 - Sunset_Time state updated to 2017-04-02T00:39:00
2017-04-01 00:00:00 - Sunrise_Time state updated to 2017-04-01T11:20:00
2017-04-02 00:00:00 - Sunset_Time state updated to 2017-04-03T00:40:00
2017-04-02 00:00:00 - Sunrise_Time state updated to 2017-04-02T11:18:00
```

- On 04-01 at Midnight UTC a Sunset is calculated to be on the 04-02 at 00:39, a few minutes after midnight UTC. 
- On 04-02 at Midnight UTC a new sunset is calculated for "today", even though the sunset calculated on 04-01 (That is going to happen in 39 minutes) hasn't yet happened. I believe this is causing the event to never "fire".

## Possible Solution

- Change java args to change default JVM timezone (Untested)
- Add and then use astro:timezone parameter to .cfg file 
- When finding sunsets (or sunrises), find the next nearest sunrise rather than the sunrise on a specific day. 

## Context
I am in the United States Central Timezone, which is currently a 7 hour difference from UTC. This means that Midnight UTC is approximately the time of sunset at my location.
My system time is correct, my system timezone is correct:
```
pi@raspberrypi:/var/log/openhab $ strings /etc/localtime | tail -n 1
CST6CDT,M3.2.0,M11.1.0
pi@raspberrypi:/var/log/openhab $ date
Sun  2 Apr 13:12:39 CDT 2017
```

## Your Environment
Version: OpenHab 1.8.3

**Comment by mckaymatthew** [comment]
I wrote a community post about this a few days ago: https://community.openhab.org/t/astro-civildusk-event-not-firing/24959

**Comment by 9037568** [comment]
Can you provide a debug log for this?
