### ISSUE TITLE
Nibe heatpump problem

### ISSUE THREAD

**Issue by palsbo** [openhab/openhab1-addons#5168]
I have been working on the nibe heatpump binding for some time  but with limited success.

I modified the Arduino nibegw to work with ESP8266, at this works. The communication with the heatpump (VVM310) is running without the heatpump going into error (I have enabled modbus in the service menue), and I get packages which are send to the openHab2 server on udp port 9999;

The first problem is, that the packages seems to be wrong. All packages look the same like this:
```
Sending UDP packet, len=86
5C 00 20 68 50 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 18
```

I expected to see somthing more exiting than FF FF 00 00 !!

Next I am unsure about the configuration

I the file nibeheatpump.cfg I have one line like this:

`nibeheatpump:udpPort=9999`

```
In the items file *I have defined the times like this:
Number N47333 "Cooling supply temp at 40C [%.1f]" {nibeheatpump="47333"}
Number N47334 "Cooling close mixing valves [%.1f]" {nibeheatpump="47334"}
Number N47335 "Time between switch heat/cooling [%.1f]" {nibeheatpump="47335"}
Number N47329 "Cooling 2-pipe accessory [%.1f]" {nibeheatpump="47329"}
Number N47330 "Cooling 4-pipe accessory [%.1f]" {nibeheatpump="47330"}
Number N47331 "Min cooling supply temp [%.1f]" {nibeheatpump="47331"}
Number N47340 "Cooling with room sensor [%.1f]" {nibeheatpump="47340"}

... continuing with all numbers in the list

int the sitemap file I have the following:
`	Frame label="Nibe" {
		Text item=N47332
		Text item=N47333
		Text item=N47334
		Text item=N47335
		Text item=N47329
		Text item=N47330
		Text item=N47331
`
... continuing with all numbers in the list

Based on the received packages, I am not surprised not seeing any values in the list!!!

Any help is appreciated.

Tnx in advance

**Comment by paulianttila** [comment]
Packet send by the Nibe heat pump is ok. You just haven't configured you pump to send any data. Download Nibe Modbus 40 ModbusManager application to create configuration file (LOG.SET) and transferred file via usb memory stick to pump. See more details from Nibe Modbus 40 manual (google Nibe Modbus 40 ModbusManager).

Btw, better ask help from the openhab forum (https://community.openhab.org) rather than create issue.

**Comment by palsbo** [comment]
Thank you. this was the answer I was missing.

**Comment by Orteppi** [comment]
Is it possible to have the code for ESP8266?
I have tried to make it run, but my skills are limited with the ESP programming.
Thank You in advance!

**Comment by Hotfire1978** [comment]
Is it possible to have the code for ESP8266?
