### ISSUE TITLE
[Weather Binding] OpenWeatherMap doesn't give windspeed in km/h as default.

### ISSUE THREAD

**Issue by JueBag** [openhab/openhab1-addons#5172]
Using the weather binding the windspeed is expected to be reported in km/h as default.

When selecting OpenWeatherMap as provider the reported windspeed value (Setting Default) is the same  value OpenWeatherMap shows on ist webpage with the unit m/s! In the API documentation of OpenWeatherMap windspeed is listed as reported in m/s.

The use of any of the transformations build into the binding (for example windspeed in Beaufort) will return false values.

**Comment by cweitkamp** [comment]
Find PR here: #5180

**Comment by 9037568** [comment]
Closed via merged PR.
