### ISSUE TITLE
[Enocean] Add EEP A5:04:02 - Tipp-Radio TF-FTSB humidity temperature  sensor 

### ISSUE THREAD

**Issue by VanHogan** [openhab/openhab1-addons#5174]
Please add Enocean EEP A5:04:02 for Tipp-Radio TF-FTSB  humidity temperature  sensor.

[TF-FTSB_30000507-1_gb.pdf](https://github.com/openhab/openhab1-addons/files/959798/TF-FTSB_30000507-1_gb.pdf)

**Comment by fruggy83** [comment]
This EEP is already implemented in the v2 binding.
