### ISSUE TITLE
Change IP of an TCP/UDP in a rule

### ISSUE THREAD

**Issue by Chanete** [openhab/openhab1-addons#5178]
Hi, is it possible to change the ip of an already defined connection?

I'll explain the need. I'm using DHCP for the arduinos that have the reles of my home automation system. Every time an arduino boots, it gets its IP from DHCP and inmediatly sends an UDP packet to the server advertising it's new IP. 

I've created  a switch like this 
`Switch Garden  [ "Lighting" ] {udp=">[ON:192.168.1.80:8888:MAP(jardin.map)], >[OFF:192.168.1.80:8888:MAP(jardin.map)]"} `    

So I need to change the IP from a rule when I received the arduino init packet I'll need to do something like this (but this doesn't work!) 

`Garden.state.remote="/192.168.1.79:8888"`

is there any way to accomplish this? 

Thx
Chano

**Comment by 9037568** [comment]
The best way: Don't use DHCP.

If you want additional ideas, you should try posting in the [community forum](http;//community.openhab.org/).

**Comment by Chanete** [comment]
Well, that's not exactly the answer I was expecting! 

Of course that's a perfect solution, but implies reflashing the arduinos with the new code. This could be easy if my arduinos where installed on simple places (or if they have OTA capablities, but they don't),  but I have them installed inside  the conection box in the wall and, most of them, have been painted after I installed them so my wifw will kill me if I reopen the box.. 

That's why I was searching for a "software" solution.

**Comment by cdjackson** [comment]
Many DHCP servers provide the option to hardcode an address based on the Mac address. So your Arduino can still use DHCP, but the DHCP server might be able to be configured to always provide the same address. That's what I use here.

**Comment by Chanete** [comment]
That's a great idea!. I0m gonna check if my router has that feature and, if not, I'll install dhcpd server in my openhab machine. 

Thx!
