### ISSUE TITLE
Weather binding: Yahoo not providing data for forecast wind

### ISSUE THREAD

**Issue by gnalbandian** [openhab/openhab1-addons#5182]
All my items are defined like this:
`Number Wind_Speed0 "Windspeed [%.2f km/h]"		<wind> 			{ weather="locationId=Home, forecast=0, type=wind, property=speed" }
Number Wind_Speed1 "Windspeed [%.2f km/h]"		<wind> 			{ weather="locationId=Home, forecast=1, type=wind, property=speed" }
Number Wind_Speed2 "Windspeed [%.2f km/h]"		<wind> 			{ weather="locationId=Home, forecast=2, type=wind, property=speed" }
Number Wind_Speed3 "Windspeed [%.2f km/h]"		<wind> 			{ weather="locationId=Home, forecast=3, type=wind, property=speed" }
Number Wind_Speed4 "Windspeed [%.2f km/h]"		<wind> 			{ weather="locationId=Home, forecast=4, type=wind, property=speed" }
Number Wind_Speed5 "Windspeed [%.2f km/h]"		<wind> 			{ weather="locationId=Home, forecast=5, type=wind, property=speed" }
Number Wind_Speed6 "Windspeed [%.2f km/h]"		<wind> 			{ weather="locationId=Home, forecast=6, type=wind, property=speed" }`

But items state is not beoing recalled:

`Wind_Speed0 (Type=NumberItem, State=UNDEF, Label=Windspeed, Category=wind)
Wind_Speed1 (Type=NumberItem, State=UNDEF, Label=Windspeed, Category=wind)
Wind_Speed2 (Type=NumberItem, State=UNDEF, Label=Windspeed, Category=wind)
Wind_Speed3 (Type=NumberItem, State=UNDEF, Label=Windspeed, Category=wind)
Wind_Speed4 (Type=NumberItem, State=UNDEF, Label=Windspeed, Category=wind)
Wind_Speed5 (Type=NumberItem, State=UNDEF, Label=Windspeed, Category=wind)
Wind_Speed6 (Type=NumberItem, State=UNDEF, Label=Windspeed, Category=wind)
`

I am using Raspbian and OpenHAB 2 Build #903

**Comment by 9037568** [comment]
If you're using OH2, odds are you're using the [Yahoo binding](https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.yahooweather) that's built into [ESH](http://docs.openhab.org/addons/bindings.html).

You should check the [community forum](http://community.openhab.org/) to see if anyone else is having issues with this. If not, you probably have a configuration error which can be corrected.
