### ISSUE TITLE
[weather] Meteoblue not working with non commercial api key

### ISSUE THREAD

**Issue by schnidrig** [openhab/openhab1-addons#5185]
## Expected Behavior

The binding should work with non commercial offer of meteo blue (basic-day package)

## Current Behavior

the binding uses a request that is not supported with the non commercial api key.

## Possible Solution

use the basic-day url instead. 
e.g. http://my.meteoblue.com/packages/basic-day?name=Basel&lat=47.5584&lon=7.57327&asl=279&tz=Europe%2FZurich&apikey=xxxxxxxxxx&temperature=C&windspeed=kmh&winddirection=degree&precipitationamount=mm&timeformat=iso8601&format=json
 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

openhab 2.1 with 1.10-Snapshot of weather binding.

**Comment by pgruetter** [comment]
Just wanted to open the same issue, got the same problem. Would love to see meteoblue working as they give the most precise forecasts for my location.

**Comment by schnidrig** [comment]
I changed the url in the binding and tested the non commercial api. It's not really usable since there are not enough data of interest. Giving up....

**Comment by 9037568** [comment]
@schnidrig I've just posted a [WIP version of a MeteoBlue binding](https://github.com/eclipse/smarthome/pull/4821) for ESH/OH2 that uses the NonCommercial API.

**Comment by 9037568** [comment]
The ESH meteoblue binding should be available in the next release.

There are no plans to change the OH1 binding.
