### ISSUE TITLE
[Weather] UnknownHostException needs to be explicitly handled in AbstractWeatherProvider

### ISSUE THREAD

**Issue by jimduchek** [openhab/openhab1-addons#5188]
It appears that any exception in the web request essentially shuts down the scheduler.  I don't think this is necessarily terrible behavior if there's a config problem, but certain exceptions need to be explicitly handled and treated as lesser errors because they are recoverable.  I suspect java.net.NoRouteToHost would need to be handled as well.  

Specifically, I am on a highly unreliable link (using OpenHab in an RV, actually).  Currently, if any attempt to fetch the weather fails, the weather bundle must be restarted.

**Comment by 9037568** [comment]
Please provide a debug log that shows the scenario you're speaking of.

**Comment by jimduchek** [comment]
Ugh, going to close this issue.  Not sure what happened.  I have logs from last night where it's clear that it was never recovering after the exception, but I was mucking about with other things at the same time.  Cannot reproduce today.  Perhaps I had something else broken.
