### ISSUE TITLE
[Weather] Lookup Wunderground by station ID

### ISSUE THREAD

**Issue by McLive** [openhab/openhab1-addons#5198]
Since wunderground API calls to an latitude and longitude always return the wrong station I'd like to request the data by station ID.

Maybe an config option like this:
#location.locationId1.stationID=

And when that is set then the API URL will be like this:
http://api.wunderground.com/api/[API_KEY]/conditions/forecast10day/lang:[LANGUAGE]/q/pws:[STATION].json

**Comment by mojoaxel** [comment]
There is already a `woeid` which is used for the yahoo provider. Maybe we could use this?

**Comment by 9037568** [comment]
The Weather Underground API is being retired/ended.
