### ISSUE TITLE
openhab 1.8.3 create action issue

### ISSUE THREAD

**Issue by Mtwbs** [openhab/openhab1-addons#5200]
follow https://github.com/openhab/openhab1-addons/wiki/How-To-Implement-An-Action
create action to Fifth point in cmd mvn enter archetype:generate
result
![image](https://cloud.githubusercontent.com/assets/28838838/26397239/39b5fba2-40a8-11e7-94ec-b94561b6a004.png)

I have  question in the results can not choose the words of action

**Comment by 9037568** [comment]
You need to post this question in the [community forum](http://community.openhab.org/).
