### ISSUE TITLE
[pushover] action logs an error message which isn't a real error

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab1-addons#5201]
Since around a couple of days the Pushover action logs an error which isn't a real error message only an info message. They maybe changes something in their API. The response now contains an `<info>` tag.

Related community thread:
[https://community.openhab.org/t/problems-with-pushover-binding/28950](https://community.openhab.org/t/problems-with-pushover-binding/28950)

openhab.log
```
2017-05-25 12:32:16.347 [ERROR] [ab.action.pushover.internal.Pushover] - Received error message from Pushover: <?xml version="1.0" encoding="UTF-8"?>
<response>
  <info>no active devices to send to</info>
  <status>1</status>
  <request>1d2c94f1-c6d3-4b57-97c3-650c9e0bb425</request>
</response>
```

**Comment by 9037568** [comment]
Please provide a debug log so that we can see the raw response that's being parsed.

You should see "Raw response: " in the output.

**Comment by cweitkamp** [comment]
@sihui62 One second faster than me ... ;-)

As additional info: I currently have no active devices, so the `<info>` tag has a meaning. Maybe it should be logged from the action as a warning as well.
```
2017-05-25 16:09:31.667 [DEBUG] [ab.action.pushover.internal.Pushover] - Executing post to https://api.pushover.net/1/messages.xml with the following content: token=acoabr2m19buy33gpttx6xzd9176da&user=u45yi3pnz21qbbrddyo7e264qm5r5m&message=Pushover+Test&title=openHAB&priority=0
2017-05-25 16:09:32.359 [DEBUG] [ab.action.pushover.internal.Pushover] - Raw response: <?xml version="1.0" encoding="UTF-8"?>
<response>
  <info>no active devices to send to</info>
  <status>1</status>
  <request>b7a1f2c8-7352-4e3e-9389-cfeb7af1a41a</request>
</response>

2017-05-25 16:09:32.370 [ERROR] [ab.action.pushover.internal.Pushover] - Received error message from Pushover: <?xml version="1.0" encoding="UTF-8"?>
<response>
  <info>no active devices to send to</info>
  <status>1</status>
  <request>b7a1f2c8-7352-4e3e-9389-cfeb7af1a41a</request>
</response>
```

**Comment by 9037568** [comment]
So it appears that this is pushover indicating that the call openhab made to the pushover api was successful, but that no devices existed to send to.

Does everyone agree that this is the case? Does everyone agree that OH should log a WARN with the contents of the "info" element of the response in this situation?

**Comment by cweitkamp** [comment]
No and Yes. Just for clarification - the binding currently always logs an error even if the call to the pushover api was successful. The other users reported so. The `<info>` tag appears only in my case. I think it is an improvement if the binding logs a warning if an` <info>` tag is returned.

**Comment by cweitkamp** [comment]
PR #5216
