### ISSUE TITLE
[snmp] Memory Leak

### ISSUE THREAD

**Issue by sconwayaus** [openhab/openhab1-addons#5202]
## Expected Behaviour
Openhab runs continuously for longer than 72Hrs...

## Current Behaviour
Java Out of Memory events in log, timeouts etc... Openhab generally doesn't work.

## My Solution
After looking at the heap dump I found a hashtable `asyncRequests` in SNMP4J that was leaking. Adding some test code calling `Snmp.getPendingAsyncRequestCount()` confirmed that the hashtable was increasing (not to mention the heap was forever getting bigger).

Looking at
[http://www.snmp4j.org/doc/org/snmp4j/Snmp.html](http://www.snmp4j.org/doc/org/snmp4j/Snmp.html)
calling `snmp.cancel()` in the listener callback `onResponse()` is required or you end up with a memory leak. The openhab binding doesn't call this method. I've implemented the below snippet to org.openhab.binding.snmp.internal.SnmpBinding and works for me.

```
    /**
     * Called when a response from a GET is received
     *
     * @see org.snmp4j.event.ResponseListener#onResponse(org.snmp4j.event.ResponseEvent )
     */
    @Override
    public void onResponse(ResponseEvent event) {
        // Always cancel async request when response has been received
        // otherwise a memory leak is created! Not canceling a request
        // immediately can be useful when sending a request to a broadcast
        // address.
        ((Snmp) event.getSource()).cancel(event.getRequest(), this);

        dispatchPdu(event.getPeerAddress(), event.getResponse());
    }
```

Confirmed using 'Snmp.getPendingAsyncRequestCount()`, and monitoring the heap size (sitting at a more reasonable 40Mb).

I haven't run this for more than an hour, but this plugs a big leak in the binding.

## Steps to Reproduce (for bugs)
1. Setup SNMP binding, add 12 SNMP OID's, polling at a rate of 5sec.
2. Run the system for 1-3days, Out of Memory Exceptions are thrown in the log.

## Context
Everyone wants a stable platform :)

## Your Environment
Raspberry Pi, openhabian.

```
>                           __  _____    ____
>   ____  ____  ___  ____  / / / /   |  / __ )
>  / __ \/ __ \/ _ \/ __ \/ /_/ / /| | / __  |
> / /_/ / /_/ /  __/ / / / __  / ___ |/ /_/ /
> \____/ .___/\___/_/ /_/_/ /_/_/  |_/_____/
>     /_/                        2.0.0
>                                Release Build
> 
> Hit '<tab>' for a list of available commands
> and '[cmd] --help' for help on a specific command.
> Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.
> 
> openhab> info
> Karaf
>   Karaf version               4.0.8
>   Karaf home                  /usr/share/openhab2/runtime
>   Karaf base                  /var/lib/openhab2
>   OSGi Framework              org.eclipse.osgi-3.10.101.v20150820-1432
> 
> JVM
>   Java Virtual Machine        Java HotSpot(TM) Client VM version 25.131-b11
>   Version                     1.8.0_131
>   Vendor                      Oracle Corporation
>   Pid                         13515
>   Uptime                      5 minutes
>   Total compile time          29.399 seconds
> Threads
>   Live threads                131
>   Daemon threads              70
>   Peak                        276
>   Total started               1704
> Memory
>   Current heap size           42,178 kbytes
>   Maximum heap size           241,536 kbytes
>   Committed heap size         87,084 kbytes
>   Pending objects             0
>   Garbage collector           Name = 'Copy', Collections = 88, Time = 3.406 seconds
>   Garbage collector           Name = 'MarkSweepCompact', Collections = 6, Time = 3.259 seconds
> Classes
>   Current classes loaded      13,323
>   Total classes loaded        13,414
>   Total classes unloaded      91
> Operating system
>   Name                        Linux version 4.9.24-v7+
>   Architecture                arm
>   Processors                  4
```

**Comment by martinvw** [comment]
Great that you fixed it, can you also make a pull request for this?

Do not forget to include a `Signed-off-by` (to certify that you wrote it or otherwise have the right to pass it on as an open-source), see http://docs.openhab.org/developers/contributing/contributing.html#sign-your-work

**Comment by sconwayaus** [comment]
Done, but not sure I did this right.

Pull request here: [https://github.com/openhab/openhab1-addons/pull/5208](https://github.com/openhab/openhab1-addons/pull/5208)

**Comment by martinvw** [comment]
It looks good (Y)

**Comment by martinvw** [comment]
I believe you should be able to close it yourself

**Comment by sconwayaus** [comment]
No problem. 

Cheers
