### ISSUE TITLE
Question only - how to implement ventilation mode key press simulation

### ISSUE THREAD

**Issue by linuxlurak** [openhab/openhab1-addons#5204]
Hi Holger

I control my ca350 over an esp-01<->rs232toTTL-chip (transparent serial bridge) with a simple python script. I wan't to implement a routine to set de ventilation mode (in or out or inANDout). 

CCEase goes off with displaying "AC"  when i connect the RX cable of my RS232toTTL chip. I am planning of creating a pcb with a CD4066B chip to switch my RX line an the RX line of the ca350.

When I send the command to press the ventilation-mode button (the small house with arrows) I'll get a response from ca350 that does not include the change of the mode itself. As soon as i connect the CCEase the display gets updated. So there is the need of a working communication path with the CCEase remote.

Can you confirm this situation/problem? 

Do you know about a command to request the state of the symbols on the CCEase display? Or the response of the CCEase that is sent to the ca350 after it received the command to change the vent mode?

I know the command to change the vent mode ('\x07\xF0\x00\x37\x07\x00\x01\x00\x00\x00\x00\x03\xEF\x07\x0F'). What's the necessary communication between CCEase and the ca350? There seems to be some messages that the ca350 is waiting for since when I send the above command it takes at least a second and the ca350 sends data. This data seems to bee the same just till i reconnect the CCEasy for a short time. Usually the ca350 responses in under a second.

I think the function to set the ventilation mode is a crucial point of having a ca350 included in any home automation system.

I hope you can find a spare minute to lead me to the right direction. Thank you very much for this public source. It inspired me a lot.

**Comment by 9037568** [comment]
Questions should go to the [community forum.](http://community.openhab.org/)
