### ISSUE TITLE
[fritzboxtr064] feature request: add items for DSL statistics to monitor connection quality

### ISSUE THREAD

**Issue by tensberg** [openhab/openhab1-addons#5221]
I'm interested in monitoring the (lousy) quality of my DSL connection using OpenHAB. The fritzboxtr064 binding is a great starting point for this as the [FritzBox TR064 interface](https://avm.de/service/schnittstellen/) offers the statistics I am interested in in the "[WAN Statistiken](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wancommonifconfigSCPD.pdf)" and "[DSL Informationen](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wandslifconfigSCPD.pdf)" interfaces.

I'd like to have (at least) the following statistics as items:
* WAN
  * physical link status
  * total bytes sent
  * total bytes received
* DSL
  * upstream current/max
  * downstream current/max
  * FEC errors
  * CRC errors

With these items one can create graphs of the connection quality and perhaps trigger warnings if they drop too low.

I have already implemented this as a prototype (https://github.com/tensberg/openhab1-addons/tree/5221-fritzboxtr064_dsl_statistics). If there is general interest in this feature, I can polish up my changes and submit a pull request.

**Comment by nmesstorff** [comment]
@tensberg looks very interesting - would use it!
It may also useful to collect the items "Störabstandsmarge" and "Leitungsdämpfung" if it is easy to get those statistics.

I could test it with my 7390 if needed.

**Comment by tensberg** [comment]
Nice to know you're interested. Störabstandsmarge (upstream/downstream noise margin) and Leitungsdämpfung (upstream/downstream attenuation) is also available in the FritzBox TR-064 API, so I can add them too.

I won't have time to work on this feature in the next few weeks, but will do it later and submit a pull request.

**Comment by tensberg** [comment]
I finally got around to polish my changes and submit a pull request for this feature.

While my changes the ["Works On My Machine"](https://blog.codinghorror.com/the-works-on-my-machine-certification-program/) certification, I would be happy to see others test the updated binding. I've been using it for the last few weeks, but I think it would be important to test it with other FritzBoxen and other configurations.

I also added the items for noise margin and attenuation, but they currently report the values in dB*10 as this is the way the FritzBox SOAP service returns it. (e. g. it shows an attenuation of 500 instead of 50). Since fixing this would require another larger code change, I'd open another issue for it if it is a problem.

**Comment by cniweb** [comment]
@tensberg I would use it, too!
But I can only test on a fritz box 6590 cable.
Do you support cable statistic, too?

**Comment by tensberg** [comment]
> Do you support cable statistic, too?

The AVM docs of the interface I used only mention DSL, but I can't find anything else about cable in the other docs either. I guess you could try out if it works with your cable FritzBox once it is implemented, and if it doesn't work create an enhancement request and I'll have another look at it.

**Comment by 9037568** [comment]
Closed via merged PR #5295
