### ISSUE TITLE
[CalDav] Username and password shouldn't be required for public calendars

### ISSUE THREAD

**Issue by carlholmberg** [openhab/openhab1-addons#5229]
If the calendar that is being used is public than the CalDav add-ons should not require username and password being set.

## Expected Behavior
When using a calendar that does not require login the add-on should not throw a ConfigurationException but connect without credentials.

## Current Behavior
When connecting to a public CalDav calendar (published through Apple Calendar) without username and password set the add-on throws a ConfigurationException. If username and password is included Sardine throws a SardineException with Unexpected response (401 - Unauthorized ).

## Possible Solution
1. Do not require username and password in config (comment out lines 210-215 in CalDavLoaderImpl.java)
2. Add configuration caldavio:<cal-id>:isPublic=<bool> (default True)

## Context
When trying to set up scheduling of switches through Apple Calendar (published through iCloud) CalDav add-on won't connect. To have to use another calendar-provider seems an unnecessary step if the fix is trivial.

## Your Environment
openHabian on RPI 3
openHab 2.0.0-1 (Release build)

**Comment by 9037568** [comment]
I thought we already had this.

Here's lines [209-218 of CalDavLoaderImpl](https://github.com/openhab/openhab1-addons/blob/master/bundles/io/org.openhab.io.caldav/src/main/java/org/openhab/io/caldav/internal/CalDavLoaderImpl.java#L209), which has nothing to do with usernames and passwords...

````
            } else if (paramKey.equals(PROP_DISABLE_CERTIFICATE_VERIFICATION)) {
                calDavConfig.setDisableCertificateVerification(BooleanUtils.toBoolean(value));
            } else if (paramKey.equals(PROP_CHARSET)) {
                try {
                    Charset.forName(value);
                    calDavConfig.setCharset(value);
                } catch (UnsupportedCharsetException e) {
                    log.warn("Character set not valid: {}", value);
                }
            }
````

If you still think this is an issue, please drop OH into TRACE mode and provide the log output.

**Comment by carlholmberg** [comment]
I checked again and the version of CalDav i have is installed via PaperUI and is 1.9.0. The corresponding lines in that release is (line 206-214):
`                if (configMap.get(id).getUrl() == null) {
                    throw new ConfigurationException(PROP_URL, PROP_URL + " must be set");
                }
                if (configMap.get(id).getUsername() == null) {
                    throw new ConfigurationException(PROP_USERNAME, PROP_USERNAME + " must be set");
                }
                if (configMap.get(id).getPassword() == null) {
                    throw new ConfigurationException(PROP_PASSWORD, PROP_PASSWORD + " must be set");
                }
 `
Hence the error I get. Is it possible to use current master of CalDav without building the add-on myself or is a new release planned soon?

**Comment by 9037568** [comment]
Haven't heard any news on timelines for new packaged releases, sorry. Try asking @kaikreuzer in the community forum.

There's probably a way to take the latest caldav jar from [cloudbees](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/org.openhab.binding$org.openhab.binding.caldav-command/) and get it working in your setup, too.
