### ISSUE TITLE
Z-wave device not in database Qubino Flush shutter

### ISSUE THREAD

**Issue by juchstrasse** [openhab/openhab1-addons#5231]
1.  Device not in Database:  Z-Wave Node 13 (0159:0003:0002:1.12) 
2.  Type: Qubino Flush shutter
3.  P/N: ZNMHCA2 H1S2P1
4.

OpenHab 2.1 stable 
Z-Wave binding 2.1.0

**Comment by cdjackson** [comment]
Information on adding devices to the database can be found here -:
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

Please use this as a guide to adding devices.

Note that this is the OH1 issue tracker - as you are using OH2 it's not relevant here in any case.
