### ISSUE TITLE
[MQTT] MQTT Binding wont communicate with mosquitto after upgrade to OH2.1

### ISSUE THREAD

**Issue by vuhams** [openhab/openhab1-addons#5233]
## Expected Behavior
MQTT Communication between Mosquitto Broker

## Current Behavior
MQTT is working excellent in OH2.0 bit it is not working after upgraded to OH2.1
I Un-Installed and installed MQTT binding once again, and checked all the configurations in mqtt.cfg
But, unsucessfull

## Possible Solution
Compatibility issue i think

## Your Environment
Raspberry 3 Model B, installed OpenHABian

**Comment by 9037568** [comment]
Sounds like you're using OH2, so I'm guessing you're also using the OH2/ESH version of MQTT.

You should check the [community forum](http://community.openhab.org) to see if anyone else is seeing this issue.
