### ISSUE TITLE
denon binding in openhab 2.x - no feedback from device

### ISSUE THREAD

**Issue by HaKuNaCH** [openhab/openhab1-addons#5250]
The items from the binding are generally working, but I got no feedback when the items are changed on the receiver itself, means the status, e.g.
Switch DenonPowerMain "Power Denon" { denon = "avr2000#ZM" }
is only changed when I switch it via the openhab GUI or app.
## Expected Behavior
Item state should be updated also when changed directly on the receiver

## Current Behavior
Item state is only updated when changed via openhab GUI or app.

## Possible Solution
-

## Steps to Reproduce (for bugs)
1. power off / on directly on the receiver
2. power on / off via WebGUI or app
3. check event.log

## Context
visibility usage in sitemap does not work as expected

## Your Environment

Version used: 2.2.0 SNAPSHOT
Denon Binding: binding-denon1 - 1.11.0.SNAPSHOT
CentOS 7

see also:
https://github.com/openhab/openhab-distro/issues/481

**Comment by 9037568** [comment]
Please attach a debug log and your configurations (items/rules/sitemap).

**Comment by HaKuNaCH** [comment]
[denon_debug.txt](https://github.com/openhab/openhab1-addons/files/1149060/denon_debug.txt)
[meinHaus.items.txt](https://github.com/openhab/openhab1-addons/files/1149065/meinHaus.items.txt)
[meinHaus.sitemap.txt](https://github.com/openhab/openhab1-addons/files/1149066/meinHaus.sitemap.txt)

In rules I have no denon related definitions.

**Comment by 9037568** [comment]
The log is pretty thin. This line is interesting, but I'm not sure it has anything to do with anything:

````
2017-07-14 18:24:55.169 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=312, bundle=185/mvn:org.openhab.binding/org.openhab.binding.denon/1.11.0-SNAPSHOT]: Unexpected problem updating configuration org.openhab.denon
````

**Comment by 9037568** [comment]
If you want to try dropping the binding into TRACE mode, we might get more information.

**Comment by HaKuNaCH** [comment]
[TRACE.txt](https://github.com/openhab/openhab1-addons/files/1153483/TRACE.txt)
I added the whole log after a restart of the openhab service.

**Comment by 9037568** [comment]
It appears that OH isn't happy with the secondary zone's master volume value:

````
2017-07-17 19:32:57.194 [TRACE] [inding.denon.internal.DenonConnector] - result of getDocument for uri 'http://10.0.1.7:80/goform/formZone2_Zone2XmlStatusLite.xml':
<?xml version="1.0" encoding="utf-8" ?>
<item>
<Power><value>OFF</value></Power>
<InputFuncSelect><value>SOURCE</value></InputFuncSelect>
<VolumeDisplay><value>Absolute</value></VolumeDisplay>
<MasterVolume><value>  0</value></MasterVolume>
<Mute><value>off</value></Mute>
</item>

[...]
java.lang.NullPointerException
	at java.math.BigDecimal.compareTo(BigDecimal.java:2625)[:1.8.0_131]
	at org.openhab.core.library.types.PercentType.validateValue(PercentType.java:47)[192:org.openhab.core.compat1x:2.2.0.201707122217]
	at org.openhab.core.library.types.PercentType.<init>(PercentType.java:43)[192:org.openhab.core.compat1x:2.2.0.201707122217]
	at org.openhab.binding.denon.internal.DenonConnector.updateSecondaryZones(DenonConnector.java:470)[185:org.openhab.binding.denon:1.11.0.201707150110]

````

Here's a [test jar](https://drive.google.com/open?id=0B8vYheWfObP9aXo2VTE4ZG9BZk0) that adds some null pointer protection around the value.

**Comment by HaKuNaCH** [comment]
Hi
Still the same.
I put the jar in /var/lib/openhab2/tmp/mvn/org/openhab/binding/org.openhab.binding.denon/1.11.0-SNAPSHOT and restarted openhab2 service.
But the jar you provided looks like the same which is already in the directory.
Do I missunderstood something ?

**Comment by 9037568** [comment]
Great to hear. I'll submit a PR.
