### ISSUE TITLE
SNMP binding documentation is outdated / undocumented feature

### ISSUE THREAD

**Issue by jboeddeker** [openhab/openhab1-addons#5251]
I was experimenting with the SNMP binding and discovered the documentation is a bit outdated:

https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.snmp/README.md

At least in my install of openHAB 2.1 i am able to bind string items to SNMP as well.
This item definition properly shows the port description of my TP-Link SG3424 switch.
(IP Adress replaced with x.x.x.x)

`String switch1p17name "switch1 port 17 [%s]" <ethernet> (gswitch1) { snmp="<[x.x.x.x:public:.1.3.6.1.4.1.11863.1.1.3.2.1.1.1.1.2.17:10000]" }`

The binding supports setting values via switch items and displaying values for Number or String items. I wasn't able to set a value using a string item.

**Comment by 9037568** [comment]
Yes, Switch, Number, or String. Looks like it's been that way a long time, too.
Not sure how the readme never got updated.
