### ISSUE TITLE
http binding POST body not correct

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab1-addons#5253]
As described in https://community.openhab.org/t/http-binding-post-does-not-work-as-expected/31673, the http binding does not work as described in http://docs.openhab.org/addons/bindings/http1/readme.html 

## Expected Behavior

http request should set the body of POST either to ON/OFF or to the MAPped value.

## Current Behavior

http request sets the body of POST to the string, defined in item definition, regardless of the key word "default" or the special function "MAP(mappingfile.map)".

## Steps to Reproduce (for bugs)

see in community https://community.openhab.org/t/http-binding-post-does-not-work-as-expected/31673

This bug also works (at least) with String items, I did not make further tests.

## Your Environment
* xen VM
* debian stretch 64bit as host
* java: Oracle Java Runtime 8.131
* OH2 : 2.2.0 Build #986

**Comment by 9037568** [comment]
I believe this fix is ready.

I have created a [test jar](https://drive.google.com/open?id=0B8vYheWfObP9SGMxUFJ6RXE0aUU) from the [code changes](https://github.com/9037568/openhab/compare/http) in my fork.  It appears to be in good shape, but please test it rigorously.
