### ISSUE TITLE
vagrant not working 

### ISSUE THREAD

**Issue by aryeharmon** [openhab/openhab1-addons#5257]
error while following the [guide](https://github.com/openhab/openhab1-addons/wiki/IDE-Setup) to create a development environment with vagrant 

when trying to vagrant up:
Failed to connect to www.noobles.info port 443: Connection refused

**Comment by 9037568** [comment]
This would have nothing to do with OpenHAB.

You could try asking for help in the [community forum](http://community.openhab.org/), in case anyone else using this vagrant setup might be able to help.
