### ISSUE TITLE
[anel] Support for anel hut 6.1

### ISSUE THREAD

**Issue by yveshanoulle** [openhab/openhab1-addons#5262]
## Expected Behavior
As an owner of an anel hut, I want to upgrade my anel HUT to 6.1 and OpenHab be able to still talk to it.
Preferable also using the newly added features for dimmers (the Hold On functionality)
(And to make it explicit, I would want it to support Anel hut 6.0 and 6.1 at the same time, so I can test the now no longer working 6.1 before I upgrade all my hut's to 6.1) 

## Current Behavior
After an upgrade of an anel Hut to 6.1, OpenHab can no longer talk to it.

## Possible Solution
The new api is described here https://anel-elektronik.de/forum_neu/viewtopic.php?f=16&t=207

## Steps to Reproduce (for bugs)
upgrade an anel hut to 6.1

## Your Environment
I had this problem with openhab 2.0 and OpenHab 2.1
(and as this is because of an upgrade of Anel hut, I suspect this problem exists in OpenHab 1.x also.

**Comment by paphko** [comment]
Thank you @yveshanoulle for this detailed feature request. Issue #3068 already added support for Firmware 6.0, so we should also add support for 6.1.  The link already explains the extension of the protocol compared to the older versions and it seems to be straight forward to at least make the current functionality available with the new version. 

Actually, we should change the code to also allow future extensions of the protocol, by not relying on the data package length anymore but just check that at least the expected values are transferred.

**Comment by yveshanoulle** [comment]
that is strange. I have a few anel hut's 6.0 that do work with OpenHab.

**Comment by paphko** [comment]
Pull request: #5264

**Comment by yveshanoulle** [comment]
That's a fast fix. 
Looking from the code, I guess this will work with both 6.0 and 6.1 huts. so I will try to upgrade my openhab when this is available and let you know if it works.
