### ISSUE TITLE
Maven build is failing due to homematic binding (checkstyle)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab1-addons#5268]
```
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.0.6:checkstyle (default) on project org.openhab.binding.homematic: Unable to execute mojo: An error has occurred in Checkstyle report generation. Failed during checkstyle configuration: Exception was thrown while processing D:\dev\openhab2\git\openhab\bundles\binding\org.openhab.binding.homematic\META-INF\MANIFEST.MF: -1 -> [Help 1]
[ERROR]
```

**Comment by kaikreuzer** [comment]
@svilenvul The build [uses the setting](https://github.com/openhab/openhab1-addons/blob/master/pom.xml#L55)
```
<report.fail.on.error>false</report.fail.on.error>
```
Do you know why the build is failing nonetheless?

**Comment by svilenvul** [comment]
Hmm, this looks like an exception thrown from some of the checks - I will find it at it and fix it.

**Comment by 9037568** [comment]
So, looks like this was fixed in the static-code-analysis repo, and this can be closed?

**Comment by svilenvul** [comment]
The change is merged, but it will be included in the next release of the tool.
