### ISSUE TITLE
[MailControl] Errors when saving changes to mailcontrol.cfg 

### ISSUE THREAD

**Issue by MartinK8** [openhab/openhab1-addons#5276]
Hello,

I was trying to get this binding to work and couldn't so any help is appreciated.
## Expected Behavior
MailControl binding should be a useful and simple binding to use whit which you can send commands to your openhab via email.

## Current Behavior
At the moment what I  experiencing is what I suppose is a bug. Everytime i try to save my mailcontrol.cfg file an error appears in the logs.
[log.txt](https://github.com/openhab/openhab1-addons/files/1215027/log.txt)

````
[ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService, id=296, bundle=186/file:/C:/Users/martin.krandarov/Downloads/openhab-2.1.0/addons/org.openhab.binding.mailcontrol-1.11.0-SNAPSHOT.jar]: Unexpected problem updating configuration org.openhab.mailcontrol
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/creek/accessemail/connector/mail/MailConnector.getPop3Store()Ljavax/mail/Store; @31: invokevirtual
  Reason:
    Type 'com/sun/mail/pop3/POP3SSLStore' (current frame, stack[0]) is not assignable to 'javax/mail/Store'
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'org/creek/accessemail/connector/mail/MailConnector', 'javax/mail/URLName', 'javax/mail/Session', 'com/sun/mail/pop3/POP3SSLStore' }
    stack: { 'com/sun/mail/pop3/POP3SSLStore' }
  Bytecode:
    0x0000000: 2ab4 0004 b600 514c 2ab4 0004 b600 1601
    0x0000010: b800 174d bb00 1859 2c2b b700 194e 2db6
    0x0000020: 0052 2db0                              

	at org.openhab.binding.mailcontrol.connection.ConnectorBuilder.createAndCheckMailConnector(ConnectorBuilder.java:55)
	at org.openhab.binding.mailcontrol.internal.MailControlBinding.updated(MailControlBinding.java:107)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1772)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]

````

## Possible Solution
I am not a programmer so I can't follow the error to its roots and thus can't fix it myself. I am not certain that it is a software mistake it may be on my side as well.

## Steps to Reproduce (for bugs)
1. Build openhab1-addons with maven
2. Put mailcontrol in addons folder
3. Put all the dependancy .jar files in the runtime/lib/ext(not sure if this is the right thing to do but otherwise i get this
[log2.txt](https://github.com/openhab/openhab1-addons/files/1215094/log2.txt))

## Context
This prevents the addon from working properly.

## Your Environment
OpenHAB 2.1.0
mailcontrol-1.11.0
Windows 10

**Comment by 9037568** [comment]
That's odd behaviour.  It appears [updated()](https://github.com/openhab/openhab1-addons/blob/db62be70e9cd9561036d8925a177a2e37aaa4bd4/bundles/binding/org.openhab.binding.mailcontrol/src/main/java/org/openhab/binding/mailcontrol/internal/MailControlBinding.java#L107) is getting called before the config file has been properly saved.

It looks like we could remove this line without ill effects. Care to try out a [test jar](https://drive.google.com/open?id=0B8vYheWfObP9UkhRUTRrdV9jUUk)?

**Comment by 9037568** [comment]
This shouldn't, by the by, prevent the addon from working. You should be able to shut down OH, change the config file, and restart.  The addon should then work normally.

**Comment by MartinK8** [comment]
The .jar you linked does solve the problem with saving the .cfg file.

**Comment by 9037568** [comment]
Did you try shutting down OH and checking the config file is correct, then restarting OH?

If so, please show the mailcontrol.cfg.

**Comment by MartinK8** [comment]
I did try it during OH wasn't on but when i turned it on i got the error i showed you earlier.
[log.txt](https://github.com/openhab/openhab1-addons/files/1217738/log.txt)

**Comment by 9037568** [comment]
Try this.
Shut down OH, then search the `userdata/etc` and `userdata/cache` folders for cached copies of the config file.
Move any you find to a temp folder outside of the OH hierarchy.
Then restart OH.

**Comment by MartinK8** [comment]
Couldn't find anything resembling mailcontrol.cfg

**Comment by 9037568** [comment]
I'm unable to reproduce this behaviour.
