### ISSUE TITLE
ComfoAirBinding feature request: more command types 

### ISSUE THREAD

**Issue by mhrnr** [openhab/openhab1-addons#5284]
Not all command types are implemented in current ComfoAirBinding (see protocol description http://www.see-solutions.de/sonstiges/Protokollbeschreibung_ComfoAir.pdf). For example I successfully added and tested the following command types:

    INCOMMING_FAN_RPM {
		{
			key = "incomming_fan_rpm";
			data_type = DataTypeNumber.class;
			read_command = 0x0b;
			read_reply_command = 0x0c;
			read_reply_data_pos = new int[] { 2, 3 };
		}
	},

	OUTGOING_FAN_RPM {
		{
			key = "outgoing_fan_rpm";
			data_type = DataTypeNumber.class;
			read_command = 0x0b;
			read_reply_command = 0x0c;
			read_reply_data_pos = new int[] { 4, 5 };
		}
	},
	
	PRE_HEAT_RUNNING {
		{
			key = "pre_heat_running";
			data_type = DataTypeNumber.class;
			read_command = 0xdd;
			read_reply_command = 0xde;
			read_reply_data_pos = new int[] { 11, 12 };
		}
	},
	
	PRE_HEAT_STATUS {
		{
			key = "pre_heat_status";
			data_type = DataTypeNumber.class;
			read_command = 0xe1;
			read_reply_command = 0xe2;
			read_reply_data_pos = new int[] { 0 };
		}
	},
	
	PRE_HEAT_FROST_PROT {
		{
			key = "pre_heat_frost_prot";
			data_type = DataTypeNumber.class;
			read_command = 0xe1;
			read_reply_command = 0xe2;
			read_reply_data_pos = new int[] { 1 };
		}
	},
	
	PRE_HEAT {
		{
			key = "pre_heat";
			data_type = DataTypeNumber.class;
			read_command = 0xe1;
			read_reply_command = 0xe2;
			read_reply_data_pos = new int[] { 2 };
		}
	},
	
	PRE_HEAT_FROST_MINUTES {
		{
			key = "pre_heat_frost_minutes";
			data_type = DataTypeNumber.class;
			read_command = 0xe1;
			read_reply_command = 0xe2;
			read_reply_data_pos = new int[] { 3, 4 };
		}
	},
	
	PRE_HEAT_FROST_SAFETY {
		{
			key = "pre_heat_frost_safety";
			data_type = DataTypeNumber.class;
			read_command = 0xe1;
			read_reply_command = 0xe2;
			read_reply_data_pos = new int[] { 5 };
		}
	},
	
	BYPASS_RUNNING {
		{
			key = "bypass_running";
			data_type = DataTypeNumber.class;
			read_command = 0xdd;
			read_reply_command = 0xde;
			read_reply_data_pos = new int[] { 13, 14 };
		}
	},

	FROST_PROT_RUNNING {
		{
			key = "frost_prot_running";
			data_type = DataTypeNumber.class;
			read_command = 0xdd;
			read_reply_command = 0xde;
			read_reply_data_pos = new int[] { 9, 10 };
		}
	},
	
	FAN_LEVEL_A_RUNNING {
		{
			key = "fan_level_a_running";
			data_type = DataTypeNumber.class;
			read_command = 0xdd;
			read_reply_command = 0xde;
			read_reply_data_pos = new int[] { 0, 1, 2 };
		}
	},
	
	FAN_LEVEL_1_RUNNING {
		{
			key = "fan_level_1_running";
			data_type = DataTypeNumber.class;
			read_command = 0xdd;
			read_reply_command = 0xde;
			read_reply_data_pos = new int[] { 3, 4, 5 };
		}
	},
	
	FAN_LEVEL_2_RUNNING {
		{
			key = "fan_level_2_running";
			data_type = DataTypeNumber.class;
			read_command = 0xdd;
			read_reply_command = 0xde;
			read_reply_data_pos = new int[] { 6, 7, 8 };
		}
	},
	
	FAN_LEVEL_3_RUNNING {
		{
			key = "fan_level_3_running";
			data_type = DataTypeNumber.class;
			read_command = 0xdd;
			read_reply_command = 0xde;
			read_reply_data_pos = new int[] { 17, 18, 19 };
		}
	}

**Comment by Nobiuss** [comment]
Hi, this is not what you are looking for, i have it for my confod350. Realy happy about it!!

http://www.knxlogic.eu/product/comfoway/

**Comment by bechte** [comment]
These enhancements have already been added to the repository. So I wonder why this issue is still open? I recommend to close it...

**Comment by 9037568** [comment]
This repository is closed to new code anyway, so I agree...
