### ISSUE TITLE
[HABDroid] different username for local and for remote access

### ISSUE THREAD

**Issue by dakipro** [openhab/openhab1-addons#5289]
## Expected Behavior

Having two set of fields for local and remote credentials.

## Current Behavior

 When accessing openhab that requires username and password from a local network a credentials are required. Same goes for when using remote access for openhab (via myopenhab.org f.eks)
However, currently there is only one set of fields for credential, requiring that local and remote credentials are the same. That complicates things even more with multiple users for single openhab instance. 

## Possible Solution

Separate login fields for local and remote access. F.eks. Having two extra login and password fields for remote access.

## Steps to Reproduce (for bugs)

1. Set local credentials for openhab as required
2. login to openhab via myopenhab.org remote service
3.
4.

## Context

This will increase security in case someone gets on the local network, the username for openhab is required. Today almost only easy solution is to have local access is without authentication. 

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by kaikreuzer** [comment]
Issue tracker for HABDroid is at https://github.com/openhab/openhab.android/issues.
