### ISSUE TITLE
[MySQL] misleading WARN Message

### ISSUE THREAD

**Issue by BrutalBirdie** [openhab/openhab1-addons#5291]
```shell
12:40:30.760 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'tmp.sitemap'
12:40:32.371 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
12:40:32.481 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
12:40:32.616 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
12:40:32.738 [INFO ] [ui.habmin.internal.servlet.HABminApp] - Started HABmin servlet at /habmin
12:40:32.815 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
12:40:32.879 [DEBUG] [org.openhab.persistence.mysql       ] - BundleEvent STARTING - org.openhab.persistence.mysql
12:40:32.881 [DEBUG] [nal.MysqlPersistenceServiceActivator] - mySQL persistence bundle has been started.
12:40:32.889 [DEBUG] [org.openhab.persistence.mysql       ] - BundleEvent STARTED - org.openhab.persistence.mysql
12:40:32.895 [WARN ] [sql.internal.MysqlPersistenceService] - The SQL database URL is missing - please configure the sql:url parameter in openhab.cfg
12:40:33.065 [DEBUG] [org.openhab.persistence.mysql       ] - ServiceEvent REGISTERED - {org.openhab.core.persistence.P
ersistenceService}={component.name=org.openhab.persistence.mysql, component.id=206, service.id=329, service.bundleid=21
0, service.scope=bundle} - org.openhab.persistence.mysql
12:40:33.083 [INFO ] [b.core.service.AbstractActiveService] - Modbus Polling Service has been started
```
12:40:32.895 [WARN ] [sql.internal.MysqlPersistenceService] - The SQL database URL is missing - please configure the sql:url parameter in openhab.cfg

This may confuse users. Because if they read the Docs http://docs.openhab.org/addons/persistence/mysql/readme.html#configuration
> This service can be configured in the file services/mysql.cfg

Also when trying to follow the instruction and adding to openhab.cfg it is still wrong
> sql:url=jdbc:mysql://127.0.0.1/openhab

it needs to be 
> mysql:url=jdbc:mysql://127.0.0.1/openhab

Also when only using services/mysql.cfg for MySQL it does not work at all.

MySQL Binding Version
> 210 | Active   |  80 | 1.10.0                 | openHAB mySQL Persistence bundle

openHAB Version
> 2.1.0

**Comment by 9037568** [comment]
I've updated the warnings.

Note, however, that when using OH2, the name of the setting should not be `mysql:url`, but just `url`.

**Comment by BrutalBirdie** [comment]
> Note, however, that when using OH2, the name of the setting should not be mysql:url, but just url
I tried that. And when using url= it did not work.
