### ISSUE TITLE
Problem: Items do not get new values

### ISSUE THREAD

**Issue by raisude** [openhab/openhab1-addons#5298]
In the past I have opened two issues for the netatmo binding. My Problem is, that the netatmo items do not get new values after some time. After starting they all get new values. Sometimes they all stop getting new values. Sometimes the amount of the items get less untill there is no one left.

I have some mqtt items which refresh all the time. Sometime at start of the openhab service i get warnings about the map tranformation or the openhabcloud or sometimes mqtt doesn`t start.

Also at the start i get a warning about my netamto.things file. Validation error using it anyway ... .

the content is:

// Bridge configuration:
Bridge netatmo:netatmoapi:91cfef78 "Netatmo API" [ clientId="right one not published here", clientSecret="right one not published here", username = "right one not published here", password = "right one not published here", readStation=true,$
    // Thing configuration:
    Thing netatmo:NAMain:91cfef78:70ee502100ea "Via per le Prandine"  [ equipmentId="70:ee:50:21:00:ea" ]
    Thing netatmo:NAModule1:91cfef78:02000020c68e "Außenmodul"  [ equipmentId="02:00:00:20:c6:8e", parentId="70:ee:50:21:00:ea"]
    Thing netatmo:NAModule4:91cfef78:0300000476f4 "Poolraum"  [ equipmentId="03:00:00:04:76:f4", parentId="70:ee:50:21:00:ea"]
    Thing netatmo:NAModule3:91cfef78:0500000351c8 "Regensensor"  [ equipmentId="05:00:00:03:51:c8", parentId="70:ee:50:21:00:ea"]
    Thing netatmo:NAModule2:91cfef78:060000023106 "Windmesser"  [ equipmentId="06:00:00:02:31:06", parentId="70:ee:50:21:00:ea"]
}

Where i have to look for to solve the problem. The netatmo binding or openhab?

Regards Rainer

**Comment by 9037568** [comment]
You'll need to ask this question in the [community forum](http://community.openhab.org/).

When you do, make sure to include details such as
- java version
- os version
- openhab version
- binding version
- errors observed
- debug log
