### ISSUE TITLE
[FritzboxTr064] Feature Request: Support DECT switch

### ISSUE THREAD

**Issue by cniweb** [openhab/openhab1-addons#5303]
Support DECT Switch, please.

For example:
`Switch fboxDECT "DECT" {fritzboxtr064="dectSwitch"} `

Thanks,
Chris

**Comment by jwsp1** [comment]
Unfortunately, the old FritzBox binding doesn't work for me anymore so I had to switch to tr064 but I desperately miss DECT Switch support... Any update on development?

**Comment by 9037568** [comment]
The update is there is no further development in OH1.
There will eventually be an [updated binding](https://github.com/openhab/openhab-addons/pull/6678) for OH2/3.

**Comment by J-N-K** [comment]
What excatly is this with doing? Switching "DECT/Basisstation/Basistation aktiv" (I used the german labellling, I have no other FB available, I think you can translate it)? I didn't find the corresponding TR-064 action in the documentation.
