### ISSUE TITLE
[weather1] Request: add support for the free version of forecasts for OpenWeatherMap

### ISSUE THREAD

**Issue by dominikkv** [openhab/openhab1-addons#5309]
Wrong url for weather forecast request for OpenWeatherMap. There is no "daily" in the url, see documentation https://openweathermap.org/forecast5

## Expected Behavior
Working forecast for OpenWeatherMap (http://docs.openhab.org/addons/bindings/weather1/readme.html#forecast)

## Current Behavior
Forecast is broken, see karaf log:
```
13:16:22.182 [TRACE] [nal.provider.AbstractWeatherProvider] - OPENWEATHERMAP[openweather]: request : http://api.openweathermap.org/data/2.5/forecast/daily?lat=48.xxx&lon=7.yyy&lang=de&cnt=5&mode=json&units=metric&APPID=123notthateasy
13:16:22.239 [TRACE] [nal.provider.AbstractWeatherProvider] - OPENWEATHERMAP[openweather]: response: {"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}
13:16:22.239 [ERROR] [nal.provider.AbstractWeatherProvider] - OPENWEATHERMAP[openweather]: Can't retreive weather data: HTTP/1.1 401 Unauthorized
```

## Possible Solution
See merge request https://github.com/openhab/openhab1-addons/pull/5308

## Steps to Reproduce (for bugs)
1. Install binding weather1
2. Create /conf/services/weather.cfg with appropriate content like:
```
apikey.OpenWeatherMap=123456789

location.openweather.name=Openweather
location.openweather.latitude=48.xxxx
location.openweather.longitude=7.yyyy
location.openweather.provider=OpenWeatherMap
location.openweather.language=de
location.openweather.updateInterval=10
location.openweather.units=si
```
3. Add any weather item 
4. Open karaf console, set trace level: `log:set TRACE org.openhab.binding.weather`
5. After 10 minutes, see log entries above

## Your Environment
* Version used: openhab2, openhab-binding-weather1 1.10.0
* Operating System and version: Docker image openhab/openhab:2.1.0-amd64 hosted on an Ubuntu 17.04

**Comment by 9037568** [comment]
The error you're getting is because you're using an invalid API key. There's nothing wrong with the binding.

And the forecast URL certainly does have 'daily' in the path. [See here](http://openweathermap.org/forecast16#16days).

**Comment by dominikkv** [comment]
OK, there are indeed 2 API endpoints
- The 5 days forecast (without "daily" in url)
- The 16 days forecast (with "daily" in url)

The problem is that the 16 day forecast is **not** included in the free plan, that's the reason why I'm getting the "Unauthorized" message.

So the question is if this is intended. The [documentation of this addon](http://docs.openhab.org/addons/bindings/weather1/readme.html#forecast) says that forecast is possible for `OpenWeatherMap: 5 days (0-4)`. Furthermore, I think it is good when also non paying users can use this addon.

If this is not intended we have to figure out how to change addon to use the 5 days forecast. I see now that simply removing the "daily" from the url is not sufficient, because the result will not be divided in days, but in 3-hour blocks.

What do you think?

(Additional info: the API access key is correct, the call to get the current weather works fine)

**Comment by 9037568** [comment]
Ok. That is indeed a different thing. I've changed the title accordingly.

**Comment by felixloesch** [comment]
The bug is still there. No forecast possible with OpenWeatherMap.

**Comment by tobiasisenberg** [comment]
I notice the same issue. Could this be fixed somehow?

**Comment by 9037568** [comment]
There's an [ESH binding](https://github.com/eclipse/smarthome/pull/5694) for OWM in development.

**Comment by mjansing** [comment]
Any updates on this? It would be great if it's possible to use free OpenWeatherMap-API with weather1 binding. What about a toggle for free and paid more detailed forecast?

**Comment by cweitkamp** [comment]
No, not yet (see https://github.com/openhab/openhab1-addons/pull/5344#issuecomment-340749803). It cannot be implemented without reaching a decision on the following questions.

> I would love to see a working forecast for OWM provider to be part of this binding. Even better without anyone has to pay for it.
>
> I agree, that it should be configurable for the user which version he wants to use. But that is not simply possible by switching the URLs.
>
> If you have a closer look at the API documentation of OWM you will see that the 5 day API provides weather data for every 3 hours. We have to adopt that in the binding too. Currently the binding parses every result set as a separate day. Meaning that you will currently see the weather data for the next 3 hours as forecast for tomorrow, the weather data for the next 6 hours as forecast for the day after tomorrow, and so on.
>
>How do you think can we archive that? Should we skip the result sets for the next 3, 6, ..., 21 hours and use the result set for the next 24 hours as forecast for tomorrow, skip 27, 30, ..., 45 hours again and use the result set of 48 hours as forecast for the day after tomorrow, and so on? Wdyt? This could end in a forecast which could change every few hours.
>
> Another approach could be to use a specific time of the day (e.g. 12 o'clock) as forecast.
>
> A third approach could be to break the general logic of the binding to return 3 hours forecast instead of daily forecast (especially if you're using OWM, but maybe other provider support other forecast options as well).

**Comment by staehler** [comment]
Please update your docu accordingly. I freshly have requested an API key and run into the same problem. Just wasted my time :-(

**Comment by chemical1979** [comment]
I also walked straight into this issue one hour ago. As I'm doing the first steps with openHAB i was confused by getting values to the items I took from the documentation (they get values, see below) by at the same time getting an invalid API key error.

openHAB/userdata/logs/events.log
2018-11-07 22:27:12.962 [vent.ItemStateChangedEvent] - Temperature changed from UNDEF to 13.65
2018-11-07 22:27:12.968 [vent.ItemStateChangedEvent] - Humidity changed from UNDEF to 66.00

openHAB/userdata/logs/openhab.log
2018-11-07 22:27:12.960 [ERROR] [nal.provider.AbstractWeatherProvider] - OPENWEATHERMAP[home]: Can't retreive weather data: Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.

**Comment by cweitkamp** [comment]
All,

Just a short heads-up: I will not come up with a solution for this. We now have a dedicated [OpenWeatherMap binding](https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.openweathermap) available in the ESH / OH2 distribution. I recommend you to use the new binding if you like to fetch data of the free 5 day / 3 hour forecast.

> Please update your docu accordingly.

@staehler Feel free to add it to the documentation and contribute.

@9037568 Shall we consider to close this issue?

**Comment by kgooris** [comment]
This new binding is not available in my installation openhab 2.3.0-1 (stable)
How can I add it, without having to move my installation to a unstable testing openhab installation?

**Comment by 9037568** [comment]
> @9037568 Shall we consider to close this issue?

Agreed.

**Comment by cweitkamp** [comment]
> When will it become available in stable version?

@kgooris In the next release version (OH 2.4). I do not know an exact release date for it yet.

**Comment by MrTheBarbarian** [comment]
Hello!
Could you please specify where is the addon folder on Linux for OH2. Is it : /usr/share/openhab2/addons ? Because in this folder I have two files: openhab-addons-2.3.0.kar & openhab-addons-legacy-2.3.0.kar 
Is it the right place where I have to put this file?
Thanks!

**Comment by AngelosF** [comment]
@MrTheBarbarian : yes, that's the correct location
by the way: It's better to use the forum for this kind of questions.
Also: You don't really need openhab-addons-2.3.0.kar & openhab-addons-legacy-2.3.0.kar
You can remove them from your addons folder (optional)

**Comment by Trysupe** [comment]
> For installation, first uninstall weather-binding via paperui and copy the jar to your addons folder.
do I have to do anything else? I unistalled the weather1 binding, put the jar into the folder and rebootet but the paper ui doesn't show the binding
