### ISSUE TITLE
[config] filter setting/del not written in /var/lib path

### ISSUE THREAD

**Issue by AlexPoeltl** [openhab/openhab1-addons#5320]
Deleting the filter value in /etc/openhab2/services/gcal.cfg won't delete a present value in "/var/lib/openhab2/config/org/openhab/gcal.config".

This only happens by changing from a setup filter to none filter / empty string.

--
openhab2, gcal 1.10.0
(basic setup openhabianpi)

**Comment by 9037568** [comment]
That's how the shadow cache works. 

And that code doesn't reside here, anyway.
