### ISSUE TITLE
[Z-Wave] Commands are not send to Z-Wave Device (Garage Door Controller)

### ISSUE THREAD

**Issue by jomojomo95** [openhab/openhab1-addons#5322]
## Expected Behavior
I try to trigger a switch in the control section of Paper UI.
The switch should open / close the garagedoor.

## Current Behavior
The Aeon Garage Door Controller is not triggerd and the console gives following error:

> Item zwave_device_c6bcd2a7_node5_switch_binary updated: OFF
>  Ignoring update for zwave_device_c6bcd2a7_node5_switch_binary, because update was probably triggered through UI.

## Context
I tried a new created Item but the new item doesnt work either.
If I manully open / close the door i get the State of it so it seems openhab can recive but not send commands to the Z-Wave Device.

## Your Environment
Openhab2 on Raspberry Pi 3, PaperUi and Habmin, Aeon Z-Wave Stick Gen5, 2* Aeon Garage Door Controller

**Comment by cdjackson** [comment]
I would suggest to discuss on the forum as there will be more people to help you. Also, this is the OH1 issue list and you seem to be using OH2 so closing here.

**Comment by jomojomo95** [comment]
Sorry came here via link and didnt notice this was OH1, will try my luck on the forum.
Thanks
