### ISSUE TITLE
Sitemap Setpoint of Virtual Item shows no or random values (from other Setpoints)

### ISSUE THREAD

**Issue by gruenwaldt** [openhab/openhab1-addons#5326]
## Expected Behavior

```
Setpoint item=Arbeitszimmer_Temperature_Set label="Tagestemperatur" icon="heating" minValue=5 maxValue=25 step=0.5
```

Should display following:
```
[Icon] Tagestemperatur [-]20,00 °C[+]
```

## Current Behavior

Actually it displays the folowing:
```
[Icon] Tagestemperatur [-][+]
```

OR!
```
[Icon] Tagestemperatur [-]17,00 °C[+]
```

Where 17,00 is a value, displayed in one of the other Setpoint entries.

## Steps to Reproduce (for bugs)
1. The item above is a virtual item in PaperUI but an item like `Number Arbeitszimmer_OpenWindowWarnMinutes` from an virtual.items file has the same problem

## Your Environment
* Version used: OpenHAB 2

iOS App is working like expected, so i think this is a bug. 
Thank you in advance
Regards
Michael Grünwaldt

**Comment by 9037568** [comment]
This is the repository for OH1 Addons. This defect would be coming from some lower level. Suggest you try the community forum first.
