### ISSUE TITLE
[dynamodb] Instructions for completing the validation for inclusion in the openHAB2 distribution

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab1-addons#5334]
The [Persistence docs](http://docs.openhab.org/addons/persistence.html) say that:
> Some openHAB 1 persistence services have not yet completed validation for inclusion in the distribution; however, they may indeed work properly under openHAB 2.

How to complete this validation in practice?

I have personally tested the version in PR #5333 quickly using openHAB2, and it seems to work fine... Is there more guidance on the testing? I wonder why so many persistence services have been left out from the distribution?

Should I as the dynamodb addon developer move this addon to use smarthome packages? I notice that all (?) persistence addons still rely on compat layer?

## Context

Community discussion re missing persistence services 
https://community.openhab.org/t/amazon-dynamodb-persistence-binding-not-in-the-addons-download/17616/2?u=ssalonen

Also mentioned here: https://community.openhab.org/t/new-amazon-dynamodb-persistence-addon-alpha-experimental/9856

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by 9037568** [comment]
I'm not clear on where these would migrate _to_. OH2 addons or ESH?

**Comment by ssalonen** [comment]
Thanks for the reply! I think I used a bit wrong wording... There are two topics as addon developer which are unclear to me:
- what should I do to "complete the validation" for getting this persistence addon as part of openHAB2 distribution?
- this persistence bundle (as all other persistence bundles in openHAB1-addons) do not use smarthome packages, and thus need the openHAB1 compatibility layer to be installed? If it would use smarthome packages, it indeed would make sense to move this somewhere else.

From my perspective it would be OK to move this to even ESH, I think the licenses should be clear for the actual addon code. Naturally there are the dependencies in lib with different license.

**Comment by 9037568** [comment]
I don't know the answers to these questions. I think we need input from someone better connected, like @kaikreuzer or @watou.

**Comment by kaikreuzer** [comment]
Hi @ssalonen, I guess this is the info you are looking for: http://docs.openhab.org/developers/development/compatibilitylayer.html#how-to-add-a-successfully-tested-1x-add-on-to-the-distribution

**Comment by ssalonen** [comment]
@kaikreuzer thanks! So in order to "complete the validation" I should follow the steps to create
- Karaf feature
- add some meta information

I'm still having a bit hard time to understand everything so bear with me :)

Adding a karaf feature seems simple enough, there are many persistence services having this already. However, I found only single openHAB1 persistence service with parameters defined with xml, [jdbc](https://github.com/openhab/openhab1-addons/blob/master/bundles/persistence/org.openhab.persistence.jdbc/ESH-INF/config/config.xml). This addon has the parameters defined in ESH-INF/config/config.xml.

The documentation talks about creating ESH-INF/binding/binding.xml and references [XML Structure for Binding Definitions](https://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html#xml-structure-for-binding-definitions) in ESH docs. This was my problem before, _binding_ is well documented but not so much persistence. So should I really create ESH-INF/binding/binding.xml even for persistence addons, or should I follow jdbc example and create ESH-INF/config/config.xml?

Taking jdbc as example, I can also see [some other parameters](https://github.com/openhab/openhab1-addons/blob/master/bundles/persistence/org.openhab.persistence.jdbc/OSGI-INF/jdbc.xml#L19-L21) under OSGI-INF, `service.config.*`. Should those be added?

Sorry for the simple questions and if these are answered somewhere. Please just point the docs if the info is somewhere but I can't just find it...

**Comment by ssalonen** [comment]
I'm still lacking information, really appreciate any pointers where to find more information.

**Comment by 9037568** [comment]
Afraid I don't have any additional input on that. Perhaps @kaikreuzer or @sjka can share the knowledge.

**Comment by ssalonen** [comment]
Discussed also here: https://community.openhab.org/t/new-amazon-dynamodb-persistence-addon-alpha-experimental/9856

It's been now 23 days since last reply. I hope that there is a way to progress this, so it would be easier for the users to take the addon into use.

Still not clear what are the necessary steps to get the addon included in openHAB2 distribution, see my [comments above](https://github.com/openhab/openhab1-addons/issues/5334#issuecomment-347615473).

**Comment by kaikreuzer** [comment]
> binding is well documented but not so much persistence. 

Yes, sorry, you are right.
So the best advice is indeed to do it in the same way as it is done for JDBC:
- create a config.xml that describes the parameters (if any) that should appear in the Paper UI for configuring the service
- add `service.config.*` properties in the OSGI DS component XML that reference the config description (it is matched by the given uri)

**Comment by ssalonen** [comment]
Thank you very much! I think I have all I need for now. I will submit a PR for dynamodb persistence. With the experiences from that I can contribute and improve the docs.

**Comment by ssalonen** [comment]
Hmm, can't seem to get this to work. Actually, I also have trouble with JDBC.

This is how JDBC looks with openHAB2.2. I installed it from Paper UI.

![image](https://user-images.githubusercontent.com/315866/35114526-c5d28942-fc8d-11e7-807c-5cfcfac5cf01.png)

So no sign of parameters even though they are clearly in the codebase. Perhaps due to `ESH-INF` missing in [build.properties](https://github.com/openhab/openhab1-addons/blob/master/bundles/persistence/org.openhab.persistence.jdbc/build.properties)? Is this a bug?

The DynamoDB persistence I have been working on looks better (branch: https://github.com/ssalonen/openhab1-addons/commits/dynamodb-esh-compat ):

![image](https://user-images.githubusercontent.com/315866/35114604-f9130f0c-fc8d-11e7-9c99-eb324c09c589.png)

## Problem 1
However, when I change the parameters, the PersistenceService is not deactivated/activated (can be easily confirmed using debugger, for example). Interestingly, I can see that the internal config cache (?) at `userdata/config/org/openhab/persistence/dynamodb.config` gets updated instantly.

## Problem 2

When I restart the bundle with `bundle:restart NNN`, the binding gets deactivated/activated as it should. However, there is another issue: the `Map<String, Object> config` passed to [`activate`](https://github.com/ssalonen/openhab1-addons/blob/dynamodb-esh-compat/bundles/persistence/org.openhab.persistence.dynamodb/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java#L90) does not have the actual configuration parameters, only some other properties. From the debugger:

```
{service.config.category=persistence, service.config.label=Amazon DynamoDB Persistence, component.name=org.openhab.persistence.dynamodb, component.id=228, service.config.description.uri=persistence:dynamodb}
```

I tried enabling verbose logging but no leads why OSGI is not working as expected... According to [this article](http://enroute.osgi.org/services/org.osgi.service.component.html) "Configurations can be updated dynamically. Without any extra effort, this will mean your component gets shot down and then recreated with the latest configuration data.".

What am I missing? Sorry to ping you again @kaikreuzer :)

**Comment by ssalonen** [comment]
Anyone? Really would value any hints to proceed.

**Comment by ssalonen** [comment]
Update (with openHAB 2.3 stable): it seems that the above Problems 1 & 2 were both caused by the OSGI configuration. Fixed by removing `immediate="true"` and `configuration-policy="optional"`, leaving only:
```xml
<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.2.0" activate="activate"
deactivate="deactivate"
name="org.openhab.persistence.dynamodb"
configuration-pid="org.openhab.dynamodb">
```

It seems that file configuration can be used as well

```
region="test-region-file"
```

However, it seems that all old keys (now removed but present before) are present in the `ServiceEvent REGISTERED` (checking the logs). Probably separate issue along the lines of https://github.com/openhab/openhab-distro/issues/396

**Comment by ssalonen** [comment]
PR to update documentation to make the steps more clear: https://github.com/openhab/openhab-docs/pull/756

The DynamoDB related changes were merged in https://github.com/openhab/openhab1-addons/pull/5635

I think we can now close this issue, and follow up doc updates in https://github.com/openhab/openhab-docs/pull/756
