### ISSUE TITLE
[telegram] sendTelegramPhoto should have configurable timeout and retries for slow networks 

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab1-addons#5336]
In some cases, especially with shaky connections, the `sendTelegramPhoto` fails with `SocketTimeoutException`.

## Expected Behavior

HTTP timeout (default 10s) and retries (default 3) should be configurable by the user.

## Possible Solution

PR to follow

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

This happened with 3G connected raspi, probably some intermittent network issue that would have been resolved with more retries and larger timeouts.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by ssalonen** [comment]
Anything I can help to get this forward?

**Comment by 9037568** [comment]
Sorry to have let this sit for so long. We'll give it a little longer in case someone else has any input...

**Comment by ssalonen** [comment]
Sounds good. Thanks!
