### ISSUE TITLE
[anel] Anel Hut 6.1 (or 6.2) sensors not supported

### ISSUE THREAD

**Issue by yveshanoulle** [openhab/openhab1-addons#5338]
In a [previous bug](https://github.com/openhab/openhab1-addons/issues/5262#issuecomment-317275300) Openhab no longer could talk to Anel HUT with 6.1. 
That works now.
Yet the added functionality of 6.1 the [sensors](https://www.anel-elektronik.de/OnlineShop/main_bigware_34.php?items_id=43) don't work. 

## Expected Behavior
 
In 6.1 anel hut API also have extra information.
They support sensors
That information is available in the API, yet not available for OpenHab

You can find the information in the UDP Answer:  
 
NET-PwrCtrl:NET-CONTROL :192.168.178.148:255.255.255.0:192.168.178.1:0.4.163.10.9.107:Nr. 1,1:Nr. 2,1:Nr. 3,1:Nr. 4,0:Nr. 5,0:Nr. 6,0:Nr. 7,1:Nr. 8,1:0:80:IO-1,0,0:IO-2,0,0:IO-3,0,0:IO-4,0,0:IO-5,0,0:IO-6,0,0:IO-7,0,0:IO-8,0,0:27.7°C:NET-PWRCTRL_06.1:h:p:225.9:0.0004:50.056:0.04:0.00:0.0:1.0000:s:20.61:40.7:7.0:xor
https://anel-elektronik.de/SITE/support/hut/hut.htm

## from the HUT internal webpage

The measurement interval is 16 seconds.
20 seconds after the (new)start of device or the sensor is switched on, the LED 'Measurement valid' lights up green. From this moment the relays can be switched.
By '+/-' is meant hysteresis. In the upper area, these parameters are added up, subtracted in the lower area. 22.0 +/- 0.5 = 21.5 (off); 22.5 (on). Larger hysteresis = more fluctuations but slow switching. It also avoids repeated switching (flickering) at the switching threshold.

## Possible Solution
I think the number's I'm looking for are the last part 
**s:20.61:40.7:7.0:**
it would be nice to have something like 
Number anel30_Sensor_Temperature <temperature> { anel="anel30:SENSOR_TEMPERATURE" } 
>> the 20.61

Number anel30_Sensor_Humidity  { anel="anel30:SENSOR_HUMIDIY" }
>> the 40.7

Number anel30_Sensor_Brightness  { anel="anel30:SENSOR_Brightness" }
>> the 7.0

## Context
I'm building a house right now. We are in the phase of warming up the floorheating, I want to use the temperature reading to have a graph of how this goes. 

## Your Environment
* OpenHab 2.1 release build running on two PINE64. (test and production) 
* I installed a beta version last time to help test the person who wrote it (and had no AnelHut 6.1)

**Comment by yveshanoulle** [comment]
I have very limited java experience (like 80 hours or so) and don't have a java editor at my disposal, yet I think something like following code added to these files is a good start. 
(I'm probably missing other parts)  




https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelState.java

/** Sensor temperature; read-only. */
String Sensor_Temperature = null;
/** Sensor Humidity; read-only. */
String Sensor_Humidity = null;
/** Sensor Brightness; read-only. */
String Sensor_Brightness = null; 

https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelDataParser.java	
   
// I think it can use the same Temperature state change function

 final String sensor_temperature = arr[27].substring(0, arr[27].length() - 2);
 if (hasSensorTemperaturChanged(state, sensor_temperature)) {
result.put(AnelCommandType.SENSOR_TEMPERATURE, new DecimalType(sensor_temperature));                
state.sensor_temperature = sensor_temperature;            
}

final String sensor_humidity = arr[28].substring(0, arr[28].length() - 1);
 if (hasSensorHumididyChanged(state, sensor_humidity)) {
result.put(AnelCommandType.SENSOR_HUMIDITY, new DecimalType(sensor_humidity));                
state.sensor_humidity = sensor_humidity;            
}
final String sensor_brightness = arr[29].substring(0, arr[29].length() - 2);
 if (hasSensorBrightnessChanged(state, sensor_brightness)) {
result.put(AnelCommandType.SENSOR_BRIGHTNESS, new DecimalType(sensor_brightness));                
state.sensor_brightness = sensor_brightness;            
}

// I think this can be refactored to have only one temperature state changer, yet it should first work before to refactor

 private static boolean hasSensorTemperaturChanged(AnelState state, final String temperature) {
 if (state == null || state.sensor_temperature == null || state.sensor_temperature.isEmpty()) {
  return true; // no calculation needed if cached state is empty
}
if (temperature.equals(state.sensor_temperature)) {
            return false; // if it equals, nothing changed
}

// report only changes of more than 0.1 degrees
if (TEMPERATURE_PATTERN.matcher(temperature).matches()
                && TEMPERATURE_PATTERN.matcher(state. sensor_temperature).matches()) {
            final int intTemperature = Integer.parseInt(temperature.replace(".", ""));
            final int stateTemperature = Integer.parseInt(state. sensor_temperature.replace(".", ""));
            return !(intTemperature + 1 == stateTemperature || intTemperature - 1 == stateTemperature);
 }

// pattern does not match or temperature differs more than 0.1 degrees
// from last update
  return true;
}

 private static boolean hasSensorHumidityChanged(AnelState state, final String humidity) {
 if (state == null || state.sensor_humidity == null || state.sensor_humidity.isEmpty()) {
  return true; // no calculation needed if cached state is empty
}
if (humidity.equals(state.sensor_humidity)) {
            return false; // if it equals, nothing changed
}
// No Pattern matching (not sure what it would be for humidity)
// humidity differs
// from last update
  return true;
}

private static boolean hasSensorBrightnessChanged(AnelState state, final String brightness) {
 if (state == null || state. sensor_brightness == null || state.sensor_brightness.isEmpty()) {
  return true; // no calculation needed if cached state is empty
}
if (brightness.equals(state.sensor_brightness)) {
            return false; // if it equals, nothing changed
}
// No Pattern matching (not sure what it would be for brightness)
// brightness differs
// from last update
  return true;
}

I assume something needs to be written here too, yet I have no idea what.

https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelCommandType.java

**Comment by yveshanoulle** [comment]
not sure if that helps @paphko or not.

**Comment by paphko** [comment]
I'll try to have look at it next week.

**Comment by yveshanoulle** [comment]
thx

**Comment by yveshanoulle** [comment]
@paphko did you have time to look at this?

**Comment by paphko** [comment]
I created a pull request for sensor support: #5357

**Comment by paphko** [comment]
Snapshot build: https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/binding/org.openhab.binding.anel/1.11.0-SNAPSHOT/org.openhab.binding.anel-1.11.0-SNAPSHOT.jar

**Comment by yveshanoulle** [comment]
Thank you, I will try to install that.

**Comment by yveshanoulle** [comment]
I tried it and it works fine on a openhab 2.1 installation. 
Thank you @paphko
