### ISSUE TITLE
EnOcean EEP A5-04-01

### ISSUE THREAD

**Issue by IanG7DWY** [openhab/openhab1-addons#5341]
Hello

Can the EnOcean E.E.P. A5-04-01 be added to enable the use of Pressac Sensing Mini temperature and humidity sensors?

**Comment by IanG7DWY** [comment]
Hello

Can the EnOcean E.E.P. A5-04-01 be added to enable the use of Pressac Sensing Mini temperature and humidity sensors?

**Comment by fruggy83** [comment]
This EEP is already implemented in the v2 binding.
