### ISSUE TITLE
NIBE F1145 - modbus 40 - raspberrypi

### ISSUE THREAD

**Issue by klsystem1** [openhab/openhab1-addons#5354]
Hi!

I want to use the binding for the nibe gateway for my Nibe F1145 using an raspberrypi.
Can you tell me if it is possible to use an USB to RS485 adapter for that source code ? Do I have to use the c code ? 
Is there any tutorial for using an raspberrypi instead of an arduino? 
Thanks,
Klaus

**Comment by 9037568** [comment]
You should ask this question in the [community forum](http://community.openhab.org/).
