### ISSUE TITLE
[Hue] Osram Smart + Plug not working correctly

### ISSUE THREAD

**Issue by Alexaas** [openhab/openhab1-addons#5378]
Today I got an Osram Smart Plug and connected it to my hue bridge. Then I added it as Thing using Paper UI. But the accepted item type for this Thing is “SwitchItem”. Shouldn’t it be “Switch”. I cannot assign any item, Where does the accepted item type come from and can I fix this somehow? Looks like a bug here.
Additionally I recognized that state updates from outside openhab (e.g. hue app) are not recognized by openhab (currenlty I added the Thing to the Item using the .item file). 
I am using openhabian with openhab 2.1
See  also https://community.openhab.org/t/hue-binding-osram-plug-accepted-item-type-switchitem/37002

## Expected Behavior
- It sould be possible to add Items of type "Switch" to the Thing
- State updates from outside openhab (e.g. hue app) should be reflected in  openhab

## Current Behavior
see above

**Comment by kaikreuzer** [comment]
The hue binding is not an openhab1 binding, so this is the wrong issue tracker. I suggest to first figure out whether there is some bug at all on the forum thread.
