### ISSUE TITLE
[Telegram] TelegramPhoto not working in release 2.2

### ISSUE THREAD

**Issue by bdammrose** [openhab/openhab1-addons#5398]
## Expected Behavior
The TelegramPhoto action worked in release 2.1 according to the documention. I started a discussion thread here: https://community.openhab.org/t/telegram-photo-release-2-2/37824/5

## Current Behavior
With release 2.2 TelegramPhoto action 

`sendTelegramPhoto("group","URL...snap.jpg",null, "user", "password")` is giving this warning

`[WARN ] [ab.action.telegram.internal.Telegram] - Failed to retrieve an image. Received status: HTTP/1.1 401 Unauthorized `  and does not send images anymore. 

Please see discussion in the community here: https://community.openhab.org/t/telegram-photo-release-2-2/37824

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:  openhab 2.2 release 
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspbian Jessie, openhabian 1.4

**Comment by 9037568** [comment]
401 Unauthorized means you've provided unacceptable credentials.

If you can provide a debug log we can check to see if there's some other problem, but it seems unlikely.

**Comment by bdammrose** [comment]
Changed the loglevel to debug but nothing more in the openhab.log than the statement above:
`2017-12-30 13:36:27.850 [WARN ] [ab.action.telegram.internal.Telegram] - Failed to retrieve an image. Received status: HTTP/1.1 401 Unauthorized`

When I test the query locally it works as suggested by @ssalonen:
For example, https://user:passwd@httpbin.org/basic-auth/user/passwd authenticates to https://httpbin.org/basic-auth/user/passwd with username user and password passwd.

However I'm not using https only http.
UserId and Password are correct and other users in the community also report this problem here:  https://community.openhab.org/t/telegram-photo-release-2-2/37824/3

My user is called "user" - is this maybe an unacceptable credential with the updated binding?

**Comment by 9037568** [comment]
>Changed the loglevel to debug but nothing more in the openhab.log than the statement above:

If this is true, then you did it wrong. However, looking at the code, there's not much debug output in the action code that would be helpful anyway.

>However I'm not using https only http.

Then that could be the problem. Please post your actual script statement.
You could also grab a network sniff as an additional check.

**Comment by bdammrose** [comment]
> If this is true, then you did it wrong. However, looking at the code, there's not much debug output in the > action code that would be helpful anyway.

Hm, maybe: 
`openhab> log:get org.openhab.binding.telegram
DEBUG
`
> Please post your actual script statement.

I call it from within a rule after a telegram message an image should be send as telegram. In 2.1 in used this command which worked:

`sendTelegramPhoto("mygroup","http://URL...snap.jpg",null, "myuserid", "mypassword")`

Did the parameters change?

**Comment by 9037568** [comment]
No, the parameters look fine. Most likely the URL you're calling doesn't support http.

**Comment by bdammrose** [comment]
> No, the parameters look fine. Most likely the URL you're calling doesn't support http.

This is where I don't know how to prove it anymore. Did you see the conversation in the community about it at my link above? Other users have similar issues since migrating to 2.2. 
I call a local URL with or without a portnumber 80, I also tried to put the caption "null" into " " just to be sure, but always the same error. The same link works fine to display the snapshot in the sitemap so it is a working URL - at least it was in 2.1 ...

**Comment by 9037568** [comment]
I did read the community thread, but it unfortunately doesn't provide any additional information that's helpful in debugging the issue.

The only other thing I can think of for you to try that I haven't already suggested is to set the http library (org.apache.commons.httpclient) to debug mode and see what additional output you get.

This could generate a lot of output, depending on how many other things are also using it.

**Comment by 9037568** [comment]
I think I may have found the problem. Such a simple thing, I don't know how it was missed.

Please try [this test jar](https://drive.google.com/open?id=1ZXER14mZaOxbyI_J7z_xujxx0u_9xMB7).

**Comment by 9037568** [comment]
[This is the fix](https://github.com/openhab/openhab1-addons/compare/master...9037568:telegram?expand=1), for those interested.

**Comment by ssalonen** [comment]
Damn, so it was certainly a regression in my PR #5337 👎

**Comment by 9037568** [comment]
Copy/paste error, looks like to me. Happens to all of us 😄 
But then, of course, I didn't notice it during review...

**Comment by 9037568** [comment]
We got one positive review in the community thread, so I'm going to push a PR.

**Comment by bdammrose** [comment]
Fix works perfectly fine! Thanks for fixing so fast and happy new year!
