### ISSUE TITLE
[Fatek PLC] Switch item does not work with 2 registers

### ISSUE THREAD

**Issue by jointerCZ** [openhab/openhab1-addons#5420]
## Expected Behavior

According to docs, when i want to display value of REG1, but control REG2, i should use this syntax:

plcName:[!]REG1[[!]REG2]
    REG1 is used for read state of switch
    REG2 is used for change state of switch, if is not specified - REG1 is used

However this is incorrect, it cannot ever work without REG1/REG2 separator, which should be probably ":"

## Current Behavior

When i use space, ; or : as separator, only REG1 is both displayed and controlled.

## Possible Solution

Fix the binding, so it use correct REG separator and fix the documentation.

## Steps to Reproduce (for bugs)

Not possible to reproduce without Fatek PLC present, but this code in Items should work, but it does not:
Switch Test                 	    	    "Test"                                            { fatekplc="plc1:M150:M151" }

## Context

Showing status of a pump, but not controlling it directly.

## Your Environment

openHAB 2.1.0-1 (Release Build) on RPI3/OpenHABian
binding-fatekplc1 - 1.10.0

Thanks.

**Comment by 9037568** [comment]
What errors are seen in the logs?

Please attach a debug log.

**Comment by jointerCZ** [comment]
Author of the plugin is aware of the bug, just asked for written request here. I will inform him that the bug is posted, so he can confirm.

**Comment by slawekjaranowski** [comment]
I confirm, there is logical bug in code.
I'll try correct this in few days.
