### ISSUE TITLE
Rename old  "v" release tags

### ISSUE THREAD

**Issue by pfink** [openhab/openhab1-addons#5428]
I think it would be a good idea to remove the trailing `v` from old release tags to consolidate the current inconsistencies between the release tags. @kaikreuzer: WDYT?

**Comment by kaikreuzer** [comment]
I assume you mean the leading, not the trailing "v"s.

I am not a big fan of changing any historic tests. Tags are supposed to be something stable over time, people might have links against them and use them in builds.

I don't see a problem in changing the tag naming to not use "v"s from now on.

**Comment by pfink** [comment]
Ok, also fine for me! Just for documentation for people finding this issue wondering why the naming convention has changed: As of version 1.11.0, we use an automated release process that creates the tags automatically on all openHAB components and we decided to consistently use the openHAB 2 naming convention (without a leading "v").
