### ISSUE TITLE
[CUL] CUL transport never unloads after disconnection of consuming bindings

### ISSUE THREAD

**Issue by Mik-** [openhab/openhab1-addons#5433]
## Expected Behavior
If all bindings has stopped, wich are consuming the CUL transport, the CUL transport should also unload.

## Current Behavior
The CUL transport  stays active.

## Possible Solution
This [pull request](https://github.com/openhab/openhab1-addons/pull/5329) to prevent a race condition, adds a separate send thread, which binds to the transport itself. This self-listening must be considered in then `hasListeners()` method of the `AbstractCULHandler`.

## Your Environment
* Version used: milestone 1.12.0

**Comment by 9037568** [comment]
Closed via merged PR.
