### ISSUE TITLE
[Enocean] EEP profile not supported

### ISSUE THREAD

**Issue by beeroo** [openhab/openhab1-addons#5454]
I have an Enocean mini temp and humidity sensor that uses the EEP profile A5-04-01 and a temp / humidity / CO2 sensor that uses the EEP profile A5-09-04. I was planning on loading OpenHab onto a Raspberry Pi Model 3 (Noobs) but these profiles aren't currently supported. Any chance you could help?

**Comment by wu3mi** [comment]
I am also interested in the EnOcean Binding. At the moment i want to include window handles from HOPPE (SecuSignal) wich uses the eep protocol F6-10-00. Would be nice to include this too.

**Comment by gadjodilo83** [comment]
please add following EEP`s:

Omnio 
D2-01-03
D2-01-11

thanks!

**Comment by fruggy83** [comment]
Most of these EEPs mentioned here are already implemented in the v2 EnOcean Binding. So I would suggest to close this issue and create a new issue for the EEP family A5-09 in the addons2 repo.
