### ISSUE TITLE
[FHT] FHZ1000 messages are missing

### ISSUE THREAD

**Issue by Jason2866** [openhab/openhab1-addons#5455]
OpenHab2 latest stable release on Rpi3

Messages from FHT8 items are all there and decoded. For the FHZ1000  there are only raw messaged in the Log for the ventil nothing else. If i use FHEM everthing is received.

The log:

````
2018-01-23 17:39:20.639 [DEBUG] [port.cul.internal.AbstractCULHandler] - Received raw message from CUL: T2C3900A6140D
2018-01-23 17:39:20.643 [DEBUG] [nhab.binding.fht.internal.FHTBinding] - Received FHT message
2018-01-23 17:39:20.647 [DEBUG] [nhab.binding.fht.internal.FHTBinding] - Received FHT report
2018-01-23 17:39:20.652 [DEBUG] [nhab.binding.fht.internal.FHTBinding] - Updating item Wohn_Ventil1 with new valve opening 
````

**Comment by 9037568** [comment]
I don't see any errors in that very brief log snippet.

What defect are you saying exists? Do you have a log that supports it?

**Comment by johoberm** [comment]
Hello 9037568,

thanks for your answer. Here is a filtered log. My Setup 5 * FHT 8b and the FHZ 1000.
The FHZ1000 has the Code 2C39. On the FHZ1000 are two ventils binded.
Here i see Ventil 1 but not Ventil 2 too. Maybe here is my Definition wrong?
My items Definition:

[FHT80.items.txt](https://github.com/openhab/openhab1-addons/files/1670930/FHT80.items.txt)

and a filtered LOG:

[FHT.log](https://github.com/openhab/openhab1-addons/files/1670931/FHT.log)

**Comment by 9037568** [comment]
As far as I can tell from this, OH is operating correctly. There are no errors reported, and the events found for 2C39 appear to be being handled correctly.

Again, as far as I can tell, OH is simply not receiving the other events you're looking for.

I suggest starting a thread in the community forum to see if anyone can help you debug further.

**Comment by Jason2866** [comment]
Thank you for looking!
Then there must be a different init in FHEM.
I will trace FHEM....
