### ISSUE TITLE
[Pushover] Feature request: Pushing images

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab1-addons#5457]
Pushover released a new API version which supports to push images.

https://updates.pushover.net/post/170043375237/pushing-images-with-pushover-30

Link to the community thread https://community.openhab.org/t/pushover-image-support/39201

**Comment by andre77** [comment]
i also would like to have the feature.
played around sending pushover notifications using a java application, it worked fine so far.
my problem is, i'm not familiar with openhab plugin development.

is there a simple way to set up the dev environment and build the artefacts?
how can i test the new created actions? currently i'm running an openhab2 instance, so how to deploy my new artefact?
will create a PR, if i figure out the points with the dev environment

**Comment by cweitkamp** [comment]
Hi @andre77 ,

sounds good. Your help is very much appreciated.

Did you see these documentations: https://docs.openhab.org/developers/development/ide.html

**Comment by andre77** [comment]
Hi @cweitkamp,
i added support for pushing images, the maven build runs without any error. Now the next question, how do i deploy the newly created org.openhab.action.pushover-1.12.0-SNAPSHOT.jar to my openhab2 instance ?

**Comment by cweitkamp** [comment]
Nice. Have a look here: https://docs.openhab.org/installation/linux.html#installing-add-ons. Uninstall the original binding first and then put the new .jar file into your addons folder. Happy to hear feedback.

I'm looking forward to see your code contribution.

**Comment by andre77** [comment]
here we go https://github.com/openhab/openhab1-addons/pull/5527

**Comment by 9037568** [comment]
Closed via merged PR.
