### ISSUE TITLE
[KNX] converting from 9.007 to 5.001 needs correction

### ISSUE THREAD

**Issue by ggzengel** [openhab/openhab1-addons#5462]
I use roller shutter with two group ids and have to use them in combination:
set position: 5.001
get position: 9.007

Item:
```
Rollershutter RS1 "RS1 [%d %%]" (All) {knx="2/0/101, 2/0/131, 5.001:2/0/201+<9.007:2/1/201"}
Number RS1Go "RS1 Go [%3.0f %%]" (All) {knx="2/0/201"}
Number RS1Pos "RS1 Pos [%3.0f %%]" (All) {knx="2/1/201"}
```

Sitemap:
```
Default item=RS1
Slider item=RS1
Default item=RS1Pos
Default item=RS1Go
```

Values after closing shutter:
```
RS1=11%
RS1Pos=100%
RS1Go=100%
```

## Expected Behavior
RS1 should show 100%

## Current Behavior
The 100% position is shown as 11%.
It looks like 9.007 is interpreted as 2 byte unsigned and is shifted to a 1 byte value.

1. 100%=0x1ce6 from device
2. 0x1ce6>>8=0x1c
3. 0x1c=28
4. percent(28) = 28*100/256 = 11%

## Possible Solution
Use 9.007 as float and multiply it with 2.56:
<5.001>=int(float(<9.007>)*2.56)

I think all floats (9.*) are converted wrong if they are used in combination with byte values.

## Your Environment

```
uname -a
Linux openhab2 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

dpkg --list openhab2
ii  openhab2                                     2.2.0-1                     all                         openhab2
```

**Comment by lewie** [comment]
[PR for this issue](https://github.com/openhab/openhab1-addons/pull/5513)

**Comment by 9037568** [comment]
Closed via merged PR.
