### ISSUE TITLE
Openhab cannot run on ubuntu 14.04

### ISSUE THREAD

**Issue by hesamira** [openhab/openhab1-addons#5488]
I used the following link to install openhab:
https://github.com/openhab/openhab1-addons/wiki/Linux-and-OS-X

sami@sami-Vostro-1520:~$ sudo /etc/init.d/openhab start
[sudo] password for sami: 
 * Starting openHAB server openhab                                       [ OK ] 
sami@sami-Vostro-1520:~$ sudo /etc/init.d/openhab status
 * openhab is running
sami@sami-Vostro-1520:~$

**Comment by 9037568** [comment]
You should raise this question in the community forum.

**Comment by hesamira** [comment]
How can i run Openhab?
When i run the above commands, Openhab did not work.

Please, guide me.

**Comment by 9037568** [comment]
As I said, go ask this question in the [community forum](http://community.openhab.org/).
