### ISSUE TITLE
[Zwave] unknown device error for a listed supported device

### ISSUE THREAD

**Issue by truefate** [openhab/openhab1-addons#5491]
I'm running a raspberry pi with a husbzb-1. Everything is set up and running but one of my zwave light switches is coming up as an "unknown device". I checked supported devices and it is listed rf9540 Cooper wiring smart dimmer. I have another aspire zwave device (smart outlet) which works fine. I've deleted and reconnected it several times with the same result.

**Comment by 9037568** [comment]
You should ask this question in the [community forum](http://community.openhab.org/).
