### ISSUE TITLE
[MQTT] broker.url not updated when mqtt.cfg is changed

### ISSUE THREAD

**Issue by Josar** [openhab/openhab1-addons#5500]
https://community.openhab.org/t/mqtt-works-in-the-shell-but-not-in-openhab/40224/12

When a wrong broker url was set there will be an error in the log. When changing the broker url to a valid url the error will be repeated. So the client is basically started with the same wrong url.

The /var/lib/openhab2/config/org/openhab/mqtt.config seems to be updated. But not the place where the client gets the url information from.
 
Only when restarting openhab the client connects to the proper url.

**Comment by 9037568** [comment]
Please provide a debug log, along with your configurations.

**Comment by Josar** [comment]
` openhab> log:set TRACE org.openhab.binding.mqtt`

Did not increase the output, so please tell me how to set the mqtt binding log output to TRACE.

**Comment by 9037568** [comment]
>I seems that it was setted to TRACE but there was not more information displayed.

More information is displayed:

>01:56:23.858 [TRACE] [t.internal.MqttGenericBindingProvider] - Starting to load MQTT config for item MQTT_data

You should also set trace mode for the transport: org.openhab.io.transport.mqtt
Then just capture the log and attach it here.

**Comment by Josar** [comment]
Sorry for the missunderstanding. The previous post just growed by multiple edits.
When i changed the log level, i did not got more info becausee i only changed the url. And as you can see after a change of the url there is not more info from TRACE. But after I restarted i saw that the change worked and there where TRACE logs. But still not when changing the url and saving.

When i have a valid url and change it to a invalid (see port), it still works properly no error.
```
09:34:25.350 [TRACE] [openhab.io.transport.mqtt.MqttService] - Processing property: mymosquitto.pwd = Testing
09:34:25.355 [TRACE] [openhab.io.transport.mqtt.MqttService] - Processing property: mymosquitto.url = tcp://localhost:188%
09:34:25.361 [TRACE] [openhab.io.transport.mqtt.MqttService] - Processing property: mymosquitto.user = Openhab
09:34:25.365 [INFO ] [openhab.io.transport.mqtt.MqttService] - MQTT Service initialization completed.
09:34:25.372 [INFO ] [rt.mqtt.internal.MqttBrokerConnection] - Starting MQTT broker connection 'mymosquitto'
09:34:25.376 [DEBUG] [rt.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'mymosquitto' on topic '433MHz'
```

**Comment by Josar** [comment]
Know we hava a little bit more in the log file. But the behaviour is still wrong. As the new log states ` client already created and connected. nothing to do.` But the url has changed, so the client has to be stopped and a new one has to be set up.

```
[DEBUG] [openhab.io.transport.mqtt.MqttService] - Processing config key mymosquitto.pwd yields name mymosquitto and property pwd.
[TRACE] [openhab.io.transport.mqtt.MqttService] - Processing property: mymosquitto.pwd = Testing
[DEBUG] [openhab.io.transport.mqtt.MqttService] - Processing config key mymosquitto.url yields name mymosquitto and property url.
[TRACE] [openhab.io.transport.mqtt.MqttService] - Processing property: mymosquitto.url = tcp://localhost:1884S
[DEBUG] [openhab.io.transport.mqtt.MqttService] - Processing config key mymosquitto.user yields name mymosquitto and property user.
[TRACE] [openhab.io.transport.mqtt.MqttService] - Processing property: mymosquitto.user = Openhab
[INFO ] [openhab.io.transport.mqtt.MqttService] - MQTT Service initialization completed.
[INFO ] [rt.mqtt.internal.MqttBrokerConnection] - Starting MQTT broker connection 'mymosquitto'
[TRACE] [rt.mqtt.internal.MqttBrokerConnection] - client already created and connected. nothing to do.
```

**Comment by 9037568** [comment]
I thought that case might fail. I'll work up another revision.

**Comment by 9037568** [comment]
I've uploaded a new version of the jar which I think will resolve this.

**Comment by Josar** [comment]
When i change the port from working to non working and save i get following

```
[TRACE] [openhab.io.transport.mqtt.MqttService] - Processing property: mymosquitto.pwd = Testing
[TRACE] [openhab.io.transport.mqtt.MqttService] - Processing property: mymosquitto.url = tcp://localhost:1885
[TRACE] [openhab.io.transport.mqtt.MqttService] - Processing property: mymosquitto.user = Openhab
[INFO ] [openhab.io.transport.mqtt.MqttService] - MQTT Service initialization completed.
[INFO ] [rt.mqtt.internal.MqttBrokerConnection] - Starting MQTT broker connection 'mymosquitto'
[DEBUG] [rt.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'mymosquitto' on topic '433MHz'
[DEBUG] [rt.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'mymosquitto' on topic '433MHz'
[DEBUG] [rt.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'mymosquitto' on topic '433MHz'
[DEBUG] [rt.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'mymosquitto' on topic '433MHz'
[DEBUG] [rt.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'mymosquitto' on topic '433MHz'
[DEBUG] [rt.mqtt.internal.MqttBrokerConnection] - Starting message consumer for broker 'mymosquitto' on topic '433MHz'
[ERROR] [org.apache.felix.configadmin         ] - Cannot use configuration org.openhab.mqtt for [org.openhab.io.transport.mqtt.MqttService, org.osgi.service.cm.ManagedService, id=319, bundle=234/file:/usr/share/openhab2/addons/org.openhab.io.transport.mqtt-1.12.0-SNAPSHOT(1).jar]: No visibility to configuration bound to mvn:org.openhab.io/org.openhab.io.transport.mqtt/1.12.0-SNAPSHOT

```

And the brocker still gets not updated.

**Comment by 9037568** [comment]
That sounds like a platform problem. Not seeing it here using OH 2.1.

**Comment by Josar** [comment]
I have  2.3.0-SNAPSHOT Build #1219 running on a RPI3.

**Comment by kaikreuzer** [comment]
@Josar There is [an old thread](https://community.openhab.org/t/solved-mqtt-binding-stopped-working-after-todays-snapshot-update/19447) which had similar errors in the log and the analysis showed that it was caused by the MQTT binding and action being installed at the same time (only one of them succeeds in getting the configuration).
Do you have the MQTT action installed as well? If so, could you uninstall it and check whether the problem remains?

**Comment by sjka** [comment]
The problem is that two bundles containing ManagedServices using the same PID are involved:

`file:/usr/share/openhab2/addons/org.openhab.io.transport.mqtt-1.12.0-SNAPSHOT(1).jar` vs `mvn:org.openhab.io/org.openhab.io.transport.mqtt/1.12.0-SNAPSHOT`

So it looks like you manually tried installing the same bundle again, right?

OSGi is pretty clear about that:

> If a configuration's location is null, it is not yet bound to a location. It will become bound to the location of the first bundle that registers a ManagedService or ManagedServiceFactory object with the corresponding PID.

and further 

> The purpose of binding a Configuration object to a location is to make it impossible for another bundle to forge a PID that would match this configuration. When a configuration is bound to a specific location, and a bundle with a different location registers a corresponding ManagedService object or ManagedServiceFactory object, then the configuration is not passed to the updated method of that object.

(see https://osgi.org/javadoc/r4v42/org/osgi/service/cm/Configuration.html)

**Comment by Josar** [comment]
I do not have the action installed.

What @sjka says would be the problem. So the first time i uninstalled the mqtt binding via paperUI as installed it from there. And i would expect that when installing a binding manually, i would uninstall it by removing from the addons folder or update by replacing it.

Maybe i did not properly uninstallt the mqtt binding?

So uninstalled mqtt binding in paperUI, stoped openhab, deleted old jar in addons copied new jar, set user rights, restart openhab.
```
[WARN ] [org.apache.felix.fileinstall         ] - A bundle with the same symbolic name (org.openhab.io.transport.mqtt) and version (1.12.0.201803040603) is already installed.  Updating this bundle instead.
```
When i uninstalled it it seem to still be there but it got updated at least.

The result is:
A new client with the right settings gets created when saving the cfg.
Looks as it works.
