### ISSUE TITLE
[Telegram] Custom Timeout not working without user auth due to typo 

### ISSUE THREAD

**Issue by Truddel** [openhab/openhab1-addons#5506]
Hello, 
i found out that the custom timeout in Telegram action is not working. I think the problem is in line 155 where "@ParamDoc(name = "timeoutMillis") **Integer** timeoutMillis) {" needs to be replaced with "@ParamDoc(name = "timeoutMillis") **int** timeoutMillis) {"

Would be great if someone could do and commit this small change.

Many thanks in advance.
Best regards,
Seb

**Comment by 9037568** [comment]
If there's any problem with the timeout, I'm not sure how it could have anything to do with Integer vs. int.

What makes you think the custom timeout isn't working?

**Comment by Truddel** [comment]
When i try to send a custom rendered picture from Grafana (which takes some long time above 10 secs) after 10 seconds the script stops with an error. I habe set the custom timeout to 30000 millis. I will update this post with my rule and exception.

**Comment by 9037568** [comment]
I think this script call is wrong, since there is no method that takes 6 parameters.

````
sendTelegramPhoto("bot1",url,"testbild",null,null,"30000")
````

Try using this one:

````
sendTelegramPhoto("bot1",url,"testbild",30000)
````

**Comment by Truddel** [comment]
Sorry for my late answer. I have tried today with your suggestion and it was successful. But what do you think would be the right arguments for custom timeout with authentication? IMHO than it is mandatory to use 6 parameters?

**Comment by 9037568** [comment]
Custom timeout WITH authentication is 7 parameters:

````
sendTelegramPhoto(String group, String photoURL, String caption, String username, String password,
int timeoutMillis, int retries)
````
