### ISSUE TITLE
[FHT] fht1 Binding doesn't install on OpenHAB 2.x

### ISSUE THREAD

**Issue by rralf** [openhab/openhab1-addons#5507]
Adding fht1 to addons.conf won't install the FHT binding. Other OH1 bindings do install.

## Expected Behavior
See sth. like 'binding-fht1 successfully installed' in logs instead of nothing.

## Current Behavior
Binding doesn't install, no errors appear in the logs. Additionally, the fht binding doesn't appear in feature:list in the cmdline interface. Othe OH1 bindings do appear.

## Steps to Reproduce (for bugs)
1. Install OH2.x
2. Add fht1 to binding section in addons.conf

## Context
I just got some FHT devices and would like to connect them to OH.

## Your Environment
Latest OH 2.3 snapshot, also tested with OH 2.2.

**Comment by 9037568** [comment]
Your "Steps to Reproduce" doesn't list the step "add fht jar to addons directory". 
Was this step done and you just didn't list it here?

**Comment by rralf** [comment]
Do I have to? Adding bindings to service.cfg automatically installed bindings so far.

So if I add, e.g., chromecast to the binding list it automatically installs the chromecast binding. Documentation tells nothing about placing jar's somewhere.

Thanks

**Comment by 9037568** [comment]
Yes.

Step 1 in the [binding documentation](Copy binding package to the respective folder) says:

````
Copy binding package to the respective folder
````

It's a little disappointing that this doesn't seem to be covered in the new docs.openhab.org site. Maybe I'm just overlooking it.

Also, the [FHT entry in the new docs](https://docs.openhab.org/addons/bindings.html) does show it is a manual install.

**Comment by rralf** [comment]
Would be nice to wait for feedback before closing an issue.

Anyway, I'm sorry but the page you're pointing me to doesn't say anything about fht, or fht1, I can't even find it in the binding list. So seems like proper documentation is missing at this point. Also, googling for a 'jar' file didn't help.

I think you're referring to this page: https://github.com/openhab/openhab1-addons/wiki/bindings

I downloaded the addons and the legacy package. I'm unable to find the fht jar in both packages.

Call me dumb, but documentation is really poor and I still don't exactly know where to get the required files. And it's really confusing that openhab doesn't yell or throw errors if I add non-existing bindings to the binding list in the addons.cfg.

So could you please explain why a subset of bindings can be installed via addons.cfg (even legacy bindings, like mqtt1) and some not?

Thanks.

**Comment by rralf** [comment]
So after hours of searching, I found the binding "org.openhab.binding.fht-1.11.0.jar", placed it in the addons directory and added fht1 to the addons.cfg.

openhab.log:
`2018-03-04 01:17:12.953 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-fht1': Error restarting bundles:
        Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="0.10.0.201802191927"; osgi.identity="org.eclipse.smarthome.model.script.runtime"; singleton:="true" [id=147] STARTED [STARTED]
`

**Comment by 9037568** [comment]
[This thread](https://community.openhab.org/t/core-karaf-feature-installer-error-after-2-2-upgrade/37486) appears to indicate this error does not prevent proper function. What's the status of the binding after this error appears?

Is the compatibility layer installed and running?

Also, please show the contents of your addons.cfg.

**Comment by rralf** [comment]
Sorry, I didn't get it running.

I wrote my own [MQTT <-> FHT](https://github.com/rralf/fhz2mqtt) gateway, which solves this issue for me.

Thanks

**Comment by erichabg** [comment]
Nothing regarding manual installation can be found on the mentioned page [https://www.openhab.org/addons/bindings/fht1/](url) and the links on the page [https://github.com/openhab/openhab1-addons/wiki/Bindings#installation](url) are empty!
Frustrating!
