### ISSUE TITLE
[Telegram Action] Feature Request - Add support for html formatted messages

### ISSUE THREAD

**Issue by FulvioSpelta** [openhab/openhab1-addons#5508]
Hi all
is it possibile/planned to support sending html/markdown formatted messages ?
Currently seems that all messages are sent as "text".
Thanks

**Comment by 9037568** [comment]
There's a [PR in progress](https://github.com/openhab/openhab1-addons/pull/5490) for this.

**Comment by FulvioSpelta** [comment]
Thanks. I'll follow the PR.
