### ISSUE TITLE
[FritzboxTr064] ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Fuempel** [openhab/openhab1-addons#5522]
## Expected Behavior
Log should not contain any Java exceptions.

## Current Behavior
Sporadically (every few days) I observe the following log entries (they are found in the Docker log, I'm running OpenHab 2.2.0 in Docker):

```
2018-03-14 10:41:07 | stdout | Exception in thread "Thread-878342" java.lang.ArrayIndexOutOfBoundsException: 4
2018-03-14 10:41:07 | stdout | at org.openhab.binding.fritzboxtr064.internal.CallEvent.parseRawEvent(CallEvent.java:133)
2018-03-14 10:41:07 | stdout | at org.openhab.binding.fritzboxtr064.internal.CallMonitor$CallMonitorThread.run(CallMonitor.java:249)

```
Additionally, I find every 2 hours the following entries in openhab.log:
```
2018-03-18 08:00:00.003 [INFO ] [xtr064.internal.FritzboxTr064Binding] - Fritzbox Reconnect Job executed
2018-03-18 08:00:00.089 [INFO ] [g.fritzboxtr064.internal.CallMonitor] - Lost connection to Fritzbox because of interrupt
2018-03-18 08:00:05.094 [INFO ] [g.fritzboxtr064.internal.CallMonitor] - Connected to FritzBox on 192.168.177.1:1012
```

Any idea why the array exception and the connection losses occur ?

## Your Environment

* Version used: openhab/openhab:2.2.0-amd64-debian from Docker Hub
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Synology DSM 6.1.5

**Comment by 9037568** [comment]
For the ArrayIndexOutOfBoundsException, the problem appears to be that at [line 133](https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.fritzboxtr064/src/main/java/org/openhab/binding/fritzboxtr064/internal/CallEvent.java#L133), the binding is expecting a CONNECT to have an external number:

````
        } else if (this._callType.equals("CONNECT")) {
            this._line = fields[3];
            this._externalNo = fields[4];
````

You could put the binding into debug mode and check the log for a line like this: `"Received raw call string from fbox: ...`

That might help you tell which calls are causing the error in the log.

**Comment by 9037568** [comment]
The second item is probably because the binding schedules a reconnect every 2 hours.

**Comment by Fuempel** [comment]
For the array exception: with help of my call protocal, I can tell that this occurs if a call from an unknown caller (no / suppressed external number is given is taken up:

Extract from FritzBox "Anrufliste":
14.03.18 10:41 | Unbekannt | Privat

Maybe the case of an caller with suppressed number is not handled ?

**Comment by 9037568** [comment]
The choices for eliminating the exception here are:
1) Set the variable to null
2) Set the variable to the empty string
3) Set the variable to some value such as "Private", "Unknown", "Not Provided", etc.

However, there could be knock-on effects from any of these...

**Comment by staehler** [comment]
I've the same problem. Is there a way to fix it?

@9037568: I would choose variant 3. to set the value to "Unknown", that's quite near to the reality, as the phone number is suppressed.

**Comment by 9037568** [comment]
Thanks for the feedback, @staehler. I'll look into making the change...

**Comment by 9037568** [comment]
Closed via merged PR.
