### ISSUE TITLE
Java quartz scheduled persistence rule fails at summertime transition 01:59->03:00

### ISSUE THREAD

**Issue by thomasstrangert** [openhab/openhab1-addons#5530]
## Expected Behavior
Java quartz persistence rules should survive/cope with summertime transition and keep trigger persistence of data.

## Current Behavior
I noticed after the transition to summertime (i.e. skipping one hour ahead at 01:59:59 -> 03:00:00 night between Sat 24 Mar to Sun 25 Mar), that some of the persistence rules I have stopped working.

OH2 logfiles (openhab.log/events.log) looks normal around the time. I can see the timestamp skip one hour as expected and events are logged normally after the transition.

However, looking straight into the persistence database (I use JDBC/MariaDB) I can see that certain items were no longer persisted.

Comparing with my **conf/persistence/jdbc.persist** file it became clear that items that relied on Java quartz strategies I made stopped being persisted, whereas items that (also) had an **everyChange** strategy kept being persisted - but **only** for the everyChange events (e.g. a reported temperature change) **not** for its Java quartz triggers.
**Case in point:**
> Strategies {
>         everyMinute     : "0 * * * * ?"
> }
> Items {
>         tempSalong              : strategy = everyMinute, restoreOnStartup
>         landstromTotal          : strategy = everyChange, everyMinute, restoreOnStartup
> }
The **tempSalong** item stops being persisted, i.e. its two last stored data values were timestamped 01:59:00 and (perhaps interestingly) 03:00:00 but not for the minute 03:01:00 and onwards.

The **landstromTotal** item keeps getting persisted, but after 03:00:00 triggered **only** for the spontaneous everyChange events - not for the Java quartz scheduled everyMinute events.

**Habmin graph of my temperature items, flat-lining due to data loss until restart of OH2:**
![image](https://user-images.githubusercontent.com/4232976/37909801-2c11457e-310c-11e8-8adb-fa86ca194830.png)

**Habmin graph of items that are only being partially persisted after the summertime kicks in. Since only the changes of values are stored the line looks like a saw-tooth, normally with samples every minute the graph is more continuous.**
![image](https://user-images.githubusercontent.com/4232976/37909683-dfa9f1a4-310b-11e8-87c4-83ba13aa916f.png)

## Possible Solution
Restart of OH2 needed to clear (not fix) the problem.

## Steps to Reproduce (for bugs)
1. Set up persistence items as above
2. Set host system time to 2018-03-25 01:55:00 (disable any NTP updates so the time doesn't corrects itself)
3. Start OH2 and let it run for some 10 minutes over to summertime
4. Check the log files and DB to see what's in there.

## Context
The issue caused potentially valuable logging of items (temperatures, power consumption whatnot) to stop functioning. Graphs in Habmin became flatline or empty.

To fix problem a restart of OH2 was needed, then persistence started to work again but obviously the non-persisted data between 03:00:00 until restart is lost (i.e. never stored).

## Your Environment
* openhab-2.2.0.tar.gz official release version
* java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
* CentOS Linux release 7.4.1708 (Core)

**Comment by kaikreuzer** [comment]
This has been fixed with https://github.com/eclipse/smarthome/pull/5299 - sorry, too late for the 2.2.0 release 🙄

**Comment by thomasstrangert** [comment]
Well, let's hope that 2.3.0 is out before it's time for summertime->standard time transition in October then! ;)

**Comment by triller-telekom** [comment]
@thomasstrangert Summer time to standard time will be different from what was fixed in eclipse/smarthome#5299. But I think there was no problem in last october when the time change happened.
