### ISSUE TITLE
[Telegram] silently fails when no network connection

### ISSUE THREAD

**Issue by UrsusS** [openhab/openhab1-addons#5531]
If we want to send a telegram message while the network is down, the action fails with a warning in the log file, but it provides no information to the rules.

```
27-Mär-2018 11:11:01.378 [WARN ] [ab.action.telegram.internal.Telegram] - Transport error: {}
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:?]
...
```
It would be good it there would be a signal if the transmission of the message to the server was successful. Than the rule could try to resend it again.
As alternative it would be nice if the action could handle the retransmission by itself.

I'm using OpenHAB 2.2.

**Comment by 9037568** [comment]
A warning is by definition not silent. And what do you mean by "it provides no information to the rules"?

Please show the rule you're using along with any related item definitions.

**Comment by UrsusS** [comment]
For me it is silent (from viewpoint rule) if I don't get a return value from the action if the transmission was successful. And I couldn't find it in the docs.

Here is one of my use cases for the sendTelegram action. It is independent of any items. 
```
`	if (OFFLINEItems != "")
	{
		var String Message
		Message = "Folgende Devices sind OFFLINE:\r\n"
		Message += OFFLINEItems
		sendTelegram("HausWartung", Message)
	}
`
```
Normally it works as it should, the only problem is that I get no feed back if the transport failed and recipient does not receive the message.

**Comment by 9037568** [comment]
So have you tried this?

````
    var success = sendTelegram("HausWartung", Message)
    if (!success) {
        //handle failure here
    }
````

**Comment by UrsusS** [comment]
Thanks, that is what I looked for. I tried it and it works.

Could you add it to the documentation? There is no hint that the action has a return value.
