### ISSUE TITLE
[FritzboxTr064] Calltype class: Could not cast to void

### ISSUE THREAD

**Issue by Stefan300381** [openhab/openhab1-addons#5538]
## Current Behavior
I copied the rules configuration from the documentation. The following line generates an error message in openhab.log

`val CallType incCall = fboxIncomingCall.state as CallType`

`[ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'Phone is ringing': Could not cast %CALLEDNUMBER%,%CALLERSNUMBER% to void; line 7, column 28, length 30
`
Example
`[ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'Phone is ringing': Could not cast 123456,123456789 to void; line 7, column 28, length 30
`

## Possible Solution
My assumption is that the seperator (the comma) is not expected. In CallType.java I noticed:
`private static final String SEPARATOR = "##";`

**Comment by 9037568** [comment]
You'll need to present the rest of your configuration as well as the entire rule you're using.

**Comment by Stefan300381** [comment]
Hi 9037568,

thanks for the feedback. As mentioned I copied it from the documentation.

https://docs.openhab.org/addons/bindings/fritzboxtr0641/readme.html

items:
```
Switch  fboxRinging         "Phone ringing [%s]"                {fritzboxtr064="callmonitor_ringing" }
Switch  fboxRinging_Out     "Phone ringing [%s]"                {fritzboxtr064="callmonitor_outgoing" }
Call    fboxIncomingCall    "Incoming call: [%1$s to %2$s]"     {fritzboxtr064="callmonitor_ringing" } 
Call    fboxOutgoingCall    "Outgoing call: [%1$s to %2$s]"     {fritzboxtr064="callmonitor_outgoing" }
```

rules:
```
rule "Phone is ringing"
when
    // fboxRinging is a switch item which switches to ON if call is detected
    Item fboxRinging changed from OFF to ON 
then
    logInfo("Anrufermeldung", "Generating caller name message...")
    // fboxIncoming call receives numbers/name of incoming call
    val CallType incCall = fboxIncomingCall.state as CallType
    var callerName = incCall.destNum //destNum is external number OR resolved Name if no phonebook entry exists

    // do something with callerName
end
```

anything else you need?

Stefan

**Comment by 9037568** [comment]
[This post](https://community.openhab.org/t/fritzbox-tr064-binding-creation-of-esh-event-failed/10064/12) appears to hold the answer.

````
val incCall = fboxIncomingCallResolved.state as StringListType
````

**Comment by Stefan300381** [comment]
thanks a lot, this helped in deed!

I am sorry if this is a stupid question:
a) I'd like to make the required changes to the documentation. Is this allowed? If so, how can I do this?
b) Does it even make sense? Maybe the documentation is right for OH1 but just not for OH2?

best regards

Stefan

**Comment by 9037568** [comment]
You can modify the [README file](https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.fritzboxtr064/README.md), which will then populate to the docs.openhab.org site you quoted.

I've reopened this ticket as a documentation issue if you wish to submit a PR.

**Comment by Stefan300381** [comment]
did it for the first time ;-)
Hope everything is fine. 

Pull request:
Update README.md #5540
