### ISSUE TITLE
[Serial] Issue with BASE64 option

### ISSUE THREAD

**Issue by TheNetStriker** [openhab/openhab1-addons#5542]
## Expected Behavior
The serial binding readme states that adding the option ",BASE64 " to the config string enables the Base64 mode.

## Current Behavior
Since [this ](https://github.com/openhab/openhab1-addons/commit/5c4c191814fe8f80f6a86a98a5a07e40e6b5af65#diff-25fc46200ac78044e5ed6aa43bc21070) commit was merged this doesn't work as intended any more. The problem is that in the SerialBinding.java class at line 169 the last character of the config string is always cut off. So when entering "BASE64" this turns into "BASE6" and the base64 mode is not enabled. As a workarround I now just entered "BASE64(" and this now enables the base64 mode.

## Possible Solution
One way to solve this would be to change the documentation so that always BASE64() should be entered. Also the string at line 177 should be changed to "BASE64(".

## Steps to Reproduce (for bugs)
Just add a serial port with only BASE64 as option.

## Context
This is just a confusing bug.

## Your Environment
OpenHabian on Raspberry Pi 3

**Comment by 9037568** [comment]
Well, I was going to add a set of tests for validating the binding config parsing, but that would require a heavy refactoring because the binding tries to connect the ports while parsing the config.

So we'll have to settle for just fixing the parsing failure.

**Comment by 9037568** [comment]
Here's a test jar 
[org.openhab.binding.serial-1.12.0-SNAPSHOT.zip](https://github.com/openhab/openhab1-addons/files/1886331/org.openhab.binding.serial-1.12.0-SNAPSHOT.zip)

**Comment by TheNetStriker** [comment]
I just tested this and it works. Thanks for fixing this so quick.

By the way, I think I also just found another issue with the serial binding and created a thread in the forum: https://community.openhab.org/t/strange-problem-with-serial-binding/43230

If I can confirm that my fix is working I will also create an issue here.

**Comment by TheNetStriker** [comment]
I just created another issue for the encoding problem here: https://github.com/openhab/openhab1-addons/issues/5548
