### ISSUE TITLE
[Bticino] binding does not accept alphanumeric password

### ISSUE THREAD

**Issue by enrico-cc** [openhab/openhab1-addons#5549]
I have a gateway that requires an alphanumeric password but the connector seems to allow only numerical password.

## Expected Behavior
in services/bticino.cfg  should be possible to use alphanumeric passwords

## Current Behavior
Here is the error I receive:
![38523440-cd691dda-3c4b-11e8-8634-4a3385c9d2e6](https://user-images.githubusercontent.com/38229078/38581379-00687598-3d0d-11e8-85c5-d04c9d38643f.png)

## Possible Solution
under openhab1-addons/bundles/binding/org.openhab.binding.bticino/src/main/java/com/myhome/fcrisciani/connector/

change password string definition

## Steps to Reproduce (for bugs)
in services/bticino.cfg insert this item:
webserver.passwd=Test1234

then launch openhub server (under windows "start.bat"

## Context
my bticino gateway is myhomeserver1 that requires an alphanumeric password

## Your Environment
openhab 2.2.0
win10
myhomeserver1

**Comment by rinal13** [comment]
Can't work as the implemented password authentication mode of the connector is the "old"
"OPEN authentication algorithm", which only works with numeric passwords up to 5 digits.

The new HMAC protocol (Hashed Message Authentication Code) is not implemented.
Only with that method alphanumeric passwords up to 30 alphanumeric characters, among digits (0-9) lowercase and uppercase letters (a-z, A-Z) are possible.

**Comment by enrico-cc** [comment]
Ok I thought it was an issue related to the validation of the string that prevented the use of letters.
The HMAC protocol is not supported in the binding so there is no way I can use openhab with myhomeserver1, right?

**Comment by rinal13** [comment]
May there is a way.
There is actually a openwebnet binding in development (basically only light are working now). Probably this will work. May you have a look and try.
[https://community.openhab.org/t/bticino-openwebnet-new-binding-bticino-openwebnet-2-0-binding-ready-for-testing/43377](url)

**Comment by enrico-cc** [comment]
Thank you, it doesn't work right now but at least it is in development!

**Comment by mvalla** [comment]
I have implemented HMAC in the new OWN binding for OH2, and in first tests it works with gw such as MyHOMEServer1. I may also add the support here in the 1.x binding, but actually OH maintainers suggest that new feature should be done only in the 2.x binding. I suggest new implementations regarding OWN is done only the new binding (I will add it to the OH2 repository soon).

**Comment by 9037568** [comment]
Agreed.
