### ISSUE TITLE
[MQTT] Changing the name of the broker in mqtt.cfg results in 2 connections

### ISSUE THREAD

**Issue by kinl99** [openhab/openhab1-addons#5552]
## Expected Behavior
Only one mqtt client should be created

## Current Behavior
If an mqtt broker is being configured via config a client is being created in background, according to the name of the broker given in the config. You name the broker mqtt1, e.g. mqtt1.Url=192.168.1.x:1883
If you rename mqtt1 to mqtt2 inside services/mqtt.cfg a second client is being created that also is trying to connect the same broker. That results in errors if a static client ID is given, as the first client with the same ID is already connected

## Possible Solution
Change connection handling so that the existing client is being updated in stead of creating a new one

## Steps to Reproduce (for bugs)

1. Install Mqtt Binding
2. Configure Mqtt Binding with broker name mqtt
3. Send messages using the client (broker name: mqtt) via outbound item or console 
4. Rename broker mqtt to mqtt2 in services/mqtt.cfg
5. Adjust items to use the new client (broker name: mqtt2)

## Your Environment
Docker on Syn. DS216+II, Openhab Debian 2.2.0 amd64

**Comment by ssalonen** [comment]
Possibly related, see this comment https://github.com/openhab/openhab1-addons/issues/5084#issuecomment-374278403

**Comment by 9037568** [comment]
Please update your ticket with OH version, configuration, and debug log.

**Comment by kinl99** [comment]
3.1 or 3.1.1 iguess as this is my broker:
https://hub.docker.com/_/eclipse-mosquitto/

**Comment by 9037568** [comment]
Please drop another note here if you find this isn't resolved with 1.12.
