### ISSUE TITLE
[Digitalstrom] KL220 and HKL230 feature recognition wrong in binding

### ISSUE THREAD

**Issue by maxx92** [openhab/openhab1-addons#5555]
<img width="1458" alt="screenshot 2018-04-15 14 11 24" src="https://user-images.githubusercontent.com/37867741/38777936-563092c6-40b9-11e8-8737-4ca7482a4db9.png">
<img width="1461" alt="screenshot 2018-04-15 14 14 06" src="https://user-images.githubusercontent.com/37867741/38777937-566d6976-40b9-11e8-9b6f-6edb46444969.png">
<img width="755" alt="screenshot 2018-04-15 14 14 13" src="https://user-images.githubusercontent.com/37867741/38777938-56aaa8ea-40b9-11e8-9ba2-0b1688387957.png">
<img width="904" alt="screenshot 2018-04-15 14 14 49" src="https://user-images.githubusercontent.com/37867741/38777939-56e8f7e4-40b9-11e8-8e17-92e308661690.png">

I have two types of devices to control my SHADES (Lamellenjalousien) and BLINDS (Vertikalrollos): For the blinds I use KL220. They only go up and down, they have no angle functionality. For my shades I use HKL-230. They additionally have angle control.

However, the digitalstrom binding turns the two around! Now I have an angle control for my blinds (which have no angle in reality) and my shades have no angle control, but should have.

All items were autodetected. The 

## Expected Behavior
KL220 should NOT have angle control
HKL-230 MUST have angle control

## Current Behavior
The opposite of what it should be

## Possible Solution
Just flip the two

## My Environment
openHAB 2.2.0-1 (Release Build)
binding-digitalstrom - 2.2.0
Raspbian GNU/Linux 8 (jessie)

**Comment by 9037568** [comment]
You appear to be using the ESH digitalstrom binding ([https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.digitalstrom](https://github.com/eclipse/smarthome/tree/master/extensions/binding/org.eclipse.smarthome.binding.digitalstrom)).

If so, you've placed this in the wrong issue tracker. The one you want is [here](https://github.com/eclipse/smarthome/issues). If this is correct, please close this issue and open a new one over there.
