### ISSUE TITLE
[telegram] Need SOCKS5

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab1-addons#5566]
Originally posted at the openhab2-addons tracker:

https://github.com/openhab/openhab2-addons/issues/3527

> Hi! I live in Russia and we have blocked the Telegram ... Could you help with setting up SOCKS5 proxy in Telegars action?

I have put a bounty on it and will move it over to this new issue.

**Comment by martinvw** [comment]
The bounty has been moved @maintainers please update the appropriate labels 😁

The bounty is at this moment 15 but maybe others want to support this feature as well 

https://www.bountysource.com/issues/57724547-telegram-need-socks5

**Comment by ehorohorin** [comment]
I've made a dirty hack to support socks5 proxy with the latest openhab binding using native JVM capabilities: https://github.com/ehorohorin/openhab2-addons/blob/master/bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java

This change allows me to install tor and work using it (or any other socks5 server). Feel free to contact me for .jar if you have difficulties with building bindings natively.

**Comment by ehorohorin** [comment]
No more need to track it here - telegram binding 2.5 is added officially :)

**Comment by ehorohorin** [comment]
@zoolu74 look at this comment
