### ISSUE TITLE
[MQTT] special characters not supported

### ISSUE THREAD

**Issue by Rene-Auberger** [openhab/openhab1-addons#5569]
## Expected Behavior
Sending a message via MQTT which contains special characters such as German umlaut or accented characters should be converted to the correct enconding for openHAB.

## Current Behavior
Currently those messages are not received correctly. As an example when I send any text to my Echo Dot via MQTT and openHAB by sending it as topic `openHAB/in/RenesEchoDot_Erinnere/command` the message is not received correctly. Symptom: the Dot does not read the word which contains the umlaut but rather spells it and omits the umlaut. The Alexa App on my phone shows the umlaut as a question mark in a black square.

This does not happen when I trigger a reminder in a rule using `RenesEchoDot_Erinnere.sendCommand` using the exact same text. In this case the app shows everything correctly and the Dot reads everything including umlauts correctly.

The same behavior has been described in the openHAB forum at https://community.openhab.org/t/incorrect-character-encoding-in-mqtt-binding/39889

## Possible Solution
I guess this has something to do with what is described here https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.pro.doc/q003040_.htm

> The MQTT Java™ client has a convenient MqttMessage.toString method. The method treats the message payload as being encoded in the local platform default character set, which is generally UTF-8. It converts the payload to a Java String. Java has a String method, getBytes that converts a string into a byte array encoded using the local platform default character set. Two MQTT Java programs exchanging text in the message payload, between platforms with the same default character set do so easily and efficiently in UTF-8.

## My Environment

* Version used: openHAB 2.2, MQTT binding 1.11.0
* Environment name and version: Java 8
* Operating System and version: Debian 8.10

**Comment by 9037568** [comment]
Please provide a debug log that contains an occurrence of the problem.

**Comment by 8666** [comment]
You can replicate the situation by publishing text string to an MQTT topic with 3rd party client like MQTT Spy. There should be a String item in OpenHAB that is using MQTT binding to that topic. You will get <?> in any OpenHAB GUI interface.

Test string "Проблем"

**Comment by 9037568** [comment]
Second round of [test jars](https://community.openhab.org/t/incorrect-character-encoding-in-mqtt-binding/39889/12?u=namraccr) is up.

Will push code shortly...

**Comment by 8666** [comment]
It works when the flow is
MQTT -> OpenHab item

but on exit to the event bus
MQTT -> OpenHab item -> MQTT event bus ohab/out/state/item_var

it is with <?> … now

The exit was working before

I am testing on 1.83 OH

**Comment by vlatko-va** [comment]
Well, it is not completely solved. I can not transfer messages between to OH instances using MQTT event bus. Chars get scrambled.

Only MQTT > OH is working properly but not the other direction

**Comment by 8666** [comment]
Well, it is not completely solved. I can not transfer messages between to OH instances using MQTT event bus. Chars get scrambled.

Only MQTT > OH is working properly but not the other direction

**Comment by 9037568** [comment]
@vlatko-va / @8666 : You'll need to log a new defect with details of the problem you're seeing, as it's different from the one addressed by this ticket.

**Comment by 8666** [comment]
I do not know how it is different. MQTT provides an option to input data (by subscription) and exporting from OpenHab items to MQTT (by publishing).

At one point publishing a string Item with non-latin character from OpenHab to MQTT worked but in the second round of changes in the plugin, it stopped working. It is not enough to just have MQTT -> OH working, I need OH -> MQTT too. It is a show-stopper for me if I want to have two OpenHab instances to share data.

**Comment by wawa79** [comment]
> Second round of [test jars](https://community.openhab.org/t/incorrect-character-encoding-in-mqtt-binding/39889/12?u=namraccr) is up.
> 
> [Code changes](https://github.com/openhab/openhab1-addons/compare/master...9037568:mqtt?expand=1) to date are pushed.

I don't know if anyone is working on this but the org.openhab.action.mqtt JAR is also affected by the issue.

Reading all the encoding issues raised by openHAB, it would be wise to have a **diagram/wiki to summarize the logic of character encoding in Java/openHAB/Web pages**.
My first HS2 home automation system was messy on this point, then moving to Python-based system fixed character encoding and now, 12 years after, we still have to waste time on character encoding with openHAB as in the old days. Very frustrating
