### ISSUE TITLE
[ecobee1] compatible with openhab-2.3.0-SNAPSHOT ? showing "null" pin

### ISSUE THREAD

**Issue by eusblh** [openhab/openhab1-addons#5578]
on Windows 10
openhab-2.3.0-SNAPSHOT
binding-ecobee1 - 1.12.0.SNAPSHOT

instead of showing PIN to enter on ecobee website for authorization, it's returning null like this (verbatim)

[INFO ] [binding.ecobee.internal.EcobeeBinding] - # 2. Enter the PIN 'null' in My Apps within the next null minutes.

**Comment by 9037568** [comment]
ecobee binding hasn't changed in a very long time.  Don't know of any reason it wouldn't be working with the latest OH.

You should post this question in the [community forum](http://community.openhab.org). Make sure to include your configuration, as that's most likely where the problem lies.

**Comment by eusblh** [comment]
my bad. I forgot I was switching between two configured subfolders. The ecobee configurations (appkey and tokens) got out of sync between them. 
comment: it'd be nice if the ecobee1 readme gave more info on where in the Windows Registry to look to reset ecobee authentication.  I learned to search for "openhab.ecobee" to get to the right place.
my full registry location was: Computer\HKEY_USERS\*\Software\JavaSoft\Prefs\org.openhab.ecobee./D/E/F/A/U/L/T_/U/S/E/R 
(the "*" part is different for each install)
