### ISSUE TITLE
[Modbus] The question about polling

### ISSUE THREAD

**Issue by Zoolu74** [openhab/openhab1-addons#5583]
Hello! I have a device that supports only writing to the register (function 6). It does not respond to the read request (function 3).
Here is the configuration in modbus.cfg:

serial.slave24.connection=/dev/ttyAMA0:9600:8:none:1:rtu:50:50:none:none
serial.slave24.id=30
serial.slave24.type=holding
serial.slave24.start=6
serial.slave24.length=1

With this configuration I get a read error. Because the device does not know the command 3. Everything is logical. Can I set up the device so that it does not participate in reading when polling. Did it work only for writing ? 
I have not even created an item, but I'm already getting errors ...

and one more question:
I have many devices. Can I make one of them be polled every 100 ms, and others for example 5 seconds

**Comment by 9037568** [comment]
Questions should be posted in the [community forum](http://community.openhab.org).
