### ISSUE TITLE
Remove the NMA Action since the service has been shut down

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab1-addons#5587]
## Expected Behavior

The NMA action should connect to the NMA service for delivering push notifications to Android phones.

## Current Behavior

The NMA service has shutdown in response to GDPR. See https://community.openhab.org/t/gdpr-killed-notify-my-android-in-eu/45438. Note that the service has been completely shut down, not just in the EU.

## Possible Solution

Remove the NMA Action and all references to NMA in the docs.

## Steps to Reproduce (for bugs)

NA

## Context

NA

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
NA

**Comment by 9037568** [comment]
PR created. I also excised references from the OH1 wiki pages.
Not sure how the process works for the OH2 docs site. It may need a manual intervention.

**Comment by rkoshak** [comment]
The OH 2 docs site pulls them from here so once the README.md file is gone for the Action it should go away in OH 2 docs. Unless there is a part of the process I don't understand. 

Thanks!

**Comment by kaikreuzer** [comment]
correct!
