### ISSUE TITLE
[Epsonprojector] TCP/IP connection handshake needed

### ISSUE THREAD

**Issue by tbraune42** [openhab/openhab1-addons#5604]
Epson Projector is not working over TCP/IP due to missing handshake. see kb.epson.eu 7914: How to Send ESC/VP.net Commands to a Projector 

To connect to port 3629, initial must send the code:  "45 53 43 2f 56 50 2e 6E 65 74 10 03 00 00 00 00 " To the projector to respond to requests.

The corresponding code could be inserted in the EpsonProjectorTcpConnector.java code

declaratiion:
String handshake = "ESC/VP.net\0x10\0x03\0x00\0x00\0x00\0x00";

in the coonect() procedure after line 53:
out.write(handshake.getBytes());
out.flush();

Unfortunately, I'm too stupid to compile this myself and upload it to git.

**Comment by paulianttila** [comment]
@tbraune42, binding doesn't currently support Epson TCP/IP protocol, but serial protocol directly or via TCP/IP link. So current TCP/IP support just make possible to use serial port / TCP converters.

**Comment by tbraune42** [comment]
but if you just add my suggestions it should directly work. because the whole tcpip routines are already implemented. there is no difference between ESC/VP and ESC/VP.net and the ip code is already implemented in the bundle. only the correct "handshake" is missing in the code.

**Comment by tbraune42** [comment]
so i did some quick and dirty coding and as expected it is possible to direct connect to the projector with a little changed is EpsonProjectorTcpConnector.java.
sadly i am not able to run the epsonprojector binding directly in eclipse. is there a "Special" tick to do that? otherwise i would like to Change to Code accordeatly and upload it to git. any clue, why i can not run this binding in eclipse? i have enabled it in to run config of course

**Comment by tbraune42** [comment]
I have come a lot further here and will now adjust the binding accordingly. Maybe this is still interesting for other people.

**Comment by l1t7l3ph0o7** [comment]
Hey, I was wondering if you've made any progress on this? I have an epson home cinema 1060 projector I would also like to control via IP (as it has no rs-232 port and is wifi only). unfortunately I don't have the skillsets to make the changes you mention, do you think you could walk me through it? All I wish to accomplish is to know the current state of the project (on or off) and be able to turn it ON or OFF via openhab. I'd really appreciate it.

**Comment by tbraune42** [comment]
please see here. https://github.com/tbraune42/compiled-addons
you have to manually install this addon
please use port 3629 in config file

**Comment by l1t7l3ph0o7** [comment]
Thanks, Ill give it a try when I get home this evening

**Comment by l1t7l3ph0o7** [comment]
Can you please post an example of a valid config file? I'm having trouble understanding what to put in there, In the documentation there is only info for serial connections, Do you happen to have any documentation?

**Comment by l1t7l3ph0o7** [comment]
OK, after a bit the config file auto generated I put in my configuration, but I get these warnings:
`2018-08-25 22:31:19.950 [WARN ] [ector.internal.EpsonProjectorBinding] - given config key 'localtime' does not follow the expected pattern '<id>.<host|port>'

2018-08-25 22:31:19.953 [WARN ] [ector.internal.EpsonProjectorBinding] - given config key 'password' does not follow the expected pattern '<id>.<host|port>'

2018-08-25 22:31:19.956 [WARN ] [ector.internal.EpsonProjectorBinding] - given config key 'reconnectCnt' does not follow the expected pattern '<id>.<host|port>'

2018-08-25 22:31:19.958 [WARN ] [ector.internal.EpsonProjectorBinding] - given config key 'url' does not follow the expected pattern '<id>.<host|port>'

2018-08-25 22:31:19.961 [WARN ] [ector.internal.EpsonProjectorBinding] - given config key 'user' does not follow the expected pattern '<id>.<host|port>'`

And I have no control

My config looks like this:
`# Serial port or Host and port of the first Epson projector to control 
LRProjector.host=192.168.137.17
# Port of the Epson projector to control (optional, defaults to 60128)
LRProjector.port=3629`
And my Items:
Switch EpsonPower    { epsonprojector="LRProjector:Power:60000" }

**Comment by 9037568** [comment]
It's about time to take this discussion to a [discussion forum](http://community.openhab.org/).

**Comment by gytisgreitai** [comment]
Thanks @tbraune42 your patched version works fine. Why don't you want to submit this as PR into main branch?
