### ISSUE TITLE
[InsteonPLM] error malformed bufferstatus.xml

### ISSUE THREAD

**Issue by dgagnon-rdx** [openhab/openhab1-addons#5608]
## Current Behavior

the log is full of this:

08:58:49.755 [ERROR] [onplm.internal.driver.hub.HubIOStream] - got exception while polling: java.io.IOException: malformed bufferstatus.xml
08:58:50.755 [ERROR] [onplm.internal.driver.hub.HubIOStream] - got invalid buffer status: 403 Forbidden: SSL Required - use HTTPS

08:58:50.784 [ERROR] [onplm.internal.driver.hub.HubIOStream] - failed to write to hub: java.io.IOException: malformed bufferstatus.xml
08:58:50.789 [ERROR] [onplm.internal.driver.hub.HubIOStream] - got invalid buffer status: 403 Forbidden: SSL Required - use HTTPS

## Possible Solution

My Insteon Hub received an update to version 1016 last monday.

**Comment by dgagnon-rdx** [comment]
[Release notes from Insteon 
](https://www.insteon.com/support-knowledgebase/2015/5/6/insteon-hub-release-notes
)
Version 1016
This version of the Insteon Hub firmware fixes stability issues that improve 3rd party integrations such as Amazon Alexa and include miscellaneous security fixes. This update is being released on June 19, 2018 and automatically installed.

**Comment by jsetton** [comment]
You can refer to [this forum thread](https://community.openhab.org/t/insteon-update/46665/24). This is indeed related to the latest firmware update. Insteon acknowledged the issue and are saying that they are working on releasing a new firmware to fix this although no timeline was given.
