### ISSUE TITLE
[Milight][Documentation] Update wiki API link 

### ISSUE THREAD

**Issue by Fantasmos** [openhab/openhab1-addons#5610]
For the page: https://github.com/openhab/openhab1-addons/wiki/milight-binding

The text (See the API) links to http://www.limitlessled.com/dev/ which appears to be down.  I have made an archive of this page at: https://github.com/Fantasmos/LimitlessLED-DevAPI which should be used in place.

**Comment by 9037568** [comment]
Will you be submitting a PR to update the README file?

**Comment by Fantasmos** [comment]
As https://github.com/openhab/openhab1-addons/wiki/milight-binding is a wiki page, i'm unsure how to do so.

**Comment by Fantasmos** [comment]
I figured it out, PR is at: https://github.com/openhab/openhab1-addons/pull/5611

**Comment by 9037568** [comment]
I have updated the wiki page with this change.

Thanks for contributing it.
