### ISSUE TITLE
Omnilink Binding - Mute not controlling Audio Source

### ISSUE THREAD

**Issue by mjcumming** [openhab/openhab1-addons#5618]
I have a Russound controller connected to my Omni 2 panel. Everything works correctly via the controller.

I am having problems with Mute not changing the setting on the Russound. Additionally, I do not see any Mute events in the logger with local control of the Mute setting.

With local control of the Mute setting, there a volume event instead - changing the volume to 0 when using local control and back to the previous setting with Mute Off.

**Comment by 9037568** [comment]
Questions like this should be posted in the [community forum](http://community.openhab.org/).
