### ISSUE TITLE
[IPX800] OH2 does not reconnect on IPX800 reboot

### ISSUE THREAD

**Issue by bchabrier** [openhab/openhab1-addons#5622]
When I reboot my IPX800, OpenHab looses the connection and does not recover.

## Expected Behavior

I would expect OpenHab to retry connecting.

## Current Behavior

IPX800 relay changes are no more recognized by OpenHab2

## Possible Solution

Looking at the code in `Ipx800DeviceConnection.java`, it seems that`in.readLine()` returns a `null` pointer, raising a `NullPointerException` which kills the KeepAlive.

## Steps to Reproduce (for bugs)

1. Change IPX800 relays, they are recognized by OH2
2. Unplug your IPX800, wait 10 seconds
3. Replug the IPX800, wait for it to reboot
4. Change IPX800 relays, they are no more detected by OH2

## Your Environment

* Version used: (e.g., openhab and addon versions)
OpenHab 2
IPX800 1.12.0
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
I am using OpenHab2 on Raspbian Jessie

**Comment by 9037568** [comment]
Please attach configurations and a debug log.

**Comment by bchabrier** [comment]
In fact it works correctly now, when I try to get a debug log ?!?!? I don't know why it didn't work...

So I close this issue and will reopen if needed.

Thanks!
