### ISSUE TITLE
[MQTT Persistence] Add feature: additional parameter for the hostname of the openhab device

### ISSUE THREAD

**Issue by preinhardt** [openhab/openhab1-addons#5634]
## Expected Behavior

If I use the MQTT binding with the persistence service, I would like to have a parameter (5$) which are reformatted using String.format at the time of publishing with the hostname of the openhab device.

## Current Behavior

Unfortunately, there is currently not possibility to set the hostname automatically in the topic and the message. The workaround is to set this manually.

## Possible Solution

I would expand the MqttPersistencePublisher class in the org.openhab.persistence.mqtt package with the additional parameter.

This issue is a question of whether the improvement would be approved if I make a pull request.
If the response is positive, I already have working code to implement these features and plan to shortly submit a pull request.

**Comment by 9037568** [comment]
I don't really understand what you're trying to do with such a modification.

I suggest starting a thread in the community forum. It could be there's an existing way to achieve your goal. Or if not, it's a great way to clarify what you're trying to do.

But if you should choose to submit a PR, it will be given full consideration.
