### ISSUE TITLE
[Dropbox] The binding should be removed since it is not working anymore

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [openhab/openhab1-addons#5637]
The Dropbox binding is a "featured" binding on the new admins page 
https://www.openhab.org/addons/

although the docs clearly state that 

"This service no longer exists. It was written to work with the original Dropbox API, which is now retired. An update for OH2/ESH is in progress but not completed.".

If it is not working, it should not be part of the openHAB bindings listing in my opinion, as it confuses the user. 
And, it should certainly not be a featured binding.

**Comment by kaikreuzer** [comment]
Thanks for the notice, this is very true.
I have created https://github.com/openhab/openhab1-addons/pull/5638 to remove it.

**Comment by kaikreuzer** [comment]
Furthermore created https://github.com/openhab/website/pull/93 to make it disappear from the website.
