### ISSUE TITLE
Unused Maven properties

### ISSUE THREAD

**Issue by wborn** [openhab/openhab1-addons#5642]
The openhab1-addons POMs also contain the now unused `bundle.namespace` and `bundle.symbolicName` properties (see https://github.com/eclipse/smarthome/issues/6060). Should we remove them in this repository as well @kaikreuzer? 

Many POMs also contain deb. properties:

https://github.com/openhab/openhab1-addons/blob/7f4e000ed71543f1c8124f7cbba27783c84aa528/bundles/binding/org.openhab.binding.xpl/pom.xml#L9-L15

I think they are no longer used for creating debian packages?

The deb.depends may still contain useful information for creating features. Most bindings already have a feature for OH2 that defines the dependencies, except for the following:

| Project                             | deb.depends             |
|-------------------------------------|-------------------------|
| org.openhab.action.xpl              | openhab-addon-io-xpl    |
| org.openhab.binding.davis           | openhab-addon-io-serial |
| org.openhab.binding.em              | openhab-addon-io-cul    |
| org.openhab.binding.fht             | openhab-addon-io-cul    |
| org.openhab.binding.oceanic         | openhab-addon-io-serial |
| org.openhab.binding.rfxcom          | openhab-addon-io-serial |
| org.openhab.binding.rme             | openhab-addon-io-serial |
| org.openhab.binding.stiebelheatpump | openhab-addon-io-serial |
| org.openhab.binding.xpl             | openhab-addon-io-xpl    |
| org.openhab.persistence.db4o        | openhab-runtime         |
| org.openhab.persistence.sitewhere   | openhab-runtime         |

If the debian package information is removed we could perhaps also remove the org.vafer:jdeb build plugin tags from the POMs?

https://github.com/openhab/openhab1-addons/blob/7f4e000ed71543f1c8124f7cbba27783c84aa528/bundles/binding/org.openhab.binding.xpl/pom.xml#L25-L32

**Comment by kaikreuzer** [comment]
I agree, I do not see any reason to keep those properties and the jdeb plugin in the poms - happy to have them removed 👍 .
