### ISSUE TITLE
KNX Binding - maximum send attempts error

### ISSUE THREAD

**Issue by dennys78** [openhab/openhab1-addons#5666]
I have this message in the logs :
**changed from OFFLINE (COMMUNICATION_ERROR): maximum send attempts to OFFLINE (COMMUNICATION_ERROR): timeout connecting to control endpoint**

And this :
KNX Binding - maximum send attempts error
I Try new installation and test different type of connection, TUNNEL and ROUTER but nothing!!!

I’m about to go crazy! please help me !!

**Comment by 9037568** [comment]
Check your network connections, then start a discussion in the [community forum](http://community.openhab.org/).
