### ISSUE TITLE
pairing energenie sockets with pi

### ISSUE THREAD

**Issue by mstewart81** [openhab/openhab1-addons#5687]
I have the openhab 2.3.0-1 installed on pi with the energenie 314 HAT.
I am new to raspberry pi and openhab.
I have looked on the openhab script but can't seem to find the start of the pairing process for the sockets.
I also have radiator TRV that will need pairing what is the id's for the thermostats
thanks

**Comment by 9037568** [comment]
You should post this question in the [community forum](http://community.openhab.org/).
