### ISSUE TITLE
[Telegram] Missing example for message with format and args

### ISSUE THREAD

**Issue by fex01** [openhab/openhab1-addons#5691]
The [Telegram Action documentation](https://www.openhab.org/addons/actions/telegram/#prerequisites) does mention the following option:

> sendTelegram(String group, String format, Object... args): Sends a Telegram via Telegram REST API - build message with format and args

But without any examples or further explanation I do not see how to use this option...

**Comment by 9037568** [comment]
If you had read the document, you would have seen [this example](https://www.openhab.org/addons/actions/telegram/#send-a-text-message-with-a-formatted-message).
