### ISSUE TITLE
[telegram] 404 error

### ISSUE THREAD

**Issue by Homer-Sim** [openhab/openhab1-addons#5695]
Hi,

This is my config:

`# Read http://www.instructables.com/id/Telegram-Bots-for-beginners/`
`# to see how to set up bots and find your chat ids`
`# bots=bot1,bot2`
`bots=heinz,kathleen`
`# Handy Heinz S7 Active`
`heinz.chatId=753770147`
`heinz.token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX`
`# Handy Kathleen iPhone`
`kathleen.chatId=760677197`
`kathleen.token=XXXXXXXXXXXXXXXX`

and this is my rule entry:

`sendTelegram("heinz", "Trockner ist fertig!")`
`sendTelegram("kathleen", "Trockner ist fertig!")`

But I am receiving in openhab log this error:
`[WARN ] [ab.action.telegram.internal.Telegram] - Method failed: HTTP/1.1 404 Not Found`

Do you know where to look for a solution?

Thanks

**Comment by 9037568** [comment]
A debug log is always the first place to look. The [community forum](http://community.openhab.org) is always the second.
