### ISSUE TITLE
[Telegram] Photo URL doesn't allow file:// protocol

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab1-addons#5713]
I get an error (invalid base64 image) when trying to send a jpg image that is stored locally on the openHAB filesystem. The URL is defined using the file:// protocol as:
```
file:///path/to/directory/with/image.jpg
```

I see that the telegram code only checks that the URL starts with `http`. Is there a reason why `file` (or possibly even `https`) are not allowed?
https://github.com/openhab/openhab1-addons/blob/master/bundles/action/org.openhab.action.telegram/src/main/java/org/openhab/action/telegram/internal/Telegram.java#L186

Would you entertain a PR that enables the use of the `file://` protocol?

**Comment by 9037568** [comment]
Well, `https` should already be allowed, but I agree it would be good to allow `file` also.
If you can confirm the change works, it should be easy to get included.

**Comment by mhilbush** [comment]
> https should already be allowed

Ah, right, because it checks for http... 👍 

I run a test using file. If I confirm it works I'll submit a PR. Thanks!

**Comment by mhilbush** [comment]
Sadly, HttpClient doesn't support the file protocol. Closing this.
