### ISSUE TITLE
[Novelanheatpump] Wrong results for state, extended_state and massflow

### ISSUE THREAD

**Issue by moodsta** [openhab/openhab1-addons#5727]
I am currently trying to get some measurements from my Novelan heatpump done with openhab, influxdb and grafana.
All usual temperature values are being read out from Novelan and stored successfully in influxdb, however I can not get useful data from the following items:

    state
    extended_state
    massflow

examples:

state always returns Wärmepumpe läuft: 00:00:00
extended_state always returns Heizbetrieb: 00:00:00
massflow always returns 0

All other temperatures return correct values. I am using port 8889, SW version of Novelan controller is v3.83.1
Tried to get some help in Openhab community but they are also lost. Followed everything in the binding documentation. I am using latest openhab2 via openhabian image.

**Comment by 9037568** [comment]
This really belongs in the forum, but I'll leave this open temporarily in case you can attach a valid debug log.

**Comment by moodsta** [comment]
Thanks for waiting. Just captured a Debug openhab.log and event.log but there are no further details. It just sets the value to the one mentioned above,
[openhab.log](https://github.com/openhab/openhab1-addons/files/2661045/openhab.log)
[events.log](https://github.com/openhab/openhab1-addons/files/2661046/events.log)

**Comment by 9037568** [comment]
Values are being interpreted correctly.  See [this community thread post](https://community.openhab.org/t/novelan-heatpump-binding-doesnt-reply-useful-values-for-state-extended-state-and-massflow/58989/26?u=namraccr) for details.
