### ISSUE TITLE
rtl_433 mqtt api

### ISSUE THREAD

**Issue by merbanan** [openhab/openhab1-addons#5734]
Hi, we are working on a MQTT api for rtl_433. The payload will be the json that rtl_433 always have been outputting. But is there any preference on how the topics are generated? I know very little about OpenHab internals but if there are any structure that would be useful for OpenHab integration I am interested to hear about those.

**Comment by 9037568** [comment]
You should ask this question in the [community forum](http://community.openhab.org/).
