### ISSUE TITLE
[mySQL Persistence] No connection to DB, SQLException: The server time zone value 'AEDT' is unrecognized.

### ISSUE THREAD

**Issue by dp3049** [openhab/openhab1-addons#5739]
## Expected Behavior
Successful connection to the persistence DB (mySQL) to allow persistence information to be stored in the DB.

## Current Behavior
This behaviour only started being exhibited following an in-place update from OH2.4 M8 to OH2.4.0 Stable. No other system or config changes were made, reverting back to M8 resolves the issue.

On OH startup, as devices are being brought up, persistence fails with the following error messages in the log:
```
Loading class com.mysql.jdbc.Driver'. This is deprecated. The new driver class iscom.mysql.cj.jdbc.Driver’. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

No connection to database. Cannot persist item 'light_study (Type=DimmerItem, State=100)'! Will retry connecting to database when error count:0 equals errReconnectThreshold:0

14:20:41.388 [ERROR] [ysql.internal.MysqlPersistenceService] - mySQL: Failed connecting to the SQL database using: driverClass=com.mysql.jdbc.Driver, url=jdbc:mysql://localhost:3306/OpenHAB, user=openhab2

java.sql.SQLException: The server time zone value 'AEDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
```

## Steps to Reproduce (for bugs)
1.Build a working OH2.4 M8 environment, with mySQL persistence add-on,
2.update using the OH update command to 2.4.0 stable.
3.
4.

## Context
Persistence data fails to be written to the mySQL database following update.

## Your Environment
* Version used: (fails) 2.4.0 Stable
* Version used: (works) 2.4.0-SNAPSHOT Build #1399
* Bindings:
  + zwave
  + Nest
  + Wemo
  + MQTT
* Services:
  + OpenHab Cloud
  + mySQL Persistence
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
  + Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
  + Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
  + mySQL: 5.7.18 MySQL Community Server (GPL)
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
  + OS X 10.14.2 (Mojave)

**Comment by mhilbush** [comment]
This might be a duplicate of [this](https://github.com/openhab/openhab1-addons/issues/5706)? If a restart of the mySQL service clears the problem, this it's the same issue.

**Comment by dp3049** [comment]
@mhilbush  it does appear to be related, however, the system has been rebooted several times while running 2.4.0 stable. And as mentioned, 2.4.0 M8 consistently does not exhibit the issue, switching back to 2.4.0 stable and it consistently fails.

**Comment by mhilbush** [comment]
It might help to post the entire stack trace. That may help show the difference between the two problems.

**Comment by 9037568** [comment]
You should try setting the right timezone.

**Comment by dp3049** [comment]
@9037568 Thanks Chris, I've checked the timezone set in OH and it is correct: Australia/Melbourne. This must translate somehow to the international time zone abbreviation of AEDT, which is also correct for my location, but is being rejected by either the driver or the DB. Also, the exact same configuration has worked for me from 2.2, 2.3, 2.4 early snapshots, and Milestone 8; I've always just done in-place updates (although 2.4 snapshot was a rebuild due to zwave changes, however all the config files (.items, etc) were copied across to 2.4). But thank you for your suggestion.

**Comment by lewie** [comment]
@dp3049, 
some parameters that can be set for JDBC Driver:
``` 
jdbc:mysql://[yourIP]:3306/[yourDBNAME]?verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=UTC
```

**Comment by dp3049** [comment]
Thanks Helmut, where do I put those parameters? Is there a cfg file they should go in? Thanks.

**Comment by dp3049** [comment]
Further info:
In my case, the MySQL system variable “time_zone” is set to “SYSTEM”, therefore the MySQL instance is using the OS timezone setting. On my system (OS X - Mojave), this is set to AEST (Australian Eastern Standard Time).
OH timezone setting: Australia/Melbourne
OH (2.4.0 stable) is somehow translating “Australia/Melbourne” to AEDT (Australian Eastern Daylight Time), which is a valid timezone value however this fails.
OH (2.4.0 M8) does not fail - does anyone know how to see/view the parameters passed from OH to MySQL via jdbc? I’d like to review what the difference between M8 and stable.

**Comment by mhilbush** [comment]
> does anyone know how to see/view the parameters passed from OH to MySQL via jdbc? 

Try putting the mysql persistence bundle into debug mode.
```
log:set DEBUG org.openhab.persistence.mysql
```

**Comment by lewie** [comment]
Alternatively use the more modern `org.openhab.persistence.jdbc` for Mysql. 

I wrote the bundle as a replacement for the good old mysql binding. Many databases are integrated. Very good debugging! More modern techniques have been used and it is much faster. An existing old database can also be migrated.

**Comment by dp3049** [comment]
Thanks Helmut,

I've switched over to jdbc for MySQL binding. I just left the database 'as-was' and configured the jdbc driver to be backwards compatible. I did have to disable SSL in the command parameters:
`url=jdbc:mysql://localhost:3306/OpenHAB?useSSL=false`
All seems to be working now. It is a very strange thing indeed that it worked in M8 and not stable, and I do not like leaving this unanswered - however the fix, at this stage, is to move to the jdbc binding for MySQL. 

I will leave the issue open for a few days while I complete configuring a few more items and test that persistence is working properly. 

Thanks again Helmut, and Merry Christmas.

**Comment by dp3049** [comment]
Hi Helmut, all seems to be going well. I notice there is an option to convert table names. So my last question is, is there any benefit to converting table names to that of the actual ‘items’? Seems there would be a performance benefit as there would be no item lookup. What’s your thoughts on this please?

Thanks.

**Comment by lewie** [comment]
@dp3049, definitely no benefit or anything! I integrated this option for better readability of the table-names while debugging. 

If you do that, be careful for ‘items’ or ‘Items’! ;-)

**Comment by dp3049** [comment]
Hi, 
Jeremy @JRB123 posted a solution to a community post, as follows:
[https://community.openhab.org/t/after-update-to-2-4-0-stable-i-get-jdbc-driver-class-is-deprecated/60294/16]

_JRB123
Jeremy
1h
I was able to keep using the MySQL persistence binding by importing the timezone tables into the MySQL server, then adjusting the DB timezone to match that of OH.

Look here for the info on importing timezone tables.

then edit /etc/mysql/my.cnf and add:

```
[mysqld]
default-time-zone=‘Australia/Melbourne’
```

and restart._

Big thanks to Jeremy.
