### ISSUE TITLE
[Pilight] Not included in any feature. Not installable via normal binding installation methods

### ISSUE THREAD

**Issue by t-8ch** [openhab/openhab1-addons#5742]
It seems the pilight binding is not included in any of the karaf features/binding indices.
This means it cannot be installed easily via the addon UI.
I had to dig my way through the maven repo and get the the Jar file manually.

Is this intentional?

## Expected Behavior

Pilight binding is installable via addon browser from inside openHAB.

## Current Behavior

Pilight binding cannot be found in openHAB addon browser.
(The [old wiki page](https://github.com/openhab/openhab1-addons/wiki/pilight-Binding) advises to get the the addon from the download page, but it is included in none of the addon bundles)

## Possible Solution

Adding the binding to `features/openhab-addons-legacy/src/main/feature/feature.xml` may be enough. (Not an expert on karaf).

## Steps to Reproduce (for bugs)

Download the openHAB 2.4.0 distribution, addons and legacy-addons from the website.
The pilight binding is not included.
Search for the pilight binding from the addon page, it is not found.

**Comment by sebastian-h** [comment]
hi there, just to add that i was fighting pilight-binding today also. the solution to multiple spurious NPEs with versions 1.8.3 and 1.9-SNAPSHOT from some google drive was to dig out the latest version of pilight-binding from here:  https://bintray.com/openhab/mvn/openhab1-addons/1.13.0#files/org%2Fopenhab%2Fbinding%2Forg.openhab.binding.pilight%2F1.13.0 

**everything seems to work now**. i think this plugin could be listed for a better user-experience.
