### ISSUE TITLE
[FritzboxTr064] maconline not working

### ISSUE THREAD

**Issue by Torsten555** [openhab/openhab1-addons#5770]
Hi,

I am using Openhab v. 2 together with the Fritzboxtr064 binding v1.13.0.

The maconline functionality is not working for me even though that MAC is online also shown online in the WebUI:

Item configuration:
Contact cFboxMacOnline "Presence (WiFi) [%s]" {fritzboxtr064="maconline:11-22-33-44-55-66"}

With debug logging enabled, the following message shows up in the logs:
2019-01-14 22:45:53.232 [DEBUG] [ing.fritzboxtr064.internal.Tr064Comm] - MAC not known to FritzBox!

I have tried different devices with their MAC addresses, all of them showing online on the UI. I have also tried deleting the device on FritzBox's webUI but it did not help either.

This was already discussed in the OpenHAB community here: 
https://community.openhab.org/t/fritzboxtr064-binding-cannot-check-presence-of-device-in-network/64031/18

Any further ideas?

Best, Torsten

**Comment by SAQ1973** [comment]
Same here, tested with 1.14.0.M1 and 1.11 on FRITZ!OS 07.08-64611 BETA on a Fritz!Box 7590.
Last working binding is 1.10. (I just realized, 1.11 was never working for me even on Fritz!OS 6.92).

**Comment by SAQ1973** [comment]
Please note that FRITZ!OS 07.0x currently has a bug when repeaters are in use (1750E in my case): If your wifi device (let's say an iPhone) is connected to a repeater that is connected to the FRITZ!Box, an the iPhone's wifi is switched to off, the FRITZ!Box will continue to keep the iPhone in the devices connected list with a LAN (sic!) connection.

**Comment by 9037568** [comment]
Need the config file and debug logs. Please **attach** them and do not paste them.

**Comment by Torsten555** [comment]
Sorry. As they did not seem to be any help available I had already removed the binding and switched to a different solution.

**Comment by SAQ1973** [comment]
@Torsten555: You should not close the issue just because of you found a different solition for yourself. The issue is still there for other users. Please reopen it.
Stefan

**Comment by 9037568** [comment]
@SAQ1973 if you can provide the requested configs and logs, I can reopen this for you.
