### ISSUE TITLE
[OpenWeatherMap] Capitalize first letter of strings

### ISSUE THREAD

**Issue by BasvanH** [openhab/openhab1-addons#5776]
The capitalization of the first letters of strings is not consistent. Sometimes it is captilized, sometimes it isnt. Please make it consistent and always capitalize the first character of a string.

## Expected Behavior
Condition

## Current Behavior
condition

## Possible Solution
Change code to always capatilize the first character of a string.

## Your Environment
openHAB 2.5.0 Build 1493

**Comment by 9037568** [comment]
Are you sure you're in the right place? Is this about the OWM provider in the Weather binding for OH1, or about the OWM binding in OH2?

If this is about the former, please provide a concrete example of the strings you're talking about.

**Comment by BasvanH** [comment]
Ah, I see, sorry. It's for the OH 2 addons. I will create a new issue there.
