### ISSUE TITLE
Mqttiude1 -openHAB 2.5.0 Build #1542

### ISSUE THREAD

**Issue by Prinsessen** [openhab/openhab1-addons#5825]
After update to openHAB 2.5.0 Build #1542, Openhab fails to start.

I removed the mqttitude1 binding from:
/var/lib/openhab2/config/org/openhab/addons.config to get Openhab running after the update.

```
This is the error in Karaf

20:00:57.755 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed installing ' openhab-binding-mqttitude1': Unable to resolve root: missing requirement [root]
```

**Comment by martinvw** [comment]
Seems to be related to https://github.com/openhab/openhab-core/issues/614 if we have a new snapshot it should be resolved.
