### ISSUE TITLE
caldavio documentation out of date

### ISSUE THREAD

**Issue by slycker** [openhab/openhab1-addons#5861]
Re: Caldav, caldav-Personal (etc)

As discussed on https://community.openhab.org/t/troubleshooting-caldav-personal-public-garbage-collection-calendar/
caldavio config information is old, refers to openhab.cfg, and there seems to be some discrepancy on if caldavio: prefix is needed before items in the caldavio.cfg file.

Does the caldavio.cfg file need a usedCalendars item, or is this just for caldavPersonel ?  Ideally there should be a section on this file in the documentation, specifying what is required.

Finally, there doesn't seem to be much debugging/logging at all.  A failed calendar load should result in a logged error (ideally with information about why it failed- failed authentication, failed parsing the calendar file, etc).

==
Openhabian 2.4 on a R Pi 3B, system regularly updated
Connecting to a publically available calendar file without any authentication required.  Link above provides some specific details.
This issue is posted mostly to get the documentation and hopefully logging improved.

Thanks for the work you do!

**Comment by 9037568** [comment]
Discussion belongs in the community forum. When you find a defect, you can log it here.
