### ISSUE TITLE
How to ignore SSL check for sendTelegramPhoto?

### ISSUE THREAD

**Issue by joshuakoh7** [openhab/openhab1-addons#5864]
I'm trying to send a currentpic.cgi capture from my IP cam that requires authentication over a self-signed SSL. Running into the following error. How do I turn off the SSL check that I can easily skip when I'm using a browser?

```
Transport error: {}

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by 9037568** [comment]
You should ask this question in the [community forum](http://community.openhab.org). Or better, search the forum for this error. It may already have suggestions for you.

**Comment by joshuakoh7** [comment]
It's not a question, there needs to be an option to disable SSL checking. The only workaround right now is to reverse proxy it through nginx to strip away https which is counterproductive for a camera.
