### ISSUE TITLE
[Build] Type mismatch: cannot convert from CommPort to SerialPort

### ISSUE THREAD

**Issue by marekhalmo** [openhab/openhab1-addons#5873]
Hello,
when i do a fresh clone of openhab1-addons [master] directory and try mvn clean install on root i get following error

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.0.0:compile (default-compile) on project org.openhab.binding.satel: Compilation failure: Compilation failure:
[ERROR] C:\Projects\OpenHab\clean build\openhab1-addons\bundles\binding\org.openhab.binding.satel\src\main\java\org\openhab\binding\satel\internal\protocol\IntRSModule.java:[68,-1]
[ERROR] 1. ERROR in C:\Projects\OpenHab\clean build\openhab1-addons\bundles\binding\org.openhab.binding.satel\src\main\java\org\openhab\binding\satel\internal\protocol\IntRSModule.java (at line 68)
[ERROR] SerialPort serialPort = portIdentifier.open("org.openhab.binding.satel", 2000);
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from CommPort to SerialPort

Can anyone help?

**Comment by 9037568** [comment]
Is there a reason you're not using the [OH2 satel binding](https://github.com/openhab/openhab2-addons/tree/master/bundles/org.openhab.binding.satel)? Just curious.

If you build from within the satel binding root, do you get the same error? Mine build fine from there. I'll try building from root to see if I get the same problem you're seeing.

**Comment by 9037568** [comment]
Build ran clean from the root of the project, too.

**Comment by marekhalmo** [comment]
Hello, thank you for help. Can you please tell me how you build the addons project?
I use "mvn clean install" where i have two folders, one with "addons" and one with "openhab"

**Comment by marekhalmo** [comment]
> 
> 
> Is there a reason you're not using the [OH2 satel binding](https://github.com/openhab/openhab2-addons/tree/master/bundles/org.openhab.binding.satel)? Just curious.
> 
> If you build from within the satel binding root, do you get the same error? Mine builds fine from there. I'll try building from root to see if I get the same problem you're seeing.

I don't need satel binding. I need to modify serial binding from addons1. Satel binding is causing my build to crash.

**Comment by 9037568** [comment]
You could try commenting out the satel binding so that it doesn't get built.
For additional help, I suggest asking in the community forum.

**Comment by marekhalmo** [comment]
Ok. I will try that.Thank you!

**Comment by marekhalmo** [comment]
Hello, tried that but id did not work. 
Same issue is popping out on the serial binding.

Can anyone help me fix this build issue?

Thank you!

**Comment by marekhalmo** [comment]
Hello, tried that but id did not work. 
Same issue is popping out on the serial binding.

Can anyone help me fix this build issue?

Thank you!

**Comment by marekhalmo** [comment]
Hello, i still can't build anything.. Can anyone help?
