### ISSUE TITLE
[Comfoair] Broken since update to 2.5M2

### ISSUE THREAD

**Issue by BoBiene** [openhab/openhab1-addons#5892]
## Expected Behavior
I have a Zehnder Comfoair 350 and the integration worked well until i did the update to the 2.5 M2 Build.

## Current Behavior
The only log-message i receive is 
[INFO ] [b.core.service.AbstractActiveService] - ComfoAir Refresh Service has been started

And after that i get nothing related to the comfoair.
Maybe it is related to the changes by @gieemek in this Pullrequest https://github.com/openhab/openhab1-addons/pull/5773?

**Comment by bechte** [comment]
I think this issue can be closed. I also have a CA350 and the integration works almost perfect with the 2.5.2.1 release.
