### ISSUE TITLE
Move to legacy?

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab1-addons#5895]
The hue, harmonyhub, samsungtv, bluetooth, and squeezebox addons all have 2.x versions, but for some reason have not been moved to legacy. Were these just missed or is there a reason?

**Comment by paulianttila** [comment]
Here is some discussion about samsungtv and rfxcom bindings. 

https://github.com/openhab/openhab1-addons/pull/5564

**Comment by openhab-5iver** [comment]
OH 1.x addons are now removed, so closing.
