### ISSUE TITLE
[weather-binding] Apixu is now weatherstack!

### ISSUE THREAD

**Issue by cniweb** [openhab/openhab1-addons#5897]
see: https://github.com/apilayer/weatherstack#readme
API-Key for Apixu provider is now weatherstack!

**Comment by kaikreuzer** [comment]
Done.

**Comment by cniweb** [comment]
You are right:
https://www.openhab.org/addons/bindings/weather1/#api-keys-for-weather-providers

**Comment by digitalewelt** [comment]
Has the binding for Weatherstack been adjusted yet? Does the WeatherStack API work with the config of the APIXU key?

**Comment by 9037568** [comment]
@digitalewelt Questions should be asked in the forum.
