### ISSUE TITLE
[http] http binding incorrectly decodes url when url contains encoded colon OH 2.5

### ISSUE THREAD

**Issue by Dem72** [openhab/openhab1-addons#5940]
## Expected Behavior
I need to use the url such
http://192.168.88.247/sec/?pt=6&cmd=6A:1  for switch item On   
http://192.168.88.247/sec/?pt=6&cmd=6A:0  for switch item On  
My http.items case1
```csv
Switch MySwitch1 { http=">[ON:GET:'http://192.168.88.247/sec/?pt=6&cmd=6A:1'] >[OFF:GET:http://192.168.88.247/sec/?pt=6&cmd=6A:0]" }
```
It doesn't work because this gets cut off at the colon after the cmd=6A because colon character is used as delimiter in item describing for http binding

> [DEBUG] [ab.binding.http.internal.HttpBinding] - Executing url 'h_ttp://192.168.88.247/sec/?pt=6&cmd=6A' via method GET

This issue was solved here:
[https://community.openhab.org/t/colon-in-http-binding/26516](https://community.openhab.org/t/colon-in-http-binding/26516)

I try http.items case2
```csv
Switch MySwitch1 { http=">[ON:GET:http://192.168.88.247/sec/?pt=6&cmd=6A%%3A1] >[OFF:GET:http://192.168.88.247/sec/?pt=6&cmd=6A%%3A0]" }
```
or http.items case3
Switch MySwitch1 { http=">[ON:GET:http://192.168.88.247/sec/?pt=6&cmd=6A%3A1] >[OFF:GET:http://192.168.88.247/sec/?pt=6&cmd=6A%3A0]" }

I expect to get url string on device such http://192.168.88.247/sec/?pt=6&cmd=6A:1

## Current Behavior
I get url without decoding, in the same encoded form.
![case2](https://user-images.githubusercontent.com/61103209/74610859-a39bca00-50ff-11ea-9a4c-84ea6350083d.png)
![case3](https://user-images.githubusercontent.com/61103209/74610867-b0b8b900-50ff-11ea-8085-412254f96c06.png)
I asked the community.
https://community.openhab.org/t/colon-in-http-binding/92885
## Possible Solution
1. implement colon escaping
2. fix url-decode function

## Steps to Reproduce (for bugs)
1. Create http.items with record as above (with IP-address of existing http server)
2. Execute the url
3. Run tcpdump for capture packets
4. Watch captured url 

## Context
I have need to manage controllers that are controlled by http-get requests. These queries include the colon character.

## Your Environment
* Platform information:
  * OS: Ubuntu Server 18.04.4 LTS
  * Java Runtime Environment: openjdk version "1.8.0_163"
OpenJDK Runtime Environment (Zulu 8.28.0.1-linux64) (build 1.8.0_163-b01)
OpenJDK 64-Bit Server VM (Zulu 8.28.0.1-linux64) (build 25.163-b01, mixed mode)
  * openHAB version: 2.5.1
 binding-http1 - 1.14.0

**Comment by 9037568** [comment]
You can probably get your URL to work by setting the `format` parameter to FALSE.
See [this community forum thread](https://community.openhab.org/t/http-item-switching-socket-blitzwolf/92510/6).

But at any rate, no changes will be made to the binding, as this repository is closed.

**Comment by Dem72** [comment]
The `format` parameter has already been set to FALSE in http.cfg.
So, then there is no solution for this bug.
It's a pity :(

**Comment by 9037568** [comment]
You should try using the new [http action](https://www.openhab.org/docs/configuration/actions.html#http-actions) provided in OH2.
