### ISSUE TITLE
weather1 binding svg icons

### ISSUE THREAD

**Issue by bechte** [openhab/openhab1-addons#5943]
I like the weather1 binding very much but I wanted to use the weather icons in my HABpanel and, therefore, needed some svg icons instead of the png icons provided within the example.

I found nice icons at: https://www.amcharts.com/free-animated-svg-weather-icons/ and copy & pasted them to my installation by renaming the files accordingly to the condition states. The result is attached to this ticket. I used the animated version with a result like this:

![image](https://user-images.githubusercontent.com/453673/76424702-dfe1e380-63a8-11ea-8b74-f7aa073ff273.png)

I wonder if one would like to add these icons to the documentation? Just in case, I wanted to share the renamed files.

Best Bechte

[animated.zip](https://github.com/openhab/openhab1-addons/files/4318624/animated.zip)

**Comment by openhab-5iver** [comment]
This repo is dead, since the OH 1.x addons have been removed in OH 3.0. As of yet, this repo has not been archived or marked in some way to communicate this.
