### ISSUE TITLE
[Fritzbox Tr064] Enable Profile Switching

### ISSUE THREAD

**Issue by eric1905** [openhab/openhab1-addons#5950]
I would like to be able to switch the Profile in my Fritzbox.
Usecase: My daughter has a Profile called "Child" where she is allowed to use the internet. And there is a profile called Spotify to allow just to use spotify as it is in the whitelist.

I would like to be able to switch between this profiles for a specific device in openhab in the basic ui or in the rules. This could also be used to switch between the profiles "Standard" and "blocked" or any other profiles.

I know there exists a python script (https://github.com/flopp/fritz-switch-profiles) which is enabling this behaviour and this script is also in use by Home Assistant (https://github.com/mammuth/ha-fritzbox-tools/commit/e9e8f8e2c6f8c3e1147b862341faa1a911c7e518). But unfortunately this is not possible in Openhab at the moment.

## Expected Behavior
Be able to switch between 2 named profiles in the Fritzbox for a specific device

## Current Behavior
Not implemented at the moment.

**Comment by 9037568** [comment]
This repository is closed to new code.
