### ISSUE TITLE
[fritzboxtr064] Ability to read all phonebooks at once

### ISSUE THREAD

**Issue by beckerr-rzht** [openhab/openhab1-addons#5959]
Fritzboxtr064 binding is **unable to read all phone books at once**.
Instead one has to choose a special phone book to import.

I've provided a pull request for that 18 months ago and again one month ago:
https://github.com/openhab/openhab1-addons/pull/5955

It is quite simple and small.
Is there any change to get this included?

**Comment by 9037568** [comment]
No chance whatsoever. OH1 bindings can no longer be built.

**Comment by ptrooms** [comment]
> No chance whatsoever. OH1 bindings can no longer be built.

Does this mean that FritzBox is virtually dropped from (OpenHab built) support ?
I presume that the word "can not" is merely "will not" as Version1 is no longer built.

**Comment by 9037568** [comment]
No, when I say "can not", it's literal. The OH1 bindings cannot be built.
I'm not aware of all of the plans for OH3, but as far as I can tell, no OH1 bindings will work in OH3.

**Comment by ptrooms** [comment]
I accept your answer but wonder why we/I can no longer compile/built  this ..... imho the whole idea behind "open source" is that one should be able to build/compile. 

A (re)built should be as simple as "mvn .... clean install". At home I can compile OH1 bindings without any problem.

**Comment by J-N-K** [comment]
There will be a new Fritzbox TR064 binding. I‘m not 100% sure if „Phonebook“ is already implemented.

**Comment by jackzone** [comment]
I'm using different phonebooks too. The first one for private, the second one for corporate contacts (home office). By resolving the caller name I get notifications from my Echos using Alexa's TTS when somebody's calling. But at the moment it's only working for one phonebook.

So thumbs up for implementing the ability to read and store all available phonebooks.

**Comment by jackzone** [comment]
@J-N-K I just found this pull request [#6678](https://github.com/openhab/openhab-addons/pull/6678). It would be really great if you could implement this feature into the new TR064 Binding for OH3.

**Comment by J-N-K** [comment]
With the implementation in place now, you can select the phonebook in the profile. Do you want to lookup the phone number in all phonebooks at once? We should continue that discussion in #6678
