### ISSUE TITLE
CALDAV uses local time if DTSTART has no timezone information

### ISSUE THREAD

**Issue by tec-lab** [openhab/openhab1-addons#5973]
When using a desktop browser entering a new event in google calendar, there is no timestamp added, instead it assumes UTC if timezone is empty.
Here an extract of the .ics file:

```
BEGIN:VEVENT
DTSTART:20201119T133000Z
DTEND:20201119T143000Z
DTSTAMP:20201112T214406Z
UID:79ivo0gjfcci2c3c1n6tmmjnne@google.com
CREATED:20201112T214406Z
DESCRIPTION:
LAST-MODIFIED:20201112T214406Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Emil Grippe Impfen
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT0H30M0S
END:VALARM
END:VEVENT

```

When using the android app still there is a timezone added:
`DTSTART;TZID=Europe/Vienna:20201119T161500`

When CALDAV now parses `DTSTART:20201119T133000Z` it assumes a local time ... which is wrong.

Setting the caldavio:timeZone=UTC shows no effect.

I am currently on the master branch. Switching to stable shows no difference.

thx

**Comment by tec-lab** [comment]
By the way, I am on RaspPi (OpenHabian).

When I set the OS timezone to UTC and the runtime.cfg to `org.eclipse.smarthome.i18n:timezone=Europe/Vienna` the problem gets the opposite. The entry without timezone gets correctly parsed, the one with timezone gets one hour added.

So the most likely explanation is that the timezone of the `DTSTART` is not used at all.

**Comment by 9037568** [comment]
This repository is closed.
