### ISSUE TITLE
[org.openhab.binding.denonmarantz] or [org.openhab.binding.denon] Possibility to shortcut "All zone stereo" mode

### ISSUE THREAD

**Issue by sladaar** [openhab/openhab1-addons#5974]
Hi all!
Sorry if that's not the correct way to write down an idea.

I didn't find if it's possible, and how, to shortcut the "all zone stereo" mode with Denon AVRs (in the AVR-2400H (but i guess many others) it's under "option" on the remote). And with "shortcut" i mean using a single switch in OH, or even also some batch command.

Btw, what this mode does is swtiching any source to stereo and playing that on every speaker connected, even zone2, ecc, which is very very useful because it can, somehow, bypass the need of an expensive heos speaker.

I hope someone can help, and thanks in advance for the attention.
Best regards!

Ed

**Comment by 9037568** [comment]
Questions belong in the [community forum](http://community.openhab.org)
