### ISSUE TITLE
iCal compatibility with kanboar iCal

### ISSUE THREAD

**Issue by joni73** [openhab/openhab1-addons#5975]
can not use kanboard link as iCal address

http://mpi2.rdw.fi/kanboard/?controller=ICalendarController&action=project&token=22ef4176cd576bb8de33003736eec366804634c9c11050942164f289b7e8

That works Google,... ext 

Kanboard allows read only access.
more: https://docs.kanboard.org/en/latest/user_guide/ical.html

**Comment by 9037568** [comment]
If this is about the CalDAV binding, you're out of luck. This repository is closed.
Try using the icalendar binding instead.
