### ISSUE TITLE
Request for OH3 GPIO binding

### ISSUE THREAD

**Issue by ramybt** [openhab/openhab1-addons#5976]
Hi,

i been using this **Gpio Binding** for years, now with the new release of **openhab3** they have completely changed the game and they no longer using it, for someone don't know much about code it will be very hard to find such an easy way of  to connect  relay board to gpio .

my question here will you be working on making a new binding that will work with **OH3** ? is there another binding similar to this ?

thanks in advanced

**Comment by mstormi** [comment]
Watch out for the pigpio binding. I think it's in the snapshot.

Please close this issue and turn to the forum. Github is not the medium to ask for help.

**Comment by ramybt** [comment]
I have ask for help in the github repo for the gpio binding and waiting for solution,  mean while if i may keep this for further help.

**Comment by ramybt** [comment]
Looking through the internet, lots of people asking for this specific binding,  its very important for automation system and makes no sense the developer team had it taken,  although they did great jop on the UI and other stuff like adding new bindings but GPIO binding its extremely important to many users!

**Comment by mstormi** [comment]
Like I said this is the wrong medium so please close this issue. For questions turn to the forum please.

**Comment by 9037568** [comment]
This repository is closed. Further, there is an [OH3 binding](https://community.openhab.org/t/gpio-new-gpio-binding-for-oh3/113943) now.

**Comment by ramybt** [comment]
Why was that so hard to keep up ? Did that bring problems to you guys or just somthing you dont like?!
