### ISSUE TITLE
Koubachi is down since 2019

### ISSUE THREAD

**Issue by viper539** [openhab/openhab1-addons#5979]
Hi,

the Binding "Koubachi" can be removed because the Service is no more exictance since 2019.
https://github.com/openhab/openhab1-addons/tree/main/bundles/binding/org.openhab.binding.koubachi#koubachi-binding

Thank you!

**Comment by 9037568** [comment]
The repository is closed.

**Comment by bobadair** [comment]
I've added a note to https://github.com/openhab/openhab-addons/issues/6179 that the binding is obsolete because the service no longer exists.
