### ISSUE TITLE
Inconsistent paths in classic UI

### ISSUE THREAD

**Issue by cbrauers** [openhab/openhab1-addons#853]
In the snippets for the classic UI (org.openhab.ui.webapp), URLs are very inconsistent. Some images are referenced with a document-relative path, others use an absolute path. Yet others are plain wrong: Every single link to the CMD servlet treats it as if it were in a parent directory, yet accessing it in a way that this could be true (http://example:8080/openhab.app/?sitemap=example) leads to a broken page as paths to the Javascript, the CSS and most images become invalid. The only reason commands work in the correctly-accessed UI (without the slash between the .app and the ?) is that, from a browser's perspective, the working directory is the document root, so any "../"s are ignored.
I have uploaded changed snippets into a fork repository at https://github.com/cbrauers/openhab, opting to only use document-relative paths for better reverse proxy support (which is how I found out about the inconsistency in the first place).

**Comment by Shmixx** [comment]
Just wanted to chime in on this as I posted on the Google Groups board as well:
I'd love the ability to use mod_proxy with Apache, or a similar setup with NGINX for reverse proxying. The basic idea is that I do want this accessible externally (yes I have a VPN already) as trying to connect to a VPN first to be able to control the home makes it more difficult than it needs to be. I also have some location based apps on our phones that help for automating when we leave and come home, which needs access to the system to function from outside the home network. My career is in infosec, and while reducing the potential threat surface (OpenHAB accessible outside) is one approach, it doesn't necessarily work for everyone. Using a reverse proxy and controls on my router, I can effectively reduce the threat to my security. If people don't understand what they are doing and decide to do it, you can't stop them, and it's not anyone but their own fault. Given many of us know what we are doing, means we can safely and securely deploy this in an externally accessible mechanism. The reality is, using a reverse proxy with authentication, is stronger than the basic auth built into OpenHAB which also requires putting passwords in plain text on the local system. I'm going to add to the Git open item as well on this to help push for this in a 1.x version. Another advantage, is that I can effectively turn on HTTPS communication with OpenHAB via the reverse proxy, without needing to enable the actual HTTPS setup (certificate install, modification of keystrokes, etc for Jetty).

I'd also add that this is not an exotic use case either. It may not be the most common for all users, but for plenty of folks who have these systems in place for external access, this is more of a norm than anything. Its basically the difference between people just testing the waters, vs folks who are already running external access. Neither of which can be considered the norm or exotic.

**Comment by kaikreuzer** [comment]
Note that this feature has by now already been addressed in openHAB 2, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=431410 <https://bugs.eclipse.org/bugs/show_bug.cgi?id=431410> and https://github.com/openhab/openhab2/blob/master/docs/sources/configuration/jetty.md <https://github.com/openhab/openhab2/blob/master/docs/sources/configuration/jetty.md>.

Feel free to create a PR for openHAB 1 with similar changes.

**Comment by renini** [comment]
Has anyone try to fix this on openHAB 1? Really want to use a reverse proxy for this.
