### ISSUE TITLE
Android: Switches do not update correctly

### ISSUE THREAD

**Issue by s0129** [openhab/openhab1-addons#902]
On android switches with multiple mappings do not update when pressed. This works correctly on the http version.
An example is the android Demo 'Discrete Widgets'. 
Switch item=Scene_General label="Scene" mappings=[1=TV, 2=Dinner, 3=Reading]
If you select Dinner the UI is not updated until the app is closed and then reopened.

Regards

Simon

**Comment by Fl0te** [comment]
Hi andrey-desman.

How is it going on the HDL/SmartBus binding?

**Comment by aaronsutton** [comment]
I'm still having this issue using openHAB 1.6 and android version 1.5.1.1. Is there any resolution to this?

**Comment by mauroMCW** [comment]
same issue for me, suddenly hadroid can't update devices status. 
Web front-end via browser works fine.
Habdroid works only if I click on "Clear images cache" or exit and enter again in the application.
No logs related to this issue on openhab.log.
I tried to delete all habdroid data, reboot the terminal and reinstall the application.

I have 22 items in habdroid home page. I don't know if that can interfere.
Openhab Version 1.6.2
Habdroid Versio 1.5.1,1
Android Lollipop

**Comment by kobelka** [comment]
I have the same problems as mauroMCW

**Comment by mauroMCW** [comment]
I Fixed restarting openhab service on server side.

**Comment by aaronsutton** [comment]
Restarting the service does not correct this issue for me. For me, it
wasn't that this issue suddenly surfaced, I've never had the switches
update properly.

--
Aaron

**Comment by belovictor** [comment]
This is a problem with openHAB updates, not with the app.

**Comment by aaronsutton** [comment]
This issue still exists for me with openHAB 1.7. Is it resolved in 2.0?

**Comment by brunoabele** [comment]
Same problem on openHAB 1.7.1 with HabDroid 1.7.0.1, web interface work fine

**Comment by 1technophile** [comment]
same problem on 1.7.0 with habdroid

**Comment by stefanst** [comment]
same problem with 1.7.1 and Habdroid. Web UI works fine.

**Comment by chjop** [comment]
Since this is issue is closed and this is the wrong tracker I comment here: https://github.com/openhab/openhab.android/issues/129
