### ISSUE TITLE
HABDroid: SetPoint behaviour buggy

### ISSUE THREAD

**Issue by schinken** [openhab/openhab1-addons#981]
Problem described in this thread:
    https://groups.google.com/forum/#!topic/openhab/H5PqvMdJbOQ

Summary:

If you have step=0.5 and tap on "+", the value changes from 4.0 to 4.5 - which OpenHAB successfully receives, but another tap on "+" won't change the value anymore - only if you switch to another page and back. 

Then you're able again to change the value from 4.5 to 5.0.
The same is true for the other direction, decrementing the value.

A simple setup to reproduce the bug:

example.items

<pre>
Number testObject "Value [%1.f]"
</pre>

example.sitemap

<pre>
Setpoint item=testObject minValue=10 maxValue=30 step=0.5
</pre>

**Comment by onoffpt** [comment]
Hum...found the same issue. I am not alone then.
Found out that going to settings are returning (even without making changes) lets you increase the setpoint again (Not a solution obviously).
Any news on this bug ?
